const fs = require('fs');

const quizzes = [
  {
    fileName: "gandhi_early_sat_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1026,
        "title": "Gandhian Era (Early Satyagrahas)",
        "title_hi": "गांधीवादी युग (प्रारंभिक सत्याग्रह)",
        "description": "Gandhi in South Africa & Early Satyagrahas in India.",
        "description_hi": "दक्षिण अफ्रीका में गांधी और भारत में प्रारंभिक सत्याग्रह।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "In which year did Mahatma Gandhi return to India from South Africa?",
          "question_hi": "महात्मा गांधी दक्षिण अफ्रीका से भारत किस वर्ष लौटे थे?",
          "option_a": "1914",
          "option_b": "1915",
          "option_c": "1916",
          "option_d": "1917",
          "option_a_hi": "1914",
          "option_b_hi": "1915",
          "option_c_hi": "1916",
          "option_d_hi": "1917",
          "correct_option": 2,
          "explanation": "Gandhi returned to India on January 9, 1915, which is now celebrated as Pravasi Bharatiya Divas.",
          "explanation_hi": "गांधी 9 जनवरी, 1915 को भारत लौटे थे, जिसे अब प्रवासी भारतीय दिवस के रूप में मनाया जाता है।"
        },
        {
          "question": "Who was Mahatma Gandhi's political guru?",
          "question_hi": "महात्मा गांधी के राजनीतिक गुरु कौन थे?",
          "option_a": "Bal Gangadhar Tilak",
          "option_b": "Dadabhai Naoroji",
          "option_c": "Gopal Krishna Gokhale",
          "option_d": "Lala Lajpat Rai",
          "option_a_hi": "बाल गंगाधर तिलक",
          "option_b_hi": "दादाभाई नौरोजी",
          "option_c_hi": "गोपाल कृष्ण गोखले",
          "option_d_hi": "लाला लाजपत राय",
          "correct_option": 3,
          "explanation": "Gokhale advised Gandhi to spend a year traveling across India to understand the country before entering politics.",
          "explanation_hi": "गोखले ने राजनीति में प्रवेश करने से पहले गांधी को देश को समझने के लिए पूरे भारत में एक साल की यात्रा करने की सलाह दी थी।"
        },
        {
          "question": "Which of the following ashrams was established by Mahatma Gandhi in South Africa?",
          "question_hi": "दक्षिण अफ्रीका में महात्मा गांधी द्वारा निम्नलिखित में से किस आश्रम की स्थापना की गई थी?",
          "option_a": "Sabarmati Ashram",
          "option_b": "Tolstoy Farm",
          "option_c": "Sevagram Ashram",
          "option_d": "Sadaqat Ashram",
          "option_a_hi": "साबरमती आश्रम",
          "option_b_hi": "टॉलस्टॉय फार्म",
          "option_c_hi": "सेवाग्राम आश्रम",
          "option_d_hi": "सदाकत आश्रम",
          "correct_option": 2,
          "explanation": "Gandhi established the Phoenix Settlement and Tolstoy Farm in South Africa.",
          "explanation_hi": "गांधी ने दक्षिण अफ्रीका में फीनिक्स सेटलमेंट और टॉलस्टॉय फार्म की स्थापना की।"
        },
        {
          "question": "Which was the first civil disobedience movement launched by Mahatma Gandhi in India?",
          "question_hi": "भारत में महात्मा गांधी द्वारा शुरू किया गया पहला सविनय अवज्ञा आंदोलन कौन सा था?",
          "option_a": "Kheda Satyagraha",
          "option_b": "Ahmedabad Mill Strike",
          "option_c": "Champaran Satyagraha",
          "option_d": "Rowlatt Satyagraha",
          "option_a_hi": "खेड़ा सत्याग्रह",
          "option_b_hi": "अहमदाबाद मिल हड़ताल",
          "option_c_hi": "चंपारण सत्याग्रह",
          "option_d_hi": "रॉलेट सत्याग्रह",
          "correct_option": 3,
          "explanation": "The Champaran Satyagraha (1917) was his first major involvement in Indian politics (first Civil Disobedience).",
          "explanation_hi": "चंपारण सत्याग्रह (1917) भारतीय राजनीति में उनका पहला बड़ा हस्तक्षेप था (पहला सविनय अवज्ञा)।"
        },
        {
          "question": "Who invited Gandhi to Champaran to look into the problems of indigo planters?",
          "question_hi": "नील बागान मालिकों की समस्याओं को देखने के लिए गांधी को चंपारण किसने आमंत्रित किया था?",
          "option_a": "Rajendra Prasad",
          "option_b": "Rajkumar Shukla",
          "option_c": "J.B. Kripalani",
          "option_d": "Motilal Nehru",
          "option_a_hi": "राजेंद्र प्रसाद",
          "option_b_hi": "राजकुमार शुक्ल",
          "option_c_hi": "जे.बी. कृपलानी",
          "option_d_hi": "मोतीलाल नेहरू",
          "correct_option": 2,
          "explanation": "Rajkumar Shukla, a local peasant, relentlessly pursued Gandhi to visit Champaran.",
          "explanation_hi": "एक स्थानीय किसान राजकुमार शुक्ल ने गांधी से चंपारण आने का लगातार आग्रह किया था।"
        },
        {
          "question": "The Champaran Satyagraha was directed against which oppressive system?",
          "question_hi": "चंपारण सत्याग्रह किस दमनकारी व्यवस्था के खिलाफ निर्देशित था?",
          "option_a": "Ryotwari system",
          "option_b": "Tinkathia system",
          "option_c": "Mahalwari system",
          "option_d": "Zamindari system",
          "option_a_hi": "रैयतवाड़ी व्यवस्था",
          "option_b_hi": "तिनकठिया प्रथा",
          "option_c_hi": "महलवाड़ी व्यवस्था",
          "option_d_hi": "जमींदारी व्यवस्था",
          "correct_option": 2,
          "explanation": "Under the Tinkathia system, peasants were forced to cultivate indigo on 3/20th of their landholdings.",
          "explanation_hi": "तिनकठिया प्रथा के तहत, किसानों को अपनी जोत के 3/20वें हिस्से पर नील की खेती करने के लिए मजबूर किया गया था।"
        },
        {
          "question": "In which movement did Mahatma Gandhi use hunger strike as a weapon for the first time?",
          "question_hi": "महात्मा गांधी ने किस आंदोलन में पहली बार भूख हड़ताल का हथियार के रूप में इस्तेमाल किया?",
          "option_a": "Champaran Satyagraha",
          "option_b": "Rowlatt Satyagraha",
          "option_c": "Ahmedabad Mill Strike",
          "option_d": "Kheda Satyagraha",
          "option_a_hi": "चंपारण सत्याग्रह",
          "option_b_hi": "रॉलेट सत्याग्रह",
          "option_c_hi": "अहमदाबाद मिल हड़ताल",
          "option_d_hi": "खेड़ा सत्याग्रह",
          "correct_option": 3,
          "explanation": "Gandhi undertook his first fast unto death during the Ahmedabad Mill Strike (1918) to secure a 35% wage hike for workers.",
          "explanation_hi": "गांधी ने श्रमिकों के लिए 35% वेतन वृद्धि सुरक्षित करने के लिए अहमदाबाद मिल हड़ताल (1918) के दौरान अपना पहला आमरण अनशन किया था।"
        },
        {
          "question": "The Kheda Satyagraha (1918) was fought to demand:",
          "question_hi": "खेड़ा सत्याग्रह (1918) किस मांग को लेकर लड़ा गया था?",
          "option_a": "Remission of land revenue due to crop failure",
          "option_b": "Increase in wages of mill workers",
          "option_c": "Abolition of the salt tax",
          "option_d": "Right to forest produce for tribals",
          "option_a_hi": "फसल खराब होने के कारण भू-राजस्व में छूट",
          "option_b_hi": "मिल मजदूरों की मजदूरी में वृद्धि",
          "option_c_hi": "नमक कर का उन्मूलन",
          "option_d_hi": "आदिवासियों के लिए वनोपज का अधिकार",
          "correct_option": 1,
          "explanation": "Due to drought, crops failed in Kheda (Gujarat), but the government refused to remit land revenue.",
          "explanation_hi": "सूखे के कारण, खेड़ा (गुजरात) में फसलें खराब हो गईं, लेकिन सरकार ने भू-राजस्व माफ करने से इनकार कर दिया।"
        },
        {
          "question": "Who among the following emerged as a prominent leader alongside Gandhi during the Kheda Satyagraha?",
          "question_hi": "खेड़ा सत्याग्रह के दौरान गांधीजी के साथ निम्नलिखित में से कौन एक प्रमुख नेता के रूप में उभरा?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Sardar Vallabhbhai Patel",
          "option_c": "Subhas Chandra Bose",
          "option_d": "B.R. Ambedkar",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "सरदार वल्लभभाई पटेल",
          "option_c_hi": "सुभाष चंद्र बोस",
          "option_d_hi": "बी.आर. अम्बेडकर",
          "correct_option": 2,
          "explanation": "Vallabhbhai Patel left his lucrative legal practice to support Gandhi in Kheda.",
          "explanation_hi": "वल्लभभाई पटेल ने खेड़ा में गांधीजी का समर्थन करने के लिए अपनी आकर्षक कानूनी प्रैक्टिस छोड़ दी।"
        },
        {
          "question": "Which act, passed in 1919, gave the government enormous powers to repress political activities and allowed detention of political prisoners without trial for two years?",
          "question_hi": "1919 में पारित किस अधिनियम ने सरकार को राजनीतिक गतिविधियों को दबाने के लिए अपार शक्तियाँ दीं और राजनीतिक कैदियों को बिना मुकदमे के दो साल तक हिरासत में रखने की अनुमति दी?",
          "option_a": "Vernacular Press Act",
          "option_b": "Ilbert Bill",
          "option_c": "Rowlatt Act",
          "option_d": "Defense of India Act",
          "option_a_hi": "वर्नाक्यूलर प्रेस एक्ट",
          "option_b_hi": "इल्बर्ट बिल",
          "option_c_hi": "रॉलेट एक्ट",
          "option_d_hi": "डिफेंस ऑफ इंडिया एक्ट",
          "correct_option": 3,
          "explanation": "The Anarchical and Revolutionary Crimes Act of 1919, popularly known as the Rowlatt Act.",
          "explanation_hi": "अराजक और क्रांतिकारी अपराध अधिनियम 1919, जिसे लोकप्रिय रूप से रॉलेट एक्ट के रूप में जाना जाता है।"
        },
        {
          "question": "Gandhi organized a nationwide hartal (strike) against the Rowlatt Act on:",
          "question_hi": "गांधीजी ने रॉलेट एक्ट के खिलाफ देशव्यापी हड़ताल का आयोजन कब किया था?",
          "option_a": "April 6, 1919",
          "option_b": "April 13, 1919",
          "option_c": "March 23, 1919",
          "option_d": "January 26, 1919",
          "option_a_hi": "6 अप्रैल, 1919",
          "option_b_hi": "13 अप्रैल, 1919",
          "option_c_hi": "23 मार्च, 1919",
          "option_d_hi": "26 जनवरी, 1919",
          "correct_option": 1,
          "explanation": "He called for a nationwide Satyagraha (hartal) on 6th April 1919 against the unjust Rowlatt Act.",
          "explanation_hi": "उन्होंने अन्यायपूर्ण रॉलेट एक्ट के खिलाफ 6 अप्रैल 1919 को राष्ट्रव्यापी सत्याग्रह (हड़ताल) का आह्वान किया।"
        },
        {
          "question": "The Jallianwala Bagh massacre took place on April 13, 1919, on the day of which festival?",
          "question_hi": "13 अप्रैल, 1919 को जलियांवाला बाग हत्याकांड किस त्योहार के दिन हुआ था?",
          "option_a": "Lohri",
          "option_b": "Baisakhi",
          "option_c": "Diwali",
          "option_d": "Holi",
          "option_a_hi": "लोहड़ी",
          "option_b_hi": "बैसाखी",
          "option_c_hi": "दीवाली",
          "option_d_hi": "होली",
          "correct_option": 2,
          "explanation": "A large, peaceful crowd had gathered on the Baisakhi festival in the enclosed ground of Jallianwala Bagh.",
          "explanation_hi": "जलियांवाला बाग के बंद मैदान में बैसाखी के त्योहार पर एक बड़ी, शांतिपूर्ण भीड़ एकत्र हुई थी।"
        },
        {
          "question": "Which two nationalist leaders were arrested in Amritsar, prompting the public gathering at Jallianwala Bagh?",
          "question_hi": "अमृतसर में किन दो राष्ट्रवादी नेताओं को गिरफ्तार किया गया था, जिसके कारण जलियांवाला बाग में सार्वजनिक सभा हुई?",
          "option_a": "Lala Lajpat Rai and Ajit Singh",
          "option_b": "Dr. Saifuddin Kitchlew and Dr. Satyapal",
          "option_c": "Bhagat Singh and Chandrashekhar Azad",
          "option_d": "Madan Mohan Malaviya and Motilal Nehru",
          "option_a_hi": "लाला लाजपत राय और अजीत सिंह",
          "option_b_hi": "डॉ. सैफुद्दीन किचलू और डॉ. सत्यपाल",
          "option_c_hi": "भगत सिंह और चंद्रशेखर आज़ाद",
          "option_d_hi": "मदन मोहन मालवीय और मोतीलाल नेहरू",
          "correct_option": 2,
          "explanation": "The crowd gathered partly to celebrate Baisakhi and partly to protest the arrest of Dr. Kitchlew and Dr. Satyapal under the Rowlatt Act.",
          "explanation_hi": "भीड़ आंशिक रूप से बैसाखी मनाने के लिए और आंशिक रूप से रॉलेट एक्ट के तहत डॉ. किचलू और डॉ. सत्यपाल की गिरफ्तारी का विरोध करने के लिए एकत्र हुई थी।"
        },
        {
          "question": "Who was the British general responsible for the Jallianwala Bagh massacre?",
          "question_hi": "जलियांवाला बाग हत्याकांड के लिए जिम्मेदार ब्रिटिश जनरल कौन था?",
          "option_a": "General O'Dwyer",
          "option_b": "General Reginald Dyer",
          "option_c": "Lord Chelmsford",
          "option_d": "Lord Reading",
          "option_a_hi": "जनरल ओ डायर",
          "option_b_hi": "जनरल रेजिनाल्ड डायर",
          "option_c_hi": "लॉर्ड चेम्सफोर्ड",
          "option_d_hi": "लॉर्ड रीडिंग",
          "correct_option": 2,
          "explanation": "Brigadier-General Reginald Dyer ordered the troops to fire on the unarmed crowd.",
          "explanation_hi": "ब्रिगेडियर-जनरल रेजिनाल्ड डायर ने सैनिकों को निहत्थी भीड़ पर गोली चलाने का आदेश दिया था।"
        },
        {
          "question": "In protest against the Jallianwala Bagh massacre, who renounced his 'Knighthood'?",
          "question_hi": "जलियांवाला बाग हत्याकांड के विरोध में, किसने अपना 'नाइटहुड' (Knighthood) त्याग दिया?",
          "option_a": "Mahatma Gandhi",
          "option_b": "Subramaniya Iyer",
          "option_c": "Rabindranath Tagore",
          "option_d": "S.N. Banerjee",
          "option_a_hi": "महात्मा गांधी",
          "option_b_hi": "सुब्रमण्यम अय्यर",
          "option_c_hi": "रवींद्रनाथ टैगोर",
          "option_d_hi": "एस.एन. बनर्जी",
          "correct_option": 3,
          "explanation": "Rabindranath Tagore returned his knighthood to the British in profound shock and protest.",
          "explanation_hi": "रवींद्रनाथ टैगोर ने गहरे सदमे और विरोध में अंग्रेजों को अपनी नाइटहुड की उपाधि वापस कर दी।"
        }
      ]
    }
  },
  {
    fileName: "ncm_khilafat_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1027,
        "title": "Non-Cooperation Movement & Khilafat",
        "title_hi": "असहयोग आंदोलन और खिलाफत",
        "description": "Causes, Spread, and Chauri Chaura incident.",
        "description_hi": "कारण, प्रसार, और चौरी चौरा घटना।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The Khilafat Movement was organized to protest against the injustice done to which country after World War I?",
          "question_hi": "प्रथम विश्व युद्ध के बाद किस देश के साथ हुए अन्याय के विरोध में खिलाफत आंदोलन आयोजित किया गया था?",
          "option_a": "Egypt",
          "option_b": "Iran",
          "option_c": "Turkey",
          "option_d": "Saudi Arabia",
          "option_a_hi": "मिस्र",
          "option_b_hi": "ईरान",
          "option_c_hi": "तुर्की",
          "option_d_hi": "सऊदी अरब",
          "correct_option": 3,
          "explanation": "It was launched by Indian Muslims to protest the harsh Treaty of Sèvres imposed on the Ottoman Empire (Turkey) and its ruler, the Caliph.",
          "explanation_hi": "इसे भारतीय मुसलमानों द्वारा ओटोमन साम्राज्य (तुर्की) और उसके शासक, खलीफा पर लगाई गई कठोर सेवर्स की संधि (Treaty of Sèvres) का विरोध करने के लिए शुरू किया गया था।"
        },
        {
          "question": "Who were the principal leaders of the Khilafat Movement in India?",
          "question_hi": "भारत में खिलाफत आंदोलन के प्रमुख नेता कौन थे?",
          "option_a": "Sir Syed Ahmad Khan and Aga Khan",
          "option_b": "Muhammad Ali and Shaukat Ali (Ali Brothers)",
          "option_c": "M.A. Jinnah and Liaquat Ali Khan",
          "option_d": "Khan Abdul Ghaffar Khan and Abul Kalam Azad",
          "option_a_hi": "सर सैयद अहमद खान और आगा खान",
          "option_b_hi": "मुहम्मद अली और शौकत अली (अली बंधु)",
          "option_c_hi": "एम.ए. जिन्ना और लियाकत अली खान",
          "option_d_hi": "खान अब्दुल गफ्फार खान और अबुल कलाम आजाद",
          "correct_option": 2,
          "explanation": "The Ali Brothers, Maulana Azad, Hakim Ajmal Khan, and Hasrat Mohani were the key leaders.",
          "explanation_hi": "अली बंधु, मौलाना आजाद, हकीम अजमल खान और हसरत मोहानी प्रमुख नेता थे।"
        },
        {
          "question": "Why did Mahatma Gandhi support the Khilafat Movement?",
          "question_hi": "महात्मा गांधी ने खिलाफत आंदोलन का समर्थन क्यों किया?",
          "option_a": "To secure British support for Indian independence",
          "option_b": "To bring Hindus and Muslims together on a common national platform",
          "option_c": "He was a staunch supporter of the Ottoman Empire",
          "option_d": "To oppose the Muslim League",
          "option_a_hi": "भारतीय स्वतंत्रता के लिए ब्रिटिश समर्थन प्राप्त करने के लिए",
          "option_b_hi": "हिंदुओं और मुसलमानों को एक साझा राष्ट्रीय मंच पर लाने के लिए",
          "option_c_hi": "वह ओटोमन साम्राज्य के कट्टर समर्थक थे",
          "option_d_hi": "मुस्लिम लीग का विरोध करने के लिए",
          "correct_option": 2,
          "explanation": "Gandhi saw the Khilafat issue as an opportunity to cement Hindu-Muslim unity against the British.",
          "explanation_hi": "गांधी ने खिलाफत मुद्दे को अंग्रेजों के खिलाफ हिंदू-मुस्लिम एकता को मजबूत करने के अवसर के रूप में देखा।"
        },
        {
          "question": "The Non-Cooperation Movement was officially launched by the Congress in which session in 1920?",
          "question_hi": "1920 के किस अधिवेशन में कांग्रेस द्वारा आधिकारिक तौर पर असहयोग आंदोलन शुरू किया गया था?",
          "option_a": "Surat Session",
          "option_b": "Lahore Session",
          "option_c": "Nagpur Session",
          "option_d": "Lucknow Session",
          "option_a_hi": "सूरत अधिवेशन",
          "option_b_hi": "लाहौर अधिवेशन",
          "option_c_hi": "नागपुर अधिवेशन",
          "option_d_hi": "लखनऊ अधिवेशन",
          "correct_option": 3,
          "explanation": "A special session at Calcutta approved it in Sept 1920, and the regular Nagpur session in Dec 1920 ratified the Non-Cooperation resolution.",
          "explanation_hi": "सितंबर 1920 में कलकत्ता में एक विशेष सत्र ने इसे मंजूरी दी, और दिसंबर 1920 में नियमित नागपुर सत्र ने असहयोग प्रस्ताव की पुष्टि की।"
        },
        {
          "question": "Which of the following was NOT a part of the Non-Cooperation Movement's program?",
          "question_hi": "निम्नलिखित में से कौन सा असहयोग आंदोलन के कार्यक्रम का हिस्सा नहीं था?",
          "option_a": "Boycott of government schools and colleges",
          "option_b": "Boycott of foreign cloth",
          "option_c": "Armed rebellion against British army camps",
          "option_d": "Resignation from government titles and honors",
          "option_a_hi": "सरकारी स्कूलों और कॉलेजों का बहिष्कार",
          "option_b_hi": "विदेशी कपड़ों का बहिष्कार",
          "option_c_hi": "ब्रिटिश सेना के शिविरों के खिलाफ सशस्त्र विद्रोह",
          "option_d_hi": "सरकारी उपाधियों और सम्मानों से त्यागपत्र",
          "correct_option": 3,
          "explanation": "The movement was strictly based on non-violence (Satyagraha) and did not include armed rebellion.",
          "explanation_hi": "आंदोलन पूरी तरह से अहिंसा (सत्याग्रह) पर आधारित था और इसमें सशस्त्र विद्रोह शामिल नहीं था।"
        },
        {
          "question": "Who among the following gave up his lucrative legal practice during the Non-Cooperation Movement?",
          "question_hi": "असहयोग आंदोलन के दौरान निम्नलिखित में से किसने अपनी आकर्षक कानूनी प्रैक्टिस (वकालत) छोड़ दी थी?",
          "option_a": "Motilal Nehru",
          "option_b": "C.R. Das",
          "option_c": "Sardar Patel",
          "option_d": "All of the above",
          "option_a_hi": "मोतीलाल नेहरू",
          "option_b_hi": "सी.आर. दास",
          "option_c_hi": "सरदार पटेल",
          "option_d_hi": "उपर्युक्त सभी",
          "correct_option": 4,
          "explanation": "Many eminent lawyers like Motilal Nehru, C.R. Das, C. Rajagopalachari, and Sardar Patel boycotted the courts and gave up their practices.",
          "explanation_hi": "मोतीलाल नेहरू, सी.आर. दास, सी. राजगोपालाचारी और सरदार पटेल जैसे कई प्रख्यात वकीलों ने अदालतों का बहिष्कार किया और अपनी प्रैक्टिस छोड़ दी।"
        },
        {
          "question": "The title 'Kaiser-i-Hind' was returned to the British government by:",
          "question_hi": "'कैसर-ए-हिंद' की उपाधि ब्रिटिश सरकार को किसके द्वारा वापस कर दी गई थी?",
          "option_a": "Rabindranath Tagore",
          "option_b": "Mahatma Gandhi",
          "option_c": "Bal Gangadhar Tilak",
          "option_d": "Dadabhai Naoroji",
          "option_a_hi": "रवींद्रनाथ टैगोर",
          "option_b_hi": "महात्मा गांधी",
          "option_c_hi": "बाल गंगाधर तिलक",
          "option_d_hi": "दादाभाई नौरोजी",
          "correct_option": 2,
          "explanation": "Gandhi returned his Kaiser-i-Hind gold medal, awarded for his humanitarian work in South Africa, as a protest against the Khilafat wrong and the Punjab atrocities.",
          "explanation_hi": "गांधीजी ने दक्षिण अफ्रीका में अपने मानवीय कार्यों के लिए दिए गए अपने कैसर-ए-हिंद स्वर्ण पदक को खिलाफत के गलत होने और पंजाब के अत्याचारों के विरोध के रूप में वापस कर दिया।"
        },
        {
          "question": "Which historic event led Mahatma Gandhi to abruptly call off the Non-Cooperation Movement in February 1922?",
          "question_hi": "किस ऐतिहासिक घटना के कारण महात्मा गांधी ने फरवरी 1922 में असहयोग आंदोलन को अचानक वापस ले लिया?",
          "option_a": "Kakori Train Robbery",
          "option_b": "Jallianwala Bagh Massacre",
          "option_c": "Chauri Chaura Incident",
          "option_d": "Arrest of Ali Brothers",
          "option_a_hi": "काकोरी ट्रेन डकैती",
          "option_b_hi": "जलियांवाला बाग हत्याकांड",
          "option_c_hi": "चौरी चौरा घटना",
          "option_d_hi": "अली बंधुओं की गिरफ्तारी",
          "correct_option": 3,
          "explanation": "At Chauri Chaura (UP), an angry mob set fire to a police station, killing 22 policemen. Appalled by the violence, Gandhi halted the movement.",
          "explanation_hi": "चौरी चौरा (यूपी) में, एक उग्र भीड़ ने एक पुलिस स्टेशन में आग लगा दी, जिसमें 22 पुलिसकर्मी मारे गए। हिंसा से स्तब्ध होकर, गांधी ने आंदोलन रोक दिया।"
        },
        {
          "question": "The Chauri Chaura incident occurred in which present-day district of Uttar Pradesh?",
          "question_hi": "चौरी चौरा की घटना उत्तर प्रदेश के किस वर्तमान जिले में हुई थी?",
          "option_a": "Varanasi",
          "option_b": "Gorakhpur",
          "option_c": "Allahabad",
          "option_d": "Lucknow",
          "option_a_hi": "वाराणसी",
          "option_b_hi": "गोरखपुर",
          "option_c_hi": "इलाहाबाद",
          "option_d_hi": "लखनऊ",
          "correct_option": 2,
          "explanation": "Chauri Chaura is a town in the Gorakhpur district of UP.",
          "explanation_hi": "चौरी चौरा यूपी के गोरखपुर जिले का एक कस्बा है।"
        },
        {
          "question": "Which prominent leader famously remarked that the suspension of the movement was a 'national calamity'?",
          "question_hi": "किस प्रमुख नेता ने प्रसिद्ध टिप्पणी की थी कि आंदोलन का निलंबन एक 'राष्ट्रीय आपदा' (National Calamity) थी?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Motilal Nehru",
          "option_c": "Subhas Chandra Bose",
          "option_d": "C.R. Das",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "मोतीलाल नेहरू",
          "option_c_hi": "सुभाष चंद्र बोस",
          "option_d_hi": "सी.आर. दास",
          "correct_option": 3,
          "explanation": "Subhas Chandra Bose and many young leaders were shocked and called it a 'national calamity' when public enthusiasm was at a boiling point.",
          "explanation_hi": "सुभाष चंद्र बोस और कई युवा नेता स्तब्ध थे और जब सार्वजनिक उत्साह चरम पर था, तो इसे 'राष्ट्रीय आपदा' कहा।"
        },
        {
          "question": "During the Non-Cooperation Movement, who was the founder of the 'Jamia Millia Islamia' in Aligarh (later moved to Delhi)?",
          "question_hi": "असहयोग आंदोलन के दौरान, अलीगढ़ (बाद में दिल्ली स्थानांतरित) में 'जामिया मिलिया इस्लामिया' के संस्थापक कौन थे?",
          "option_a": "Sir Syed Ahmad Khan",
          "option_b": "Maulana Abul Kalam Azad and Hakim Ajmal Khan",
          "option_c": "Muhammad Ali Jinnah",
          "option_d": "Liaquat Ali Khan",
          "option_a_hi": "सर सैयद अहमद खान",
          "option_b_hi": "मौलाना अबुल कलाम आजाद और हकीम अजमल खान",
          "option_c_hi": "मुहम्मद अली जिन्ना",
          "option_d_hi": "लियाकत अली खान",
          "correct_option": 2,
          "explanation": "Nationalist Muslim leaders like Zakir Husain, Maulana Azad, and Hakim Ajmal Khan established Jamia to boycott government educational institutions.",
          "explanation_hi": "जाकिर हुसैन, मौलाना आजाद और हकीम अजमल खान जैसे राष्ट्रवादी मुस्लिम नेताओं ने सरकारी शिक्षण संस्थानों का बहिष्कार करने के लिए जामिया की स्थापना की।"
        },
        {
          "question": "Which of the following peasant movements coincided with the Non-Cooperation movement in Awadh?",
          "question_hi": "अवध में असहयोग आंदोलन के साथ-साथ निम्नलिखित में से कौन सा किसान आंदोलन हुआ?",
          "option_a": "Moplah Rebellion",
          "option_b": "Eka Movement",
          "option_c": "Tebhaga Movement",
          "option_d": "Telangana Movement",
          "option_a_hi": "मोपला विद्रोह",
          "option_b_hi": "एका आंदोलन",
          "option_c_hi": "तेभागा आंदोलन",
          "option_d_hi": "तेलंगाना आंदोलन",
          "correct_option": 2,
          "explanation": "The Eka (Unity) movement in Awadh (1921-22) led by Madari Pasi emerged from the worsening conditions of peasants, closely linked to the NCM.",
          "explanation_hi": "मदारी पासी के नेतृत्व में अवध (1921-22) में एका (एकता) आंदोलन किसानों की बिगड़ती स्थिति से उभरा, जो NCM से निकटता से जुड़ा था।"
        },
        {
          "question": "Who was arrested along with Gandhi after the Chauri Chaura incident?",
          "question_hi": "चौरी चौरा घटना के बाद गांधीजी के साथ किसे गिरफ्तार किया गया था?",
          "option_a": "Gandhi was arrested alone and sentenced to 6 years",
          "option_b": "Jawaharlal Nehru",
          "option_c": "Subhas Chandra Bose",
          "option_d": "Vallabhbhai Patel",
          "option_a_hi": "गांधीजी को अकेले गिरफ्तार किया गया और 6 साल की सजा सुनाई गई",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "सुभाष चंद्र बोस",
          "option_d_hi": "वल्लभभाई पटेल",
          "correct_option": 1,
          "explanation": "Gandhi was arrested in March 1922 and charged with sedition. Judge Broomfield sentenced him to 6 years of imprisonment.",
          "explanation_hi": "मार्च 1922 में गांधीजी को गिरफ्तार कर लिया गया और उन पर राजद्रोह का आरोप लगाया गया। न्यायाधीश ब्रूमफील्ड ने उन्हें 6 साल की जेल की सजा सुनाई।"
        },
        {
          "question": "The Moplah Rebellion of 1921 took place in which region?",
          "question_hi": "1921 का मोपला विद्रोह किस क्षेत्र में हुआ था?",
          "option_a": "Bengal",
          "option_b": "Malabar (Kerala)",
          "option_c": "Punjab",
          "option_d": "Awadh (UP)",
          "option_a_hi": "बंगाल",
          "option_b_hi": "मालाबार (केरल)",
          "option_c_hi": "पंजाब",
          "option_d_hi": "अवध (यूपी)",
          "correct_option": 2,
          "explanation": "The Moplah (Muslim peasants) rebellion in Malabar started as part of the Khilafat movement but soon took a violent, communal turn against Hindu landlords.",
          "explanation_hi": "मालाबार में मोपला (मुस्लिम किसान) विद्रोह खिलाफत आंदोलन के हिस्से के रूप में शुरू हुआ, लेकिन जल्द ही हिंदू जमींदारों के खिलाफ एक हिंसक, सांप्रदायिक मोड़ ले लिया।"
        },
        {
          "question": "At which session did the Indian National Congress ratify the resolution to pass the Non-Cooperation Movement and restructure the Congress working committee?",
          "question_hi": "किस अधिवेशन में भारतीय राष्ट्रीय कांग्रेस ने असहयोग आंदोलन को पारित करने और कांग्रेस कार्य समिति का पुनर्गठन करने के प्रस्ताव की पुष्टि की?",
          "option_a": "Amritsar, 1919",
          "option_b": "Calcutta (Special), 1920",
          "option_c": "Nagpur, 1920",
          "option_d": "Gaya, 1922",
          "option_a_hi": "अमृतसर, 1919",
          "option_b_hi": "कलकत्ता (विशेष), 1920",
          "option_c_hi": "नागपुर, 1920",
          "option_d_hi": "गया, 1922",
          "correct_option": 3,
          "explanation": "The Nagpur session in Dec 1920 was historic; it ratified NCM and made structural changes like creating a 15-member Congress Working Committee (CWC).",
          "explanation_hi": "दिसंबर 1920 में नागपुर अधिवेशन ऐतिहासिक था; इसने NCM की पुष्टि की और 15 सदस्यीय कांग्रेस वर्किंग कमेटी (CWC) बनाने जैसे संरचनात्मक बदलाव किए।"
        }
      ]
    }
  },
  {
    fileName: "swaraj_simon_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1028,
        "title": "Swaraj Party, Simon Commission & Nehru Report",
        "title_hi": "स्वराज पार्टी, साइमन कमीशन और नेहरू रिपोर्ट",
        "description": "Politics of the 1920s.",
        "description_hi": "1920 के दशक की राजनीति।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The Swaraj Party was formed in 1923 by:",
          "question_hi": "स्वराज पार्टी का गठन 1923 में किसके द्वारा किया गया था?",
          "option_a": "Mahatma Gandhi and Vallabhbhai Patel",
          "option_b": "Motilal Nehru and C.R. Das",
          "option_c": "Jawaharlal Nehru and Subhas Chandra Bose",
          "option_d": "B.G. Tilak and Annie Besant",
          "option_a_hi": "महात्मा गांधी और वल्लभभाई पटेल",
          "option_b_hi": "मोतीलाल नेहरू और सी.आर. दास",
          "option_c_hi": "जवाहरलाल नेहरू और सुभाष चंद्र बोस",
          "option_d_hi": "बी.जी. तिलक और एनी बेसेंट",
          "correct_option": 2,
          "explanation": "Chittaranjan Das (President) and Motilal Nehru (Secretary) formed the Congress-Khilafat Swarajya Party, better known as the Swaraj Party.",
          "explanation_hi": "चित्तरंजन दास (अध्यक्ष) और मोतीलाल नेहरू (सचिव) ने कांग्रेस-खिलाफत स्वराज्य पार्टी का गठन किया, जिसे स्वराज पार्टी के नाम से जाना जाता है।"
        },
        {
          "question": "What was the main political strategy of the Swaraj Party?",
          "question_hi": "स्वराज पार्टी की मुख्य राजनीतिक रणनीति क्या थी?",
          "option_a": "To organize an armed rebellion against the British",
          "option_b": "To boycott all legislative councils and focus on constructive work",
          "option_c": "To enter the legislative councils and wreck the government from within",
          "option_d": "To demand separate electorates for all minorities",
          "option_a_hi": "अंग्रेजों के खिलाफ सशस्त्र विद्रोह का आयोजन करना",
          "option_b_hi": "सभी विधान परिषदों का बहिष्कार करना और रचनात्मक कार्यों पर ध्यान केंद्रित करना",
          "option_c_hi": "विधान परिषदों में प्रवेश करना और भीतर से सरकार को बर्बाद करना",
          "option_d_hi": "सभी अल्पसंख्यकों के लिए अलग निर्वाचक मंडल की मांग करना",
          "correct_option": 3,
          "explanation": "The 'Pro-changers' wanted to end the boycott of councils, enter them, and obstruct the working of the unjust government from within.",
          "explanation_hi": "'परिवर्तनवादी' (Pro-changers) परिषदों के बहिष्कार को समाप्त करना चाहते थे, उनमें प्रवेश करना चाहते थे, और भीतर से अन्यायपूर्ण सरकार के कामकाज में बाधा डालना चाहते थे।"
        },
        {
          "question": "The leaders who opposed council entry and wanted to focus on Gandhi's constructive programme were known as:",
          "question_hi": "जो नेता परिषद में प्रवेश का विरोध करते थे और गांधी के रचनात्मक कार्यक्रम पर ध्यान केंद्रित करना चाहते थे, उन्हें किस रूप में जाना जाता था?",
          "option_a": "Pro-changers",
          "option_b": "No-changers",
          "option_c": "Extremists",
          "option_d": "Revolutionaries",
          "option_a_hi": "प्रो-चेंजर्स (परिवर्तनवादी)",
          "option_b_hi": "नो-चेंजर्स (अपरिवर्तनवादी)",
          "option_c_hi": "चरमपंथी",
          "option_d_hi": "क्रांतिकारी",
          "correct_option": 2,
          "explanation": "Leaders like C. Rajagopalachari, Vallabhbhai Patel, and Rajendra Prasad were called 'No-changers'.",
          "explanation_hi": "सी. राजगोपालाचारी, वल्लभभाई पटेल और राजेंद्र प्रसाद जैसे नेताओं को 'नो-चेंजर्स' (अपरिवर्तनवादी) कहा जाता था।"
        },
        {
          "question": "Who among the following was elected as the President of the Central Legislative Assembly in 1925, a major victory for the Swaraj Party?",
          "question_hi": "निम्नलिखित में से किसे 1925 में केंद्रीय विधान सभा के अध्यक्ष (Speaker) के रूप में चुना गया था, जो स्वराज पार्टी की एक बड़ी जीत थी?",
          "option_a": "Motilal Nehru",
          "option_b": "C.R. Das",
          "option_c": "Vithalbhai Patel",
          "option_d": "Sardar Vallabhbhai Patel",
          "option_a_hi": "मोतीलाल नेहरू",
          "option_b_hi": "सी.आर. दास",
          "option_c_hi": "विट्ठलभाई पटेल",
          "option_d_hi": "सरदार वल्लभभाई पटेल",
          "correct_option": 3,
          "explanation": "Vithalbhai Patel (brother of Sardar Patel) became the first Indian to be elected as the President (Speaker) of the Central Assembly.",
          "explanation_hi": "विट्ठलभाई पटेल (सरदार पटेल के भाई) केंद्रीय विधान सभा के अध्यक्ष (स्पीकर) चुने जाने वाले पहले भारतीय बने।"
        },
        {
          "question": "Why was the Simon Commission (1927) completely boycotted by Indians?",
          "question_hi": "भारतीयों द्वारा साइमन कमीशन (1927) का पूरी तरह से बहिष्कार क्यों किया गया था?",
          "option_a": "It proposed the partition of India.",
          "option_b": "It did not include a single Indian member.",
          "option_c": "It proposed to abolish the provincial assemblies.",
          "option_d": "It recommended the shifting of the capital back to Calcutta.",
          "option_a_hi": "इसने भारत के विभाजन का प्रस्ताव रखा।",
          "option_b_hi": "इसमें एक भी भारतीय सदस्य शामिल नहीं था।",
          "option_c_hi": "इसने प्रांतीय विधानसभाओं को समाप्त करने का प्रस्ताव रखा।",
          "option_d_hi": "इसने राजधानी को वापस कलकत्ता स्थानांतरित करने की सिफारिश की।",
          "correct_option": 2,
          "explanation": "The Indian Statutory Commission (Simon Commission) consisted of seven British MPs and zero Indians, which was seen as an insult.",
          "explanation_hi": "भारतीय वैधानिक आयोग (साइमन कमीशन) में सात ब्रिटिश सांसद और शून्य भारतीय शामिल थे, जिसे एक अपमान के रूप में देखा गया।"
        },
        {
          "question": "Which prominent nationalist leader died due to injuries sustained during a police lathi-charge while protesting against the Simon Commission in Lahore?",
          "question_hi": "लाहौर में साइमन कमीशन का विरोध करते हुए पुलिस लाठीचार्ज के दौरान लगी चोटों के कारण किस प्रमुख राष्ट्रवादी नेता की मृत्यु हो गई?",
          "option_a": "Bipin Chandra Pal",
          "option_b": "Bal Gangadhar Tilak",
          "option_c": "Lala Lajpat Rai",
          "option_d": "C.R. Das",
          "option_a_hi": "बिपिन चंद्र पाल",
          "option_b_hi": "बाल गंगाधर तिलक",
          "option_c_hi": "लाला लाजपत राय",
          "option_d_hi": "सी.आर. दास",
          "correct_option": 3,
          "explanation": "Lala Lajpat Rai was severely beaten on Oct 30, 1928, and died on Nov 17, 1928, declaring 'every blow... will be a nail in the coffin of the British Empire'.",
          "explanation_hi": "लाला लाजपत राय को 30 अक्टूबर, 1928 को बुरी तरह पीटा गया था, और 17 नवंबर, 1928 को उनकी मृत्यु हो गई।"
        },
        {
          "question": "The Nehru Report (1928) was drafted under the chairmanship of:",
          "question_hi": "नेहरू रिपोर्ट (1928) का मसौदा किसकी अध्यक्षता में तैयार किया गया था?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Motilal Nehru",
          "option_c": "Tej Bahadur Sapru",
          "option_d": "Subhas Chandra Bose",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "मोतीलाल नेहरू",
          "option_c_hi": "तेज बहादुर सप्रू",
          "option_d_hi": "सुभाष चंद्र बोस",
          "correct_option": 2,
          "explanation": "Motilal Nehru chaired the committee formed by the All Parties Conference to draft a constitution for India.",
          "explanation_hi": "भारत के लिए संविधान का मसौदा तैयार करने के लिए सर्वदलीय सम्मेलन द्वारा गठित समिति की अध्यक्षता मोतीलाल नेहरू ने की थी।"
        },
        {
          "question": "What was the core constitutional demand made by the Nehru Report (1928)?",
          "question_hi": "नेहरू रिपोर्ट (1928) द्वारा की गई मुख्य संवैधानिक मांग क्या थी?",
          "option_a": "Purna Swaraj (Complete Independence)",
          "option_b": "Dominion Status for India",
          "option_c": "Balkanization of India",
          "option_d": "Continuation of dyarchy",
          "option_a_hi": "पूर्ण स्वराज (पूर्ण स्वतंत्रता)",
          "option_b_hi": "भारत के लिए डोमिनियन स्टेटस",
          "option_c_hi": "भारत का बाल्कनीकरण",
          "option_d_hi": "द्वैध शासन (dyarchy) की निरंतरता",
          "correct_option": 2,
          "explanation": "The Nehru Report demanded Dominion Status as the next immediate step, which angered young leaders like Jawaharlal Nehru and Subhas Bose who wanted Purna Swaraj.",
          "explanation_hi": "नेहरू रिपोर्ट ने अगले तत्काल कदम के रूप में डोमिनियन स्टेटस की मांग की, जिससे जवाहरलाल नेहरू और सुभाष बोस जैसे युवा नेता नाराज हो गए जो पूर्ण स्वराज चाहते थे।"
        },
        {
          "question": "Regarding the electoral system, what did the Nehru Report recommend?",
          "question_hi": "निर्वाचन प्रणाली के संबंध में, नेहरू रिपोर्ट ने क्या सिफारिश की थी?",
          "option_a": "Continuation of separate electorates for Muslims",
          "option_b": "Joint electorates with reservation of seats for minorities",
          "option_c": "Separate electorates for depressed classes",
          "option_d": "Universal adult franchise without any reservations",
          "option_a_hi": "मुसलमानों के लिए अलग निर्वाचक मंडल जारी रखना",
          "option_b_hi": "अल्पसंख्यकों के लिए सीटों के आरक्षण के साथ संयुक्त निर्वाचक मंडल",
          "option_c_hi": "दलित वर्गों के लिए अलग निर्वाचक मंडल",
          "option_d_hi": "बिना किसी आरक्षण के सार्वभौमिक वयस्क मताधिकार",
          "correct_option": 2,
          "explanation": "It rejected separate electorates and proposed joint electorates with reservation of seats for Muslims in provinces where they were a minority.",
          "explanation_hi": "इसने अलग निर्वाचक मंडलों को खारिज कर दिया और उन प्रांतों में मुसलमानों के लिए सीटों के आरक्षण के साथ संयुक्त निर्वाचक मंडल का प्रस्ताव रखा जहां वे अल्पसंख्यक थे।"
        },
        {
          "question": "In response to the Nehru Report, who proposed the famous 'Fourteen Points' in 1929 to safeguard Muslim interests?",
          "question_hi": "नेहरू रिपोर्ट के जवाब में, मुस्लिम हितों की रक्षा के लिए 1929 में प्रसिद्ध 'चौदह सूत्र' (Fourteen Points) का प्रस्ताव किसने दिया था?",
          "option_a": "Aga Khan",
          "option_b": "Maulana Abul Kalam Azad",
          "option_c": "Muhammad Ali Jinnah",
          "option_d": "Allama Iqbal",
          "option_a_hi": "आगा खान",
          "option_b_hi": "मौलाना अबुल कलाम आजाद",
          "option_c_hi": "मुहम्मद अली जिन्ना",
          "option_d_hi": "अल्लामा इकबाल",
          "correct_option": 3,
          "explanation": "Jinnah rejected the Nehru Report and formulated his 'Fourteen Points', which demanded a weak center and one-third representation for Muslims.",
          "explanation_hi": "जिन्ना ने नेहरू रिपोर्ट को खारिज कर दिया और अपने 'चौदह सूत्र' तैयार किए, जिसमें एक कमजोर केंद्र और मुसलमानों के लिए एक तिहाई प्रतिनिधित्व की मांग की गई थी।"
        },
        {
          "question": "Who founded the 'Independence for India League' in opposition to the Nehru Report's acceptance of Dominion Status?",
          "question_hi": "नेहरू रिपोर्ट द्वारा डोमिनियन स्टेटस की स्वीकृति के विरोध में 'इंडिपेंडेंस फॉर इंडिया लीग' (Independence for India League) की स्थापना किसने की?",
          "option_a": "Bhagat Singh and Chandrashekhar Azad",
          "option_b": "Jawaharlal Nehru and Subhas Chandra Bose",
          "option_c": "Sardar Patel and Rajendra Prasad",
          "option_d": "C.R. Das and Motilal Nehru",
          "option_a_hi": "भगत सिंह और चंद्रशेखर आज़ाद",
          "option_b_hi": "जवाहरलाल नेहरू और सुभाष चंद्र बोस",
          "option_c_hi": "सरदार पटेल और राजेंद्र प्रसाद",
          "option_d_hi": "सी.आर. दास और मोतीलाल नेहरू",
          "correct_option": 2,
          "explanation": "The younger section of the Congress led by Jawaharlal and Subhas organized the League to press for complete independence.",
          "explanation_hi": "जवाहरलाल और सुभाष के नेतृत्व वाले कांग्रेस के युवा वर्ग ने पूर्ण स्वतंत्रता के लिए दबाव बनाने के लिए लीग का आयोजन किया।"
        },
        {
          "question": "The Bardoli Satyagraha (1928), a successful peasant movement against a 22% tax hike, was led by:",
          "question_hi": "22% कर वृद्धि के खिलाफ एक सफल किसान आंदोलन, बारडोली सत्याग्रह (1928) का नेतृत्व किसके द्वारा किया गया था?",
          "option_a": "Mahatma Gandhi",
          "option_b": "Vallabhbhai Patel",
          "option_c": "Vinoba Bhave",
          "option_d": "Indulal Yagnik",
          "option_a_hi": "महात्मा गांधी",
          "option_b_hi": "वल्लभभाई पटेल",
          "option_c_hi": "विनोबा भावे",
          "option_d_hi": "इंदुलाल याज्ञनिक",
          "correct_option": 2,
          "explanation": "Vallabhbhai Patel led this movement so successfully that the women of Bardoli bestowed the title 'Sardar' upon him.",
          "explanation_hi": "वल्लभभाई पटेल ने इस आंदोलन का इतनी सफलतापूर्वक नेतृत्व किया कि बारडोली की महिलाओं ने उन्हें 'सरदार' की उपाधि से सम्मानित किया।"
        },
        {
          "question": "Which Viceroy made the vague 'Deepavali Declaration' (1929) offering Dominion Status to India in the future?",
          "question_hi": "भविष्य में भारत को डोमिनियन स्टेटस देने की पेशकश करते हुए किस वायसराय ने अस्पष्ट 'दीपावली घोषणा' (1929) की थी?",
          "option_a": "Lord Chelmsford",
          "option_b": "Lord Reading",
          "option_c": "Lord Irwin",
          "option_d": "Lord Linlithgow",
          "option_a_hi": "लॉर्ड चेम्सफोर्ड",
          "option_b_hi": "लॉर्ड रीडिंग",
          "option_c_hi": "लॉर्ड इरविन",
          "option_d_hi": "लॉर्ड लिनलिथगो",
          "correct_option": 3,
          "explanation": "Lord Irwin's declaration simply stated that the natural issue of India's constitutional progress was the attainment of Dominion Status.",
          "explanation_hi": "लॉर्ड इरविन की घोषणा में केवल यह कहा गया था कि भारत की संवैधानिक प्रगति का स्वाभाविक परिणाम डोमिनियन स्टेटस प्राप्त करना था।"
        },
        {
          "question": "The public boycott of the Simon Commission was famously led in Lucknow by:",
          "question_hi": "लखनऊ में साइमन कमीशन के सार्वजनिक बहिष्कार का प्रसिद्ध नेतृत्व किसके द्वारा किया गया था?",
          "option_a": "Govind Ballabh Pant and Jawaharlal Nehru",
          "option_b": "Sardar Patel and Morarji Desai",
          "option_c": "Khan Abdul Ghaffar Khan",
          "option_d": "Subhas Chandra Bose",
          "option_a_hi": "गोविंद बल्लभ पंत और जवाहरलाल नेहरू",
          "option_b_hi": "सरदार पटेल और मोरारजी देसाई",
          "option_c_hi": "खान अब्दुल गफ्फार खान",
          "option_d_hi": "सुभाष चंद्र बोस",
          "correct_option": 1,
          "explanation": "In Lucknow, Govind Ballabh Pant and Jawaharlal Nehru led the procession and were severely beaten by the police.",
          "explanation_hi": "लखनऊ में, गोविंद बल्लभ पंत और जवाहरलाल नेहरू ने जुलूस का नेतृत्व किया और पुलिस ने उन्हें बुरी तरह पीटा।"
        },
        {
          "question": "When the Swaraj Party won several seats in 1923, what was the primary response of the British government to their obstructionist tactics?",
          "question_hi": "जब स्वराज पार्टी ने 1923 में कई सीटें जीतीं, तो उनकी बाधावादी रणनीति पर ब्रिटिश सरकार की प्राथमिक प्रतिक्रिया क्या थी?",
          "option_a": "They immediately granted Dominion Status",
          "option_b": "The Viceroy used his veto and certification powers extensively to bypass the legislature",
          "option_c": "They banned the Swaraj Party",
          "option_d": "They arrested all members of the assembly",
          "option_a_hi": "उन्होंने तुरंत डोमिनियन स्टेटस प्रदान किया",
          "option_b_hi": "वायसराय ने विधायिका को दरकिनार करने के लिए अपने वीटो और प्रमाणन (certification) शक्तियों का बड़े पैमाने पर उपयोग किया",
          "option_c_hi": "उन्होंने स्वराज पार्टी पर प्रतिबंध लगा दिया",
          "option_d_hi": "उन्होंने विधानसभा के सभी सदस्यों को गिरफ्तार कर लिया",
          "correct_option": 2,
          "explanation": "Since the Swarajists defeated government bills repeatedly, the Viceroy resorted to 'certifying' bills, exposing the autocratic nature of the councils.",
          "explanation_hi": "चूंकि स्वराजवादियों ने सरकारी विधेयकों को बार-बार हराया, वायसराय ने विधेयकों को 'प्रमाणित' (certify) करने का सहारा लिया, जिससे परिषदों की निरंकुश प्रकृति उजागर हुई।"
        }
      ]
    }
  }
];

async function insertAll() {
  for (const q of quizzes) {
    fs.writeFileSync(q.fileName, JSON.stringify(q.data, null, 2));
  }
}
insertAll();
