const fs = require('fs');

const quizzes = [
  {
    fileName: "cdm_rtc_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1029,
        "title": "Civil Disobedience Movement & RTC",
        "title_hi": "सविनय अवज्ञा आंदोलन और गोलमेज सम्मेलन",
        "description": "Dandi March, Gandhi-Irwin Pact, and Round Table Conferences.",
        "description_hi": "दांडी मार्च, गांधी-इरविन समझौता और गोलमेज सम्मेलन।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The Civil Disobedience Movement was started by Mahatma Gandhi in 1930 with the famous:",
          "question_hi": "सविनय अवज्ञा आंदोलन 1930 में महात्मा गांधी द्वारा किस प्रसिद्ध घटना के साथ शुरू किया गया था?",
          "option_a": "Chauri Chaura incident",
          "option_b": "Dandi March",
          "option_c": "Quit India resolution",
          "option_d": "Champaran Satyagraha",
          "option_a_hi": "चौरी चौरा की घटना",
          "option_b_hi": "दांडी मार्च",
          "option_c_hi": "भारत छोड़ो प्रस्ताव",
          "option_d_hi": "चंपारण सत्याग्रह",
          "correct_option": 2,
          "explanation": "Gandhi started the movement by marching from Sabarmati to Dandi to break the salt law.",
          "explanation_hi": "गांधीजी ने नमक कानून तोड़ने के लिए साबरमती से दांडी तक मार्च करके आंदोलन की शुरुआत की।"
        },
        {
          "question": "On which date did Mahatma Gandhi break the salt law at Dandi?",
          "question_hi": "महात्मा गांधी ने दांडी में नमक कानून किस तारीख को तोड़ा था?",
          "option_a": "March 12, 1930",
          "option_b": "April 6, 1930",
          "option_c": "August 8, 1942",
          "option_d": "January 26, 1930",
          "option_a_hi": "12 मार्च, 1930",
          "option_b_hi": "6 अप्रैल, 1930",
          "option_c_hi": "8 अगस्त, 1942",
          "option_d_hi": "26 जनवरी, 1930",
          "correct_option": 2,
          "explanation": "The march started on March 12 and Gandhi reached Dandi and broke the law on April 6, 1930.",
          "explanation_hi": "मार्च 12 मार्च को शुरू हुआ और गांधीजी 6 अप्रैल 1930 को दांडी पहुंचे और कानून तोड़ा।"
        },
        {
          "question": "Who among the following leaders led the Salt Satyagraha in Tamil Nadu?",
          "question_hi": "निम्नलिखित में से किस नेता ने तमिलनाडु में नमक सत्याग्रह का नेतृत्व किया?",
          "option_a": "C. Rajagopalachari",
          "option_b": "K. Kelappan",
          "option_c": "T. Prakasam",
          "option_d": "Sarojini Naidu",
          "option_a_hi": "सी. राजगोपालाचारी",
          "option_b_hi": "के. केलप्पन",
          "option_c_hi": "टी. प्रकाशम",
          "option_d_hi": "सरोजिनी नायडू",
          "correct_option": 1,
          "explanation": "C. Rajagopalachari organized a march from Tiruchirappalli to Vedaranyam on the Tanjore coast to break the salt law.",
          "explanation_hi": "सी. राजगोपालाचारी ने नमक कानून तोड़ने के लिए तिरुचिरापल्ली से तंजौर तट पर वेदारण्यम तक एक मार्च का आयोजन किया।"
        },
        {
          "question": "Who is known as the 'Frontier Gandhi' for leading the Khudai Khidmatgars (Red Shirts) during the Civil Disobedience Movement?",
          "question_hi": "सविनय अवज्ञा आंदोलन के दौरान 'खुदाई खिदमतगार' (लाल कुर्ती) का नेतृत्व करने के लिए किसे 'सीमांत गांधी' (Frontier Gandhi) के रूप में जाना जाता है?",
          "option_a": "Khan Abdul Ghaffar Khan",
          "option_b": "Maulana Abul Kalam Azad",
          "option_c": "Syed Ahmad Khan",
          "option_d": "Liaquat Ali Khan",
          "option_a_hi": "खान अब्दुल गफ्फार खान",
          "option_b_hi": "मौलाना अबुल कलाम आजाद",
          "option_c_hi": "सैयद अहमद खान",
          "option_d_hi": "लियाकत अली खान",
          "correct_option": 1,
          "explanation": "Khan Abdul Ghaffar Khan led a massive non-violent movement in the North-West Frontier Province.",
          "explanation_hi": "खान अब्दुल गफ्फार खान ने उत्तर-पश्चिम सीमा प्रांत में एक बड़े पैमाने पर अहिंसक आंदोलन का नेतृत्व किया।"
        },
        {
          "question": "The Gandhi-Irwin Pact was signed in which year to suspend the Civil Disobedience Movement?",
          "question_hi": "सविनय अवज्ञा आंदोलन को निलंबित करने के लिए गांधी-इरविन समझौते पर किस वर्ष हस्ताक्षर किए गए थे?",
          "option_a": "1930",
          "option_b": "1931",
          "option_c": "1932",
          "option_d": "1933",
          "option_a_hi": "1930",
          "option_b_hi": "1931",
          "option_c_hi": "1932",
          "option_d_hi": "1933",
          "correct_option": 2,
          "explanation": "Signed on March 5, 1931, it led to the suspension of the movement and Congress's participation in the Second Round Table Conference.",
          "explanation_hi": "5 मार्च, 1931 को हस्ताक्षरित, इसके कारण आंदोलन को निलंबित कर दिया गया और दूसरे गोलमेज सम्मेलन में कांग्रेस की भागीदारी हुई।"
        },
        {
          "question": "At which Congress session in 1931 was the Gandhi-Irwin Pact endorsed and a resolution on Fundamental Rights and National Economic Programme passed?",
          "question_hi": "1931 में किस कांग्रेस अधिवेशन में गांधी-इरविन समझौते का समर्थन किया गया और मौलिक अधिकारों और राष्ट्रीय आर्थिक कार्यक्रम पर एक प्रस्ताव पारित किया गया?",
          "option_a": "Lahore Session",
          "option_b": "Karachi Session",
          "option_c": "Faizpur Session",
          "option_d": "Haripura Session",
          "option_a_hi": "लाहौर अधिवेशन",
          "option_b_hi": "कराची अधिवेशन",
          "option_c_hi": "फैजपुर अधिवेशन",
          "option_d_hi": "हरिपुरा अधिवेशन",
          "correct_option": 2,
          "explanation": "The Karachi Session (1931), presided over by Sardar Vallabhbhai Patel, endorsed the pact and passed the famous resolution.",
          "explanation_hi": "सरदार वल्लभभाई पटेल की अध्यक्षता में कराची अधिवेशन (1931) ने समझौते का समर्थन किया और प्रसिद्ध प्रस्ताव पारित किया।"
        },
        {
          "question": "Who represented the Indian National Congress at the Second Round Table Conference in London?",
          "question_hi": "लंदन में दूसरे गोलमेज सम्मेलन में भारतीय राष्ट्रीय कांग्रेस का प्रतिनिधित्व किसने किया था?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Motilal Nehru",
          "option_c": "Mahatma Gandhi",
          "option_d": "Subhas Chandra Bose",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "मोतीलाल नेहरू",
          "option_c_hi": "महात्मा गांधी",
          "option_d_hi": "सुभाष चंद्र बोस",
          "correct_option": 3,
          "explanation": "Mahatma Gandhi was the sole representative of the INC at the Second Round Table Conference in 1931.",
          "explanation_hi": "महात्मा गांधी 1931 में दूसरे गोलमेज सम्मेलन में INC के एकमात्र प्रतिनिधि थे।"
        },
        {
          "question": "Who attended all three Round Table Conferences held in London?",
          "question_hi": "लंदन में आयोजित तीनों गोलमेज सम्मेलनों में किसने भाग लिया था?",
          "option_a": "Mahatma Gandhi",
          "option_b": "B.R. Ambedkar and Tej Bahadur Sapru",
          "option_c": "Jawaharlal Nehru and Sardar Patel",
          "option_d": "Muhammad Ali Jinnah and Aga Khan",
          "option_a_hi": "महात्मा गांधी",
          "option_b_hi": "बी.आर. अम्बेडकर और तेज बहादुर सप्रू",
          "option_c_hi": "जवाहरलाल नेहरू और सरदार पटेल",
          "option_d_hi": "मुहम्मद अली जिन्ना और आगा खान",
          "correct_option": 2,
          "explanation": "Dr. B.R. Ambedkar and Tej Bahadur Sapru attended all three RTCs.",
          "explanation_hi": "डॉ बी.आर. अंबेडकर और तेज बहादुर सप्रू ने तीनों गोलमेज सम्मेलनों में भाग लिया।"
        },
        {
          "question": "The Communal Award (1932), which granted separate electorates to the depressed classes, was announced by which British Prime Minister?",
          "question_hi": "कम्युनल अवार्ड (1932), जिसने दलित वर्गों को अलग निर्वाचक मंडल प्रदान किया, की घोषणा किस ब्रिटिश प्रधान मंत्री ने की थी?",
          "option_a": "Winston Churchill",
          "option_b": "Ramsay MacDonald",
          "option_c": "Clement Attlee",
          "option_d": "Lord Mountbatten",
          "option_a_hi": "विंस्टन चर्चिल",
          "option_b_hi": "रामसे मैकडोनाल्ड",
          "option_c_hi": "क्लेमेंट एटली",
          "option_d_hi": "लॉर्ड माउंटबेटन",
          "correct_option": 2,
          "explanation": "Ramsay MacDonald announced the Communal Award in August 1932.",
          "explanation_hi": "रामसे मैकडोनाल्ड ने अगस्त 1932 में कम्युनल अवार्ड (सांप्रदायिक पंचाट) की घोषणा की थी।"
        },
        {
          "question": "The Poona Pact (1932) was an agreement between:",
          "question_hi": "पूना समझौता (1932) किसके बीच एक समझौता था?",
          "option_a": "Gandhi and Lord Irwin",
          "option_b": "Gandhi and B.R. Ambedkar",
          "option_c": "Jawaharlal Nehru and Subhas Chandra Bose",
          "option_d": "INC and Muslim League",
          "option_a_hi": "गांधी और लॉर्ड इरविन",
          "option_b_hi": "गांधी और बी.आर. अम्बेडकर",
          "option_c_hi": "जवाहरलाल नेहरू और सुभाष चंद्र बोस",
          "option_d_hi": "INC और मुस्लिम लीग",
          "correct_option": 2,
          "explanation": "It was an agreement between Mahatma Gandhi and Dr. B.R. Ambedkar to abandon separate electorates for depressed classes in favor of reserved seats within the general electorate.",
          "explanation_hi": "यह महात्मा गांधी और डॉ. बी.आर. अंबेडकर के बीच दलित वर्गों के लिए अलग निर्वाचक मंडल को छोड़कर आम निर्वाचक मंडल के भीतर आरक्षित सीटों के पक्ष में एक समझौता था।"
        },
        {
          "question": "In 1932, Mahatma Gandhi founded which organization to eradicate untouchability?",
          "question_hi": "1932 में, महात्मा गांधी ने छुआछूत को मिटाने के लिए किस संगठन की स्थापना की?",
          "option_a": "Bahishkrit Hitakarini Sabha",
          "option_b": "Harijan Sevak Sangh",
          "option_c": "Satyashodhak Samaj",
          "option_d": "Servants of India Society",
          "option_a_hi": "बहिष्कृत हितकारिणी सभा",
          "option_b_hi": "हरिजन सेवक संघ",
          "option_c_hi": "सत्यशोधक समाज",
          "option_d_hi": "सर्वेंट्स ऑफ इंडिया सोसाइटी",
          "correct_option": 2,
          "explanation": "Gandhi founded the All India Anti-Untouchability League, later renamed as Harijan Sevak Sangh.",
          "explanation_hi": "गांधीजी ने अखिल भारतीय अस्पृश्यता विरोधी लीग की स्थापना की, जिसका नाम बाद में हरिजन सेवक संघ रखा गया।"
        },
        {
          "question": "Who famously led a raid on the Dharasana Salt Works after Gandhi's arrest during the Salt Satyagraha?",
          "question_hi": "नमक सत्याग्रह के दौरान गांधीजी की गिरफ्तारी के बाद किसने धरसाना नमक कारखाने पर छापे का प्रसिद्ध नेतृत्व किया था?",
          "option_a": "Abbas Tyabji and Sarojini Naidu",
          "option_b": "Jawaharlal Nehru",
          "option_c": "Vallabhbhai Patel",
          "option_d": "Madan Mohan Malaviya",
          "option_a_hi": "अब्बास तैयबजी और सरोजिनी नायडू",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "वल्लभभाई पटेल",
          "option_d_hi": "मदन मोहन मालवीय",
          "correct_option": 1,
          "explanation": "Following Gandhi's arrest, Abbas Tyabji and then Sarojini Naidu led the non-violent march to the Dharasana salt works where protesters were brutally beaten.",
          "explanation_hi": "गांधीजी की गिरफ्तारी के बाद, अब्बास तैयबजी और फिर सरोजिनी नायडू ने धरसाना नमक कारखाने तक अहिंसक मार्च का नेतृत्व किया, जहां प्रदर्शनकारियों को बेरहमी से पीटा गया।"
        },
        {
          "question": "Rani Gaidinliu, who rebelled against the British and was sentenced to life imprisonment at the age of 16, belonged to which region?",
          "question_hi": "रानी गाईदिन्ल्यू, जिन्होंने अंग्रेजों के खिलाफ विद्रोह किया और उन्हें 16 साल की उम्र में आजीवन कारावास की सजा सुनाई गई, किस क्षेत्र से संबंधित थीं?",
          "option_a": "Punjab",
          "option_b": "Naga Hills (Manipur/Nagaland)",
          "option_c": "Malabar",
          "option_d": "Awadh",
          "option_a_hi": "पंजाब",
          "option_b_hi": "नागा हिल्स (मणिपुर/नागालैंड)",
          "option_c_hi": "मालाबार",
          "option_d_hi": "अवध",
          "correct_option": 2,
          "explanation": "Rani Gaidinliu led a revolt in the Naga hills during the Civil Disobedience movement. Jawaharlal Nehru gave her the title of 'Rani'.",
          "explanation_hi": "रानी गाईदिन्ल्यू ने सविनय अवज्ञा आंदोलन के दौरान नागा पहाड़ियों में विद्रोह का नेतृत्व किया। जवाहरलाल नेहरू ने उन्हें 'रानी' की उपाधि दी।"
        },
        {
          "question": "Which round table conference was completely boycotted by the Indian National Congress?",
          "question_hi": "किस गोलमेज सम्मेलन का भारतीय राष्ट्रीय कांग्रेस द्वारा पूरी तरह से बहिष्कार किया गया था?",
          "option_a": "First Round Table Conference",
          "option_b": "Second Round Table Conference",
          "option_c": "First and Third Round Table Conferences",
          "option_d": "None of the above",
          "option_a_hi": "प्रथम गोलमेज सम्मेलन",
          "option_b_hi": "द्वितीय गोलमेज सम्मेलन",
          "option_c_hi": "प्रथम और तृतीय गोलमेज सम्मेलन",
          "option_d_hi": "इनमें से कोई नहीं",
          "correct_option": 3,
          "explanation": "Congress boycotted the First (1930) and the Third (1932) Round Table Conferences. Gandhi attended only the Second (1931).",
          "explanation_hi": "कांग्रेस ने पहले (1930) और तीसरे (1932) गोलमेज सम्मेलनों का बहिष्कार किया। गांधीजी ने केवल दूसरे (1931) में भाग लिया था।"
        },
        {
          "question": "In which prison did Mahatma Gandhi undertake a fast unto death against the Communal Award?",
          "question_hi": "महात्मा गांधी ने सांप्रदायिक पंचाट (Communal Award) के खिलाफ किस जेल में आमरण अनशन किया था?",
          "option_a": "Aga Khan Palace, Pune",
          "option_b": "Yerawada Central Jail, Pune",
          "option_c": "Cellular Jail, Andaman",
          "option_d": "Alipore Jail, Calcutta",
          "option_a_hi": "आगा खान पैलेस, पुणे",
          "option_b_hi": "यरवदा सेंट्रल जेल, पुणे",
          "option_c_hi": "सेल्यूलर जेल, अंडमान",
          "option_d_hi": "अलीपुर जेल, कलकत्ता",
          "correct_option": 2,
          "explanation": "Gandhi, who was imprisoned in Yerawada jail in Pune, began a fast unto death in Sept 1932 which led to the Poona Pact.",
          "explanation_hi": "पुणे की यरवदा जेल में बंद गांधीजी ने सितंबर 1932 में आमरण अनशन शुरू किया, जिसके कारण पूना समझौता हुआ।"
        }
      ]
    }
  },
  {
    fileName: "elections_tripuri_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1030,
        "title": "1937 Elections, Ministries & Tripuri Crisis",
        "title_hi": "1937 के चुनाव, मंत्रालय और त्रिपुरी संकट",
        "description": "Provincial elections and Subhas Chandra Bose.",
        "description_hi": "प्रांतीय चुनाव और सुभाष चंद्र बोस।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "Which Government of India Act provided for provincial autonomy and the establishment of an All-India Federation?",
          "question_hi": "भारत सरकार के किस अधिनियम ने प्रांतीय स्वायत्तता (provincial autonomy) और अखिल भारतीय संघ की स्थापना का प्रावधान किया?",
          "option_a": "Government of India Act 1909",
          "option_b": "Government of India Act 1919",
          "option_c": "Government of India Act 1935",
          "option_d": "Indian Independence Act 1947",
          "option_a_hi": "भारत सरकार अधिनियम 1909",
          "option_b_hi": "भारत सरकार अधिनियम 1919",
          "option_c_hi": "भारत सरकार अधिनियम 1935",
          "option_d_hi": "भारतीय स्वतंत्रता अधिनियम 1947",
          "correct_option": 3,
          "explanation": "The GoI Act 1935 replaced dyarchy in provinces with provincial autonomy.",
          "explanation_hi": "भारत सरकार अधिनियम 1935 ने प्रांतों में द्वैध शासन को प्रांतीय स्वायत्तता से बदल दिया।"
        },
        {
          "question": "In the provincial elections held in 1937, the Indian National Congress formed ministries in how many provinces initially?",
          "question_hi": "1937 में हुए प्रांतीय चुनावों में, भारतीय राष्ट्रीय कांग्रेस ने शुरू में कितने प्रांतों में सरकार (मंत्रालय) बनाई थी?",
          "option_a": "5",
          "option_b": "7",
          "option_c": "9",
          "option_d": "11",
          "option_a_hi": "5",
          "option_b_hi": "7",
          "option_c_hi": "9",
          "option_d_hi": "11",
          "correct_option": 2,
          "explanation": "Congress swept the polls and formed ministries in 7 out of 11 provinces (later 8 when they formed a coalition in Assam).",
          "explanation_hi": "कांग्रेस ने चुनावों में भारी जीत हासिल की और 11 में से 7 प्रांतों में मंत्रालय बनाए (बाद में 8 जब उन्होंने असम में गठबंधन बनाया)।"
        },
        {
          "question": "Why did the Congress ministries in the provinces resign in October-November 1939?",
          "question_hi": "अक्टूबर-नवंबर 1939 में प्रांतों में कांग्रेस मंत्रालयों ने इस्तीफा क्यों दिया?",
          "option_a": "Due to corruption charges",
          "option_b": "Because the British declared India a party to World War II without consulting them",
          "option_c": "In protest against the partition of India",
          "option_d": "Because they were defeated in fresh elections",
          "option_a_hi": "भ्रष्टाचार के आरोपों के कारण",
          "option_b_hi": "क्योंकि अंग्रेजों ने उनसे परामर्श किए बिना भारत को द्वितीय विश्व युद्ध में एक पक्ष घोषित कर दिया था",
          "option_c_hi": "भारत के विभाजन के विरोध में",
          "option_d_hi": "क्योंकि वे नए चुनावों में हार गए थे",
          "correct_option": 2,
          "explanation": "Viceroy Lord Linlithgow declared India's entry into WWII without consulting the Indian legislatures, prompting the mass resignation.",
          "explanation_hi": "वायसराय लॉर्ड लिनलिथगो ने भारतीय विधानसभाओं से परामर्श किए बिना द्वितीय विश्व युद्ध में भारत के प्रवेश की घोषणा की, जिससे सामूहिक इस्तीफा हुआ।"
        },
        {
          "question": "When the Congress ministries resigned in 1939, who called upon the Muslims to observe 'Day of Deliverance'?",
          "question_hi": "जब कांग्रेस मंत्रालयों ने 1939 में इस्तीफा दिया, तो मुसलमानों को 'मुक्ति दिवस' (Day of Deliverance) मनाने का आह्वान किसने किया?",
          "option_a": "Syed Ahmad Khan",
          "option_b": "Maulana Abul Kalam Azad",
          "option_c": "Muhammad Ali Jinnah",
          "option_d": "Aga Khan",
          "option_a_hi": "सैयद अहमद खान",
          "option_b_hi": "मौलाना अबुल कलाम आजाद",
          "option_c_hi": "मुहम्मद अली जिन्ना",
          "option_d_hi": "आगा खान",
          "correct_option": 3,
          "explanation": "Jinnah and the Muslim League celebrated 22 December 1939 as the 'Day of Deliverance' from Congress rule.",
          "explanation_hi": "जिन्ना और मुस्लिम लीग ने 22 दिसंबर 1939 को कांग्रेस शासन से 'मुक्ति दिवस' के रूप में मनाया।"
        },
        {
          "question": "At which Congress session in 1938 was Subhas Chandra Bose unanimously elected as the President?",
          "question_hi": "1938 में किस कांग्रेस अधिवेशन में सुभाष चंद्र बोस को सर्वसम्मति से अध्यक्ष चुना गया था?",
          "option_a": "Haripura Session",
          "option_b": "Tripuri Session",
          "option_c": "Faizpur Session",
          "option_d": "Ramgarh Session",
          "option_a_hi": "हरिपुरा अधिवेशन",
          "option_b_hi": "त्रिपुरी अधिवेशन",
          "option_c_hi": "फैजपुर अधिवेशन",
          "option_d_hi": "रामगढ़ अधिवेशन",
          "correct_option": 1,
          "explanation": "Bose was elected unanimously at the Haripura session (Gujarat) in 1938.",
          "explanation_hi": "1938 में हरिपुरा अधिवेशन (गुजरात) में बोस को सर्वसम्मति से चुना गया था।"
        },
        {
          "question": "The famous 'Tripuri Crisis' (1939) occurred because Subhas Chandra Bose defeated Gandhi's nominated candidate for Congress Presidency. Who was that candidate?",
          "question_hi": "प्रसिद्ध 'त्रिपुरी संकट' (1939) हुआ क्योंकि सुभाष चंद्र बोस ने कांग्रेस अध्यक्ष पद के लिए गांधी के नामित उम्मीदवार को हरा दिया था। वह उम्मीदवार कौन था?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Pattabhi Sitaramayya",
          "option_c": "Maulana Abul Kalam Azad",
          "option_d": "Rajendra Prasad",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "पट्टाभि सीतारमैय्या",
          "option_c_hi": "मौलाना अबुल कलाम आजाद",
          "option_d_hi": "राजेंद्र प्रसाद",
          "correct_option": 2,
          "explanation": "Bose defeated Pattabhi Sitaramayya, a victory Gandhi saw as his own personal defeat.",
          "explanation_hi": "बोस ने पट्टाभि सीतारमैय्या को हराया, एक ऐसी जीत जिसे गांधी ने अपनी व्यक्तिगत हार के रूप में देखा।"
        },
        {
          "question": "After resigning from the Congress Presidency in 1939 due to ideological differences with Gandhi, what new party did Subhas Chandra Bose form within the Congress?",
          "question_hi": "गांधी के साथ वैचारिक मतभेदों के कारण 1939 में कांग्रेस अध्यक्ष पद से इस्तीफा देने के बाद, सुभाष चंद्र बोस ने कांग्रेस के भीतर कौन सी नई पार्टी बनाई?",
          "option_a": "Swaraj Party",
          "option_b": "Forward Bloc",
          "option_c": "Congress Socialist Party",
          "option_d": "Kirti Kisan Party",
          "option_a_hi": "स्वराज पार्टी",
          "option_b_hi": "फॉरवर्ड ब्लॉक",
          "option_c_hi": "कांग्रेस सोशलिस्ट पार्टी",
          "option_d_hi": "कीर्ति किसान पार्टी",
          "correct_option": 2,
          "explanation": "Bose formed the Forward Bloc in May 1939 to consolidate left-wing and radical elements.",
          "explanation_hi": "बोस ने वामपंथी और कट्टरपंथी तत्वों को मजबूत करने के लिए मई 1939 में फॉरवर्ड ब्लॉक का गठन किया।"
        },
        {
          "question": "Who took over as the Congress President after Subhas Chandra Bose resigned in 1939?",
          "question_hi": "1939 में सुभाष चंद्र बोस के इस्तीफे के बाद कांग्रेस अध्यक्ष का पद किसने संभाला?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Rajendra Prasad",
          "option_c": "Pattabhi Sitaramayya",
          "option_d": "Sardar Vallabhbhai Patel",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "राजेंद्र प्रसाद",
          "option_c_hi": "पट्टाभि सीतारमैय्या",
          "option_d_hi": "सरदार वल्लभभाई पटेल",
          "correct_option": 2,
          "explanation": "Dr. Rajendra Prasad was appointed as the President to finish the term.",
          "explanation_hi": "डॉ. राजेंद्र प्रसाद को कार्यकाल पूरा करने के लिए अध्यक्ष नियुक्त किया गया था।"
        },
        {
          "question": "The National Planning Committee (1938) was set up under the chairmanship of:",
          "question_hi": "राष्ट्रीय योजना समिति (1938) की स्थापना किसकी अध्यक्षता में की गई थी?",
          "option_a": "Subhas Chandra Bose",
          "option_b": "Jawaharlal Nehru",
          "option_c": "M. Visvesvaraya",
          "option_d": "Mahatma Gandhi",
          "option_a_hi": "सुभाष चंद्र बोस",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "एम. विश्वेश्वरैया",
          "option_d_hi": "महात्मा गांधी",
          "correct_option": 2,
          "explanation": "It was set up by Congress President Subhas Chandra Bose, but he appointed Jawaharlal Nehru as its Chairman.",
          "explanation_hi": "इसकी स्थापना कांग्रेस अध्यक्ष सुभाष चंद्र बोस ने की थी, लेकिन उन्होंने जवाहरलाल नेहरू को इसका अध्यक्ष नियुक्त किया।"
        },
        {
          "question": "The historic 'Lahore Resolution' demanding an independent state for Muslims was passed by the Muslim League in:",
          "question_hi": "मुसलमानों के लिए एक स्वतंत्र राज्य की मांग करने वाला ऐतिहासिक 'लाहौर प्रस्ताव' (Lahore Resolution) मुस्लिम लीग द्वारा कब पारित किया गया था?",
          "option_a": "1930",
          "option_b": "1935",
          "option_c": "1940",
          "option_d": "1946",
          "option_a_hi": "1930",
          "option_b_hi": "1935",
          "option_c_hi": "1940",
          "option_d_hi": "1946",
          "correct_option": 3,
          "explanation": "On March 23, 1940, the Muslim League passed the Lahore Resolution (Pakistan Resolution), formally demanding independent states for Muslims.",
          "explanation_hi": "23 मार्च, 1940 को मुस्लिम लीग ने लाहौर प्रस्ताव (पाकिस्तान प्रस्ताव) पारित किया, जिसमें औपचारिक रूप से मुसलमानों के लिए स्वतंत्र राज्यों की मांग की गई थी।"
        }
      ]
    }
  },
  {
    fileName: "qim_ina_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1031,
        "title": "Quit India Movement & INA",
        "title_hi": "भारत छोड़ो आंदोलन और INA",
        "description": "August Offer, Quit India Movement, and Subhas Chandra Bose.",
        "description_hi": "अगस्त प्रस्ताव, भारत छोड़ो आंदोलन, और सुभाष चंद्र बोस।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The 'August Offer' (1940), proposing Dominion status and expansion of the Viceroy's executive council, was made by Viceroy:",
          "question_hi": "'अगस्त प्रस्ताव' (1940), जिसमें डोमिनियन स्टेटस और वायसराय की कार्यकारी परिषद के विस्तार का प्रस्ताव था, किस वायसराय द्वारा दिया गया था?",
          "option_a": "Lord Wavell",
          "option_b": "Lord Linlithgow",
          "option_c": "Lord Mountbatten",
          "option_d": "Lord Irwin",
          "option_a_hi": "लॉर्ड वेवेल",
          "option_b_hi": "लॉर्ड लिनलिथगो",
          "option_c_hi": "लॉर्ड माउंटबेटन",
          "option_d_hi": "लॉर्ड इरविन",
          "correct_option": 2,
          "explanation": "Lord Linlithgow made the August Offer to gain Indian cooperation during World War II.",
          "explanation_hi": "लॉर्ड लिनलिथगो ने द्वितीय विश्व युद्ध के दौरान भारतीय सहयोग प्राप्त करने के लिए अगस्त प्रस्ताव दिया था।"
        },
        {
          "question": "Who was chosen by Mahatma Gandhi as the first satyagrahi for the Individual Satyagraha (1940)?",
          "question_hi": "व्यक्तिगत सत्याग्रह (1940) के लिए महात्मा गांधी द्वारा प्रथम सत्याग्रही के रूप में किसे चुना गया था?",
          "option_a": "Jawaharlal Nehru",
          "option_b": "Sardar Patel",
          "option_c": "Vinoba Bhave",
          "option_d": "Brahma Datt",
          "option_a_hi": "जवाहरलाल नेहरू",
          "option_b_hi": "सरदार पटेल",
          "option_c_hi": "विनोबा भावे",
          "option_d_hi": "ब्रह्म दत्त",
          "correct_option": 3,
          "explanation": "Vinoba Bhave was the first, followed by Jawaharlal Nehru as the second satyagrahi.",
          "explanation_hi": "विनोबा भावे पहले थे, उनके बाद जवाहरलाल नेहरू दूसरे सत्याग्रही थे।"
        },
        {
          "question": "The Cripps Mission visited India in which year with proposals to frame a new constitution after WWII?",
          "question_hi": "क्रिप्स मिशन किस वर्ष द्वितीय विश्व युद्ध के बाद एक नया संविधान बनाने के प्रस्तावों के साथ भारत आया था?",
          "option_a": "1940",
          "option_b": "1941",
          "option_c": "1942",
          "option_d": "1946",
          "option_a_hi": "1940",
          "option_b_hi": "1941",
          "option_c_hi": "1942",
          "option_d_hi": "1946",
          "correct_option": 3,
          "explanation": "Sir Stafford Cripps came to India in March 1942. Gandhi famously called its proposals 'a post-dated cheque on a crashing bank'.",
          "explanation_hi": "सर स्टैफ़ोर्ड क्रिप्स मार्च 1942 में भारत आए। गांधीजी ने इसके प्रस्तावों को प्रसिद्ध रूप से 'डूबते हुए बैंक का उत्तर-दिनांकित चेक' (post-dated cheque) कहा था।"
        },
        {
          "question": "On August 8, 1942, the historic 'Quit India' resolution was passed by the All India Congress Committee at:",
          "question_hi": "8 अगस्त, 1942 को अखिल भारतीय कांग्रेस कमेटी द्वारा ऐतिहासिक 'भारत छोड़ो' प्रस्ताव कहाँ पारित किया गया था?",
          "option_a": "Calcutta",
          "option_b": "Gowalia Tank Maidan, Bombay",
          "option_c": "Lahore",
          "option_d": "Delhi",
          "option_a_hi": "कलकत्ता",
          "option_b_hi": "गोवालिया टैंक मैदान, बॉम्बे",
          "option_c_hi": "लाहौर",
          "option_d_hi": "दिल्ली",
          "correct_option": 2,
          "explanation": "Also known as the August Kranti Maidan in Bombay.",
          "explanation_hi": "इसे बॉम्बे में अगस्त क्रांति मैदान के नाम से भी जाना जाता है।"
        },
        {
          "question": "During the Quit India Movement, Gandhi gave the famous slogan:",
          "question_hi": "भारत छोड़ो आंदोलन के दौरान, गांधीजी ने कौन सा प्रसिद्ध नारा दिया था?",
          "option_a": "Swaraj is my birthright",
          "option_b": "Jai Hind",
          "option_c": "Do or Die",
          "option_d": "Inquilab Zindabad",
          "option_a_hi": "स्वराज मेरा जन्मसिद्ध अधिकार है",
          "option_b_hi": "जय हिंद",
          "option_c_hi": "करो या मरो (Do or Die)",
          "option_d_hi": "इंकलाब जिंदाबाद",
          "correct_option": 3,
          "explanation": "He declared, 'We shall either free India or die in the attempt; we shall not live to see the perpetuation of our slavery.'",
          "explanation_hi": "उन्होंने घोषणा की, 'हम या तो भारत को स्वतंत्र कराएंगे या इस प्रयास में मर जाएंगे; हम अपनी गुलामी को हमेशा कायम देखने के लिए जीवित नहीं रहेंगे।'"
        },
        {
          "question": "Who ran a secret underground radio station called 'Congress Radio' during the Quit India Movement?",
          "question_hi": "भारत छोड़ो आंदोलन के दौरान 'कांग्रेस रेडियो' नामक एक गुप्त भूमिगत रेडियो स्टेशन किसने चलाया था?",
          "option_a": "Aruna Asaf Ali",
          "option_b": "Sucheta Kripalani",
          "option_c": "Usha Mehta",
          "option_d": "Bhikaji Cama",
          "option_a_hi": "अरुणा आसफ अली",
          "option_b_hi": "सुचेता कृपलानी",
          "option_c_hi": "उषा मेहता",
          "option_d_hi": "भीकाजी कामा",
          "correct_option": 3,
          "explanation": "Usha Mehta operated a secret Congress Radio from Bombay to broadcast messages during the movement.",
          "explanation_hi": "उषा मेहता ने आंदोलन के दौरान संदेश प्रसारित करने के लिए बॉम्बे से एक गुप्त कांग्रेस रेडियो का संचालन किया।"
        },
        {
          "question": "During the Quit India movement, parallel governments were established in various parts of India. The one in Ballia (UP) was led by:",
          "question_hi": "भारत छोड़ो आंदोलन के दौरान, भारत के विभिन्न हिस्सों में समानांतर सरकारें स्थापित की गईं। बलिया (यूपी) में इसका नेतृत्व किसने किया था?",
          "option_a": "Nana Patil",
          "option_b": "Chittu Pandey",
          "option_c": "Matangini Hazra",
          "option_d": "Jayaprakash Narayan",
          "option_a_hi": "नाना पाटिल",
          "option_b_hi": "चित्तू पांडेय",
          "option_c_hi": "मातंगिनी हाजरा",
          "option_d_hi": "जयप्रकाश नारायण",
          "correct_option": 2,
          "explanation": "Chittu Pandey formed the first parallel government (Jatiya Sarkar) in Ballia for a few days.",
          "explanation_hi": "चित्तू पांडेय ने कुछ दिनों के लिए बलिया में पहली समानांतर सरकार (जातीय सरकार) बनाई थी।"
        },
        {
          "question": "Which political organization formally opposed the Quit India Movement?",
          "question_hi": "किस राजनीतिक संगठन ने औपचारिक रूप से भारत छोड़ो आंदोलन का विरोध किया था?",
          "option_a": "Communist Party of India (CPI)",
          "option_b": "Muslim League",
          "option_c": "Hindu Mahasabha",
          "option_d": "All of the above",
          "option_a_hi": "भारतीय कम्युनिस्ट पार्टी (CPI)",
          "option_b_hi": "मुस्लिम लीग",
          "option_c_hi": "हिंदू महासभा",
          "option_d_hi": "उपर्युक्त सभी",
          "correct_option": 4,
          "explanation": "The Muslim League, Hindu Mahasabha, and the CPI (which supported the British war effort after USSR was attacked) opposed the movement.",
          "explanation_hi": "मुस्लिम लीग, हिंदू महासभा और सीपीआई (जिसने यूएसएसआर पर हमले के बाद ब्रिटिश युद्ध के प्रयास का समर्थन किया) ने आंदोलन का विरोध किया।"
        },
        {
          "question": "The idea of the Indian National Army (INA) was originally conceived by:",
          "question_hi": "भारतीय राष्ट्रीय सेना (INA) का विचार मूल रूप से किसके द्वारा कल्पना की गई थी?",
          "option_a": "Subhas Chandra Bose",
          "option_b": "Captain Mohan Singh",
          "option_c": "Rash Behari Bose",
          "option_d": "Shah Nawaz Khan",
          "option_a_hi": "सुभाष चंद्र बोस",
          "option_b_hi": "कैप्टन मोहन सिंह",
          "option_c_hi": "रास बिहारी बोस",
          "option_d_hi": "शाह नवाज खान",
          "correct_option": 2,
          "explanation": "Captain Mohan Singh, an officer in the British Indian Army captured by Japan, first conceived the idea of raising an army from Indian POWs.",
          "explanation_hi": "जापान द्वारा पकड़े गए ब्रिटिश भारतीय सेना के एक अधिकारी कैप्टन मोहन सिंह ने सबसे पहले भारतीय युद्धबंदियों (POWs) से एक सेना बनाने का विचार किया था।"
        },
        {
          "question": "Subhas Chandra Bose gave the famous slogan \"Give me blood, and I shall give you freedom\" in:",
          "question_hi": "सुभाष चंद्र बोस ने प्रसिद्ध नारा \"तुम मुझे खून दो, मैं तुम्हें आजादी दूंगा\" कहाँ दिया था?",
          "option_a": "Berlin",
          "option_b": "Tokyo",
          "option_c": "Burma (Myanmar)",
          "option_d": "Singapore",
          "option_a_hi": "बर्लिन",
          "option_b_hi": "टोक्यो",
          "option_c_hi": "बर्मा (म्यांमार)",
          "option_d_hi": "सिंगापुर",
          "correct_option": 3,
          "explanation": "He delivered this rousing speech in Burma to the INA soldiers.",
          "explanation_hi": "उन्होंने बर्मा में आईएनए के सैनिकों को यह जोशीला भाषण दिया था।"
        },
        {
          "question": "What was the name of the women's regiment of the Indian National Army (INA)?",
          "question_hi": "भारतीय राष्ट्रीय सेना (INA) की महिला रेजिमेंट का क्या नाम था?",
          "option_a": "Sarojini Naidu Regiment",
          "option_b": "Ahilya Bai Regiment",
          "option_c": "Rani of Jhansi Regiment",
          "option_d": "Bhikaji Cama Regiment",
          "option_a_hi": "सरोजिनी नायडू रेजिमेंट",
          "option_b_hi": "अहिल्या बाई रेजिमेंट",
          "option_c_hi": "झांसी की रानी रेजिमेंट",
          "option_d_hi": "भीकाजी कामा रेजिमेंट",
          "correct_option": 3,
          "explanation": "It was led by Captain Lakshmi Sahgal (Swaminathan).",
          "explanation_hi": "इसका नेतृत्व कैप्टन लक्ष्मी सहगल (स्वामीनाथन) ने किया था।"
        },
        {
          "question": "The famous INA trials (1945-46) took place at:",
          "question_hi": "प्रसिद्ध आईएनए परीक्षण (मुकदमे) (1945-46) कहाँ हुए थे?",
          "option_a": "Victoria Memorial, Calcutta",
          "option_b": "Red Fort, Delhi",
          "option_c": "Parliament House, Delhi",
          "option_d": "Lahore Fort",
          "option_a_hi": "विक्टोरिया मेमोरियल, कलकत्ता",
          "option_b_hi": "लाल किला, दिल्ली",
          "option_c_hi": "संसद भवन, दिल्ली",
          "option_d_hi": "लाहौर का किला",
          "correct_option": 2,
          "explanation": "Three INA officers — P.K. Sehgal, Shah Nawaz Khan, and Gurbaksh Singh Dhillon — were famously tried at the Red Fort.",
          "explanation_hi": "तीन आईएनए अधिकारियों - पी.के. सहगल, शाह नवाज खान, और गुरबख्श सिंह ढिल्लों - पर लाल किले में मुकदमा चलाया गया था।"
        },
        {
          "question": "Who among the following was a prominent lawyer who defended the INA prisoners at the Red Fort trials?",
          "question_hi": "निम्नलिखित में से कौन एक प्रमुख वकील था जिसने लाल किले के मुकदमों में INA कैदियों का बचाव किया था?",
          "option_a": "Bhulabhai Desai",
          "option_b": "C.R. Das",
          "option_c": "Motilal Nehru",
          "option_d": "B.R. Ambedkar",
          "option_a_hi": "भूलाभाई देसाई",
          "option_b_hi": "सी.आर. दास",
          "option_c_hi": "मोतीलाल नेहरू",
          "option_d_hi": "बी.आर. अम्बेडकर",
          "correct_option": 1,
          "explanation": "The defense team was led by Bhulabhai Desai and included Tej Bahadur Sapru, K.N. Katju, Asaf Ali, and Jawaharlal Nehru.",
          "explanation_hi": "बचाव दल का नेतृत्व भूलाभाई देसाई ने किया और इसमें तेज बहादुर सप्रू, के.एन. काटजू, आसफ अली और जवाहरलाल नेहरू शामिल थे।"
        },
        {
          "question": "The Royal Indian Navy (RIN) Mutiny, a massive strike by Indian sailors, broke out in February 1946 in which city?",
          "question_hi": "फरवरी 1946 में भारतीय नाविकों द्वारा की गई भारी हड़ताल, रॉयल इंडियन नेवी (RIN) विद्रोह, किस शहर में शुरू हुआ?",
          "option_a": "Madras",
          "option_b": "Karachi",
          "option_c": "Bombay",
          "option_d": "Calcutta",
          "option_a_hi": "मद्रास",
          "option_b_hi": "कराची",
          "option_c_hi": "बॉम्बे",
          "option_d_hi": "कलकत्ता",
          "correct_option": 3,
          "explanation": "The mutiny started on the ship HMIS Talwar in Bombay over poor food and racial discrimination, and quickly spread.",
          "explanation_hi": "विद्रोह बॉम्बे में HMIS तलवार जहाज पर खराब भोजन और नस्लीय भेदभाव को लेकर शुरू हुआ, और जल्दी ही फैल गया।"
        },
        {
          "question": "Which Indian leader convinced the naval ratings (sailors) to surrender during the RIN Mutiny in 1946?",
          "question_hi": "1946 में RIN विद्रोह के दौरान किस भारतीय नेता ने नौसैनिकों को आत्मसमर्पण करने के लिए राजी किया था?",
          "option_a": "Mahatma Gandhi",
          "option_b": "Jawaharlal Nehru",
          "option_c": "Sardar Vallabhbhai Patel",
          "option_d": "Subhas Chandra Bose",
          "option_a_hi": "महात्मा गांधी",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "सरदार वल्लभभाई पटेल",
          "option_d_hi": "सुभाष चंद्र बोस",
          "correct_option": 3,
          "explanation": "Sardar Patel, along with Jinnah, persuaded the sailors to surrender to prevent massive bloodshed by the British.",
          "explanation_hi": "सरदार पटेल ने जिन्ना के साथ मिलकर नाविकों को अंग्रेजों द्वारा बड़े पैमाने पर खून-खराबे को रोकने के लिए आत्मसमर्पण करने के लिए राजी किया।"
        }
      ]
    }
  },
  {
    fileName: "partition_independence_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1032,
        "title": "Partition & Independence",
        "title_hi": "विभाजन और स्वतंत्रता",
        "description": "Cabinet Mission, Direct Action Day, and Independence Act.",
        "description_hi": "कैबिनेट मिशन, डायरेक्ट एक्शन डे, और स्वतंत्रता अधिनियम।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "Who authored the 'C.R. Formula' (1944) aimed at solving the political deadlock between the Congress and the Muslim League?",
          "question_hi": "कांग्रेस और मुस्लिम लीग के बीच राजनीतिक गतिरोध को दूर करने के उद्देश्य से 'सी.आर. फॉर्मूला' (1944) किसने लिखा था?",
          "option_a": "Chittaranjan Das",
          "option_b": "C. Rajagopalachari",
          "option_c": "Chandrashekhar Azad",
          "option_d": "C.F. Andrews",
          "option_a_hi": "चित्तरंजन दास",
          "option_b_hi": "सी. राजगोपालाचारी",
          "option_c_hi": "चंद्रशेखर आज़ाद",
          "option_d_hi": "सी.एफ. एंड्रयूज",
          "correct_option": 2,
          "explanation": "Chakravarti Rajagopalachari proposed a plan for Muslim-majority areas to decide via plebiscite on forming a separate sovereign state after independence.",
          "explanation_hi": "चक्रवर्ती राजगोपालाचारी ने मुस्लिम बहुल क्षेत्रों के लिए स्वतंत्रता के बाद एक अलग संप्रभु राज्य बनाने पर जनमत संग्रह के माध्यम से निर्णय लेने की योजना का प्रस्ताव रखा।"
        },
        {
          "question": "The Shimla Conference (1945) was convened by which British Viceroy to discuss the Wavell Plan?",
          "question_hi": "शिमला सम्मेलन (1945) वेवेल योजना पर चर्चा करने के लिए किस ब्रिटिश वायसराय द्वारा बुलाया गया था?",
          "option_a": "Lord Linlithgow",
          "option_b": "Lord Wavell",
          "option_c": "Lord Mountbatten",
          "option_d": "Lord Irwin",
          "option_a_hi": "लॉर्ड लिनलिथगो",
          "option_b_hi": "लॉर्ड वेवेल",
          "option_c_hi": "लॉर्ड माउंटबेटन",
          "option_d_hi": "लॉर्ड इरविन",
          "correct_option": 2,
          "explanation": "Lord Wavell convened the conference, but it failed because Jinnah insisted that only the Muslim League could nominate Muslim members to the executive council.",
          "explanation_hi": "लॉर्ड वेवेल ने सम्मेलन बुलाया, लेकिन यह विफल रहा क्योंकि जिन्ना ने जोर देकर कहा कि केवल मुस्लिम लीग ही कार्यकारी परिषद में मुस्लिम सदस्यों को नामित कर सकती है।"
        },
        {
          "question": "The Cabinet Mission (1946) sent to India consisted of three members. Who among the following was NOT a member?",
          "question_hi": "भारत भेजे गए कैबिनेट मिशन (1946) में तीन सदस्य शामिल थे। निम्नलिखित में से कौन उसका सदस्य नहीं था?",
          "option_a": "Lord Pethick-Lawrence",
          "option_b": "Sir Stafford Cripps",
          "option_c": "A.V. Alexander",
          "option_d": "Lord Mountbatten",
          "option_a_hi": "लॉर्ड पैथिक-लॉरेंस",
          "option_b_hi": "सर स्टैफ़ोर्ड क्रिप्स",
          "option_c_hi": "ए.वी. अलेक्जेंडर",
          "option_d_hi": "लॉर्ड माउंटबेटन",
          "correct_option": 4,
          "explanation": "The three members were Pethick-Lawrence, Cripps, and A.V. Alexander.",
          "explanation_hi": "तीन सदस्य पैथिक-लॉरेंस, क्रिप्स और ए.वी. अलेक्जेंडर थे।"
        },
        {
          "question": "What was the core recommendation of the Cabinet Mission Plan (1946) regarding the partition of India?",
          "question_hi": "भारत के विभाजन के संबंध में कैबिनेट मिशन योजना (1946) की मुख्य सिफारिश क्या थी?",
          "option_a": "It strongly recommended the creation of Pakistan.",
          "option_b": "It rejected the idea of a separate Pakistan and proposed a united India with a weak center.",
          "option_c": "It proposed dividing India into three independent nations.",
          "option_d": "It suggested holding a referendum across India.",
          "option_a_hi": "इसने मजबूती से पाकिस्तान के निर्माण की सिफारिश की।",
          "option_b_hi": "इसने एक अलग पाकिस्तान के विचार को खारिज कर दिया और एक कमजोर केंद्र के साथ एकजुट भारत का प्रस्ताव रखा।",
          "option_c_hi": "इसने भारत को तीन स्वतंत्र देशों में विभाजित करने का प्रस्ताव रखा।",
          "option_d_hi": "इसने पूरे भारत में जनमत संग्रह कराने का सुझाव दिया।",
          "correct_option": 2,
          "explanation": "The Cabinet Mission explicitly rejected Pakistan but proposed grouping of provinces into three sections with significant provincial autonomy.",
          "explanation_hi": "कैबिनेट मिशन ने स्पष्ट रूप से पाकिस्तान को खारिज कर दिया, लेकिन महत्वपूर्ण प्रांतीय स्वायत्तता के साथ प्रांतों को तीन वर्गों में समूहित करने का प्रस्ताव रखा।"
        },
        {
          "question": "When the Muslim League rejected the Cabinet Mission Plan, Jinnah called for 'Direct Action Day' on:",
          "question_hi": "जब मुस्लिम लीग ने कैबिनेट मिशन योजना को खारिज कर दिया, तो जिन्ना ने 'डायरेक्ट एक्शन डे' (सीधी कार्रवाई दिवस) का आह्वान कब किया?",
          "option_a": "August 16, 1946",
          "option_b": "March 23, 1940",
          "option_c": "August 14, 1947",
          "option_d": "September 2, 1946",
          "option_a_hi": "16 अगस्त, 1946",
          "option_b_hi": "23 मार्च, 1940",
          "option_c_hi": "14 अगस्त, 1947",
          "option_d_hi": "2 सितंबर, 1946",
          "correct_option": 1,
          "explanation": "August 16, 1946, was observed as Direct Action Day, triggering massive communal riots, famously known as the Great Calcutta Killings.",
          "explanation_hi": "16 अगस्त, 1946 को डायरेक्ट एक्शन डे के रूप में मनाया गया, जिससे बड़े पैमाने पर सांप्रदायिक दंगे हुए, जिन्हें प्रसिद्ध रूप से ग्रेट कलकत्ता किलिंग्स (Great Calcutta Killings) के रूप में जाना जाता है।"
        },
        {
          "question": "Who headed the Interim Government formed in September 1946?",
          "question_hi": "सितंबर 1946 में बनी अंतरिम सरकार (Interim Government) का नेतृत्व किसने किया था?",
          "option_a": "Mahatma Gandhi",
          "option_b": "Sardar Vallabhbhai Patel",
          "option_c": "Jawaharlal Nehru",
          "option_d": "Lord Mountbatten",
          "option_a_hi": "महात्मा गांधी",
          "option_b_hi": "सरदार वल्लभभाई पटेल",
          "option_c_hi": "जवाहरलाल नेहरू",
          "option_d_hi": "लॉर्ड माउंटबेटन",
          "correct_option": 3,
          "explanation": "Jawaharlal Nehru served as the Vice-President of the Viceroy's Executive Council, effectively acting as the Prime Minister of the Interim Government.",
          "explanation_hi": "जवाहरलाल नेहरू ने वायसराय की कार्यकारी परिषद के उपाध्यक्ष के रूप में कार्य किया, प्रभावी रूप से अंतरिम सरकार के प्रधान मंत्री के रूप में कार्य किया।"
        },
        {
          "question": "Which British Prime Minister declared in February 1947 that the British would quit India by June 1948?",
          "question_hi": "किस ब्रिटिश प्रधान मंत्री ने फरवरी 1947 में घोषणा की थी कि अंग्रेज जून 1948 तक भारत छोड़ देंगे?",
          "option_a": "Winston Churchill",
          "option_b": "Clement Attlee",
          "option_c": "Ramsay MacDonald",
          "option_d": "Neville Chamberlain",
          "option_a_hi": "विंस्टन चर्चिल",
          "option_b_hi": "क्लेमेंट एटली",
          "option_c_hi": "रामसे मैकडोनाल्ड",
          "option_d_hi": "नेविल चेम्बरलेन",
          "correct_option": 2,
          "explanation": "Clement Attlee (Labour Party) made this historic announcement.",
          "explanation_hi": "क्लेमेंट एटली (लेबर पार्टी) ने यह ऐतिहासिक घोषणा की थी।"
        },
        {
          "question": "The plan to partition India into two independent dominions (India and Pakistan) is known as:",
          "question_hi": "भारत को दो स्वतंत्र डोमिनियन (भारत और पाकिस्तान) में विभाजित करने की योजना को किस नाम से जाना जाता है?",
          "option_a": "Wavell Plan",
          "option_b": "Mountbatten Plan (June 3 Plan)",
          "option_c": "Cabinet Mission Plan",
          "option_d": "Radcliffe Plan",
          "option_a_hi": "वेवेल योजना",
          "option_b_hi": "माउंटबेटन योजना (3 जून योजना)",
          "option_c_hi": "कैबिनेट मिशन योजना",
          "option_d_hi": "रैडक्लिफ योजना",
          "correct_option": 2,
          "explanation": "Lord Mountbatten announced the 'June 3 Plan' which was accepted by both Congress and Muslim League, leading to partition.",
          "explanation_hi": "लॉर्ड माउंटबेटन ने '3 जून योजना' की घोषणा की जिसे कांग्रेस और मुस्लिम लीग दोनों ने स्वीकार कर लिया, जिससे विभाजन हुआ।"
        },
        {
          "question": "Who was appointed to chair the boundary commissions to demarcate the borders of India and Pakistan?",
          "question_hi": "भारत और पाकिस्तान की सीमाओं का सीमांकन करने के लिए सीमा आयोगों (boundary commissions) की अध्यक्षता करने के लिए किसे नियुक्त किया गया था?",
          "option_a": "Lord Mountbatten",
          "option_b": "Sir Cyril Radcliffe",
          "option_c": "Sir Stafford Cripps",
          "option_d": "A.V. Alexander",
          "option_a_hi": "लॉर्ड माउंटबेटन",
          "option_b_hi": "सर सिरिल रैडक्लिफ",
          "option_c_hi": "सर स्टैफ़ोर्ड क्रिप्स",
          "option_d_hi": "ए.वी. अलेक्जेंडर",
          "correct_option": 2,
          "explanation": "Sir Cyril Radcliffe drew the borders of the two new nations (the Radcliffe Line).",
          "explanation_hi": "सर सिरिल रैडक्लिफ ने दो नए राष्ट्रों (रैडक्लिफ रेखा) की सीमाएँ खींचीं।"
        },
        {
          "question": "Who was the first Governor-General of independent India?",
          "question_hi": "स्वतंत्र भारत के प्रथम गवर्नर जनरल कौन थे?",
          "option_a": "C. Rajagopalachari",
          "option_b": "Jawaharlal Nehru",
          "option_c": "Lord Mountbatten",
          "option_d": "Dr. Rajendra Prasad",
          "option_a_hi": "सी. राजगोपालाचारी",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "लॉर्ड माउंटबेटन",
          "option_d_hi": "डॉ. राजेंद्र प्रसाद",
          "correct_option": 3,
          "explanation": "Lord Mountbatten stayed on as the first Governor-General of independent India, while Jinnah became the first Governor-General of Pakistan.",
          "explanation_hi": "लॉर्ड माउंटबेटन स्वतंत्र भारत के पहले गवर्नर-जनरल बने रहे, जबकि जिन्ना पाकिस्तान के पहले गवर्नर-जनरल बने।"
        }
      ]
    }
  }
];

async function insertAll() {
  for (const q of quizzes) {
    fs.writeFileSync(q.fileName, JSON.stringify(q.data, null, 2));
  }
}
insertAll();
