const fs = require('fs');

const quizzes = [
  {
    fileName: "extremist_trio_surat_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1024,
        "title": "Rise of Extremism & Surat Split (1907)",
        "title_hi": "उग्रवाद का उदय और सूरत विभाजन (1907)",
        "description": "Extremist phase and the Surat Split.",
        "description_hi": "उग्रवादी चरण और सूरत विभाजन।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "Who among the following was known as the 'Father of Indian Unrest' by the British?",
          "question_hi": "निम्नलिखित में से किसे अंग्रेजों द्वारा 'भारतीय अशांति का जनक' (Father of Indian Unrest) कहा गया था?",
          "option_a": "Lala Lajpat Rai",
          "option_b": "Bipin Chandra Pal",
          "option_c": "Bal Gangadhar Tilak",
          "option_d": "Aurobindo Ghosh",
          "option_a_hi": "लाला लाजपत राय",
          "option_b_hi": "बिपिन चंद्र पाल",
          "option_c_hi": "बाल गंगाधर तिलक",
          "option_d_hi": "अरबिंदो घोष",
          "correct_option": 3,
          "explanation": "Valentine Chirol described Bal Gangadhar Tilak as the 'Father of Indian Unrest'.",
          "explanation_hi": "वैलेंटाइन चिरोल ने बाल गंगाधर तिलक को 'भारतीय अशांति का जनक' बताया था।"
        },
        {
          "question": "Which of the following festivals was popularized by Bal Gangadhar Tilak to stimulate nationalism among the masses?",
          "question_hi": "जनता के बीच राष्ट्रवाद को जगाने के लिए बाल गंगाधर तिलक द्वारा निम्नलिखित में से कौन सा त्योहार लोकप्रिय बनाया गया था?",
          "option_a": "Ganesh Chaturthi and Shivaji Utsav",
          "option_b": "Durga Puja and Kali Puja",
          "option_c": "Kumbh Mela and Makar Sankranti",
          "option_d": "Dussehra and Diwali",
          "option_a_hi": "गणेश चतुर्थी और शिवाजी उत्सव",
          "option_b_hi": "दुर्गा पूजा और काली पूजा",
          "option_c_hi": "कुंभ मेला और मकर संक्रांति",
          "option_d_hi": "दशहरा और दीवाली",
          "correct_option": 1,
          "explanation": "Tilak used Ganesh Chaturthi (1893) and Shivaji Utsav (1895) to propagate nationalist ideas.",
          "explanation_hi": "तिलक ने राष्ट्रवादी विचारों का प्रचार करने के लिए गणेश चतुर्थी (1893) और शिवाजी उत्सव (1895) का उपयोग किया।"
        },
        {
          "question": "The historical split in the Indian National Congress between Moderates and Extremists took place in the year:",
          "question_hi": "भारतीय राष्ट्रीय कांग्रेस में नरमपंथियों और चरमपंथियों के बीच ऐतिहासिक विभाजन किस वर्ष हुआ था?",
          "option_a": "1905",
          "option_b": "1906",
          "option_c": "1907",
          "option_d": "1908",
          "option_a_hi": "1905",
          "option_b_hi": "1906",
          "option_c_hi": "1907",
          "option_d_hi": "1908",
          "correct_option": 3,
          "explanation": "The split occurred at the Surat session of the INC in 1907.",
          "explanation_hi": "विभाजन 1907 में INC के सूरत अधिवेशन में हुआ था।"
        },
        {
          "question": "Who presided over the Surat Session of the Indian National Congress in 1907?",
          "question_hi": "1907 में भारतीय राष्ट्रीय कांग्रेस के सूरत अधिवेशन की अध्यक्षता किसने की थी?",
          "option_a": "Dadabhai Naoroji",
          "option_b": "Rash Behari Ghosh",
          "option_c": "Lala Lajpat Rai",
          "option_d": "Gopal Krishna Gokhale",
          "option_a_hi": "दादाभाई नौरोजी",
          "option_b_hi": "रास बिहारी घोष",
          "option_c_hi": "लाला लाजपत राय",
          "option_d_hi": "गोपाल कृष्ण गोखले",
          "correct_option": 2,
          "explanation": "The Extremists wanted Lala Lajpat Rai to preside, but the Moderates successfully elected Rash Behari Ghosh, leading to the split.",
          "explanation_hi": "चरमपंथी चाहते थे कि लाला लाजपत राय अध्यक्षता करें, लेकिन नरमपंथियों ने रास बिहारी घोष को सफलतापूर्वक चुना, जिससे विभाजन हुआ।"
        },
        {
          "question": "Consider the following statements regarding the Extremist leaders:\n1. They believed in passive resistance and direct political action.\n2. They rejected the idea of complete independence (Swaraj) as their goal.\nWhich of the statements is/are correct?",
          "question_hi": "चरमपंथी नेताओं के संबंध में निम्नलिखित कथनों पर विचार करें:\n1. वे निष्क्रिय प्रतिरोध और प्रत्यक्ष राजनीतिक कार्रवाई में विश्वास करते थे।\n2. उन्होंने अपने लक्ष्य के रूप में पूर्ण स्वतंत्रता (स्वराज) के विचार को खारिज कर दिया।\nकौन सा/से कथन सही है/हैं?",
          "option_a": "1 only",
          "option_b": "2 only",
          "option_c": "Both 1 and 2",
          "option_d": "Neither 1 nor 2",
          "option_a_hi": "केवल 1",
          "option_b_hi": "केवल 2",
          "option_c_hi": "1 और 2 दोनों",
          "option_d_hi": "न तो 1 और न ही 2",
          "correct_option": 1,
          "explanation": "Statement 2 is incorrect because the Extremists firmly demanded Swaraj, unlike Moderates who wanted self-government under British rule.",
          "explanation_hi": "कथन 2 गलत है क्योंकि नरमपंथियों के विपरीत, जो ब्रिटिश शासन के तहत स्वशासन चाहते थे, चरमपंथियों ने दृढ़ता से स्वराज की मांग की।"
        },
        {
          "question": "Who famously declared, \"Swaraj is my birthright and I shall have it\"?",
          "question_hi": "किसने यह प्रसिद्ध घोषणा की थी, \"स्वराज मेरा जन्मसिद्ध अधिकार है और मैं इसे लेकर रहूंगा\"?",
          "option_a": "Bipin Chandra Pal",
          "option_b": "Aurobindo Ghosh",
          "option_c": "Bhagat Singh",
          "option_d": "Bal Gangadhar Tilak",
          "option_a_hi": "बिपिन चंद्र पाल",
          "option_b_hi": "अरबिंदो घोष",
          "option_c_hi": "भगत सिंह",
          "option_d_hi": "बाल गंगाधर तिलक",
          "correct_option": 4,
          "explanation": "This historic slogan was coined by Bal Gangadhar Tilak.",
          "explanation_hi": "यह ऐतिहासिक नारा बाल गंगाधर तिलक ने दिया था।"
        },
        {
          "question": "Which of the following newspapers were published by Bal Gangadhar Tilak?",
          "question_hi": "बाल गंगाधर तिलक द्वारा निम्नलिखित में से कौन से समाचार पत्र प्रकाशित किए गए थे?",
          "option_a": "Amrita Bazar Patrika and Jugantar",
          "option_b": "Kesari and Mahratta",
          "option_c": "Al-Hilal and Comrade",
          "option_d": "Vande Mataram and New India",
          "option_a_hi": "अमृत ​​बाजार पत्रिका और युगांतर",
          "option_b_hi": "केसरी और मराठा",
          "option_c_hi": "अल-हिलाल और कॉमरेड",
          "option_d_hi": "वंदे मातरम और न्यू इंडिया",
          "correct_option": 2,
          "explanation": "Tilak published Kesari in Marathi and Mahratta in English.",
          "explanation_hi": "तिलक ने मराठी में केसरी और अंग्रेजी में मराठा प्रकाशित किया।"
        },
        {
          "question": "The famous 'Lal-Bal-Pal' trio included Lala Lajpat Rai, Bal Gangadhar Tilak, and:",
          "question_hi": "प्रसिद्ध 'लाल-बाल-पाल' की तिकड़ी में लाला लाजपत राय, बाल गंगाधर तिलक और कौन शामिल थे?",
          "option_a": "Bipin Chandra Pal",
          "option_b": "Badruddin Tyabji",
          "option_c": "Bankim Chandra Chatterjee",
          "option_d": "Barindra Kumar Ghosh",
          "option_a_hi": "बिपिन चंद्र पाल",
          "option_b_hi": "बदरुद्दीन तैयबजी",
          "option_c_hi": "बंकिम चंद्र चटर्जी",
          "option_d_hi": "बारींद्र कुमार घोष",
          "correct_option": 1,
          "explanation": "Bipin Chandra Pal, from Bengal, was the 'Pal' in the extremist trio.",
          "explanation_hi": "बंगाल के बिपिन चंद्र पाल, उग्रवादी तिकड़ी में 'पाल' थे।"
        },
        {
          "question": "Which prominent Extremist leader retired from active politics and turned to spiritualism in Pondicherry?",
          "question_hi": "कौन सा प्रमुख चरमपंथी नेता सक्रिय राजनीति से सेवानिवृत्त हो गया और पांडिचेरी में आध्यात्मवाद की ओर मुड़ गया?",
          "option_a": "Bipin Chandra Pal",
          "option_b": "Lala Lajpat Rai",
          "option_c": "Aurobindo Ghosh",
          "option_d": "V.D. Savarkar",
          "option_a_hi": "बिपिन चंद्र पाल",
          "option_b_hi": "लाला लाजपत राय",
          "option_c_hi": "अरबिंदो घोष",
          "option_d_hi": "वी.डी. सावरकर",
          "correct_option": 3,
          "explanation": "Aurobindo Ghosh left active politics in 1910 and set up an ashram in Pondicherry.",
          "explanation_hi": "अरबिंदो घोष ने 1910 में सक्रिय राजनीति छोड़ दी और पांडिचेरी में एक आश्रम स्थापित किया।"
        },
        {
          "question": "At the 1906 Calcutta session of INC, presided over by Dadabhai Naoroji, which of the following was declared as the goal of the Congress for the first time?",
          "question_hi": "दादाभाई नौरोजी की अध्यक्षता में INC के 1906 के कलकत्ता अधिवेशन में, निम्नलिखित में से किसे पहली बार कांग्रेस का लक्ष्य घोषित किया गया था?",
          "option_a": "Purna Swaraj",
          "option_b": "Swaraj (Self-government like the UK)",
          "option_c": "Dominion Status",
          "option_d": "Abolition of Salt Tax",
          "option_a_hi": "पूर्ण स्वराज",
          "option_b_hi": "स्वराज (यूके की तरह स्वशासन)",
          "option_c_hi": "डोमिनियन स्टेटस",
          "option_d_hi": "नमक कर का उन्मूलन",
          "correct_option": 2,
          "explanation": "To avoid a split in 1906, Dadabhai Naoroji declared 'Swaraj' or self-government (like that of the UK) as the goal.",
          "explanation_hi": "1906 में विभाजन से बचने के लिए, दादाभाई नौरोजी ने 'स्वराज' या स्वशासन (यूके की तरह) को लक्ष्य घोषित किया।"
        },
        {
          "question": "In which year was Bal Gangadhar Tilak sentenced to six years of imprisonment in Mandalay (Burma) on charges of sedition?",
          "question_hi": "बाल गंगाधर तिलक को राजद्रोह के आरोप में मांडले (बर्मा) में छह साल के कारावास की सजा किस वर्ष दी गई थी?",
          "option_a": "1906",
          "option_b": "1907",
          "option_c": "1908",
          "option_d": "1914",
          "option_a_hi": "1906",
          "option_b_hi": "1907",
          "option_c_hi": "1908",
          "option_d_hi": "1914",
          "correct_option": 3,
          "explanation": "Tilak was arrested in 1908 for writing articles in Kesari defending the revolutionaries and was sent to Mandalay for six years.",
          "explanation_hi": "तिलक को 1908 में केसरी में क्रांतिकारियों का बचाव करने वाले लेख लिखने के आरोप में गिरफ्तार किया गया था और छह साल के लिए मांडले भेज दिया गया था।"
        },
        {
          "question": "The Extremists wanted to extend the Swadeshi and Boycott movement:",
          "question_hi": "चरमपंथी स्वदेशी और बहिष्कार आंदोलन का विस्तार करना चाहते थे:",
          "option_a": "Only in Bengal",
          "option_b": "Only in Punjab",
          "option_c": "To the rest of India outside Bengal",
          "option_d": "Only to the major urban centers",
          "option_a_hi": "केवल बंगाल में",
          "option_b_hi": "केवल पंजाब में",
          "option_c_hi": "बंगाल के बाहर शेष भारत में",
          "option_d_hi": "केवल प्रमुख शहरी केंद्रों में",
          "correct_option": 3,
          "explanation": "While Moderates wanted to confine it to Bengal, Extremists wanted to take it to the rest of India, which became a major reason for the Surat Split.",
          "explanation_hi": "जबकि नरमपंथी इसे बंगाल तक ही सीमित रखना चाहते थे, चरमपंथी इसे शेष भारत में ले जाना चाहते थे, जो सूरत विभाजन का एक बड़ा कारण बन गया।"
        },
        {
          "question": "Who authored the book 'Unhappy India'?",
          "question_hi": "'अनहैप्पी इंडिया' (Unhappy India) पुस्तक के लेखक कौन हैं?",
          "option_a": "Bal Gangadhar Tilak",
          "option_b": "Lala Lajpat Rai",
          "option_c": "Bipin Chandra Pal",
          "option_d": "Mahatma Gandhi",
          "option_a_hi": "बाल गंगाधर तिलक",
          "option_b_hi": "लाला लाजपत राय",
          "option_c_hi": "बिपिन चंद्र पाल",
          "option_d_hi": "महात्मा गांधी",
          "correct_option": 2,
          "explanation": "Lala Lajpat Rai wrote 'Unhappy India'.",
          "explanation_hi": "लाला लाजपत राय ने 'अनहैप्पी इंडिया' लिखी।"
        },
        {
          "question": "Who among the following was known as the 'Sher-e-Punjab' (Lion of Punjab)?",
          "question_hi": "निम्नलिखित में से किसे 'शेर-ए-पंजाब' (पंजाब का शेर) के नाम से जाना जाता था?",
          "option_a": "Bhagat Singh",
          "option_b": "Lala Lajpat Rai",
          "option_c": "Ranjit Singh",
          "option_d": "Udham Singh",
          "option_a_hi": "भगत सिंह",
          "option_b_hi": "लाला लाजपत राय",
          "option_c_hi": "रणजीत सिंह",
          "option_d_hi": "ऊधम सिंह",
          "correct_option": 2,
          "explanation": "Lala Lajpat Rai was famously known as Sher-e-Punjab.",
          "explanation_hi": "लाला लाजपत राय को शेर-ए-पंजाब के नाम से जाना जाता था।"
        },
        {
          "question": "What was the immediate outcome of the Surat Split (1907) for the Congress?",
          "question_hi": "कांग्रेस के लिए सूरत विभाजन (1907) का तात्कालिक परिणाम क्या था?",
          "option_a": "The Extremists took over the Congress.",
          "option_b": "The Moderates completely controlled the Congress and expelled the Extremists.",
          "option_c": "The Congress was banned by the British.",
          "option_d": "Muslim leaders completely boycotted the Congress.",
          "option_a_hi": "चरमपंथियों ने कांग्रेस पर कब्ज़ा कर लिया।",
          "option_b_hi": "नरमपंथियों ने कांग्रेस को पूरी तरह से नियंत्रित किया और चरमपंथियों को निष्कासित कर दिया।",
          "option_c_hi": "अंग्रेजों द्वारा कांग्रेस पर प्रतिबंध लगा दिया गया था।",
          "option_d_hi": "मुस्लिम नेताओं ने कांग्रेस का पूरी तरह से बहिष्कार किया।",
          "correct_option": 2,
          "explanation": "After the split, the Moderates remained in control of the INC and kept the Extremists out until 1916.",
          "explanation_hi": "विभाजन के बाद, नरमपंथियों का INC पर नियंत्रण बना रहा और उन्होंने 1916 तक चरमपंथियों को बाहर रखा।"
        }
      ]
    }
  },
  {
    fileName: "revolutionary_bengal_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1024,
        "title": "Revolutionary Movement in Bengal",
        "title_hi": "बंगाल में क्रांतिकारी आंदोलन",
        "description": "Revolutionary activities in Bengal phase 1.",
        "description_hi": "बंगाल में क्रांतिकारी गतिविधियां चरण 1।",
        "difficulty": "Moderate",
        "total_questions": 10,
        "time_limit_mins": 15,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "Which of the following was the first secret revolutionary society established in Bengal in 1902?",
          "question_hi": "1902 में बंगाल में स्थापित पहला गुप्त क्रांतिकारी समाज निम्नलिखित में से कौन सा था?",
          "option_a": "Anushilan Samiti",
          "option_b": "Jugantar",
          "option_c": "Mitra Mela",
          "option_d": "Abhinav Bharat",
          "option_a_hi": "अनुशीलन समिति",
          "option_b_hi": "युगांतर",
          "option_c_hi": "मित्र मेला",
          "option_d_hi": "अभिनव भारत",
          "correct_option": 1,
          "explanation": "Anushilan Samiti was founded by Pramathanath Mitra (P. Mitra) in Calcutta in 1902.",
          "explanation_hi": "अनुशीलन समिति की स्थापना प्रमथनाथ मित्रा (पी. मित्रा) ने 1902 में कलकत्ता में की थी।"
        },
        {
          "question": "Who started the revolutionary journal 'Jugantar' (Yugantar) in 1906?",
          "question_hi": "1906 में क्रांतिकारी पत्रिका 'युगांतर' (Jugantar) किसने शुरू की थी?",
          "option_a": "Barindra Kumar Ghosh and Bhupendranath Dutta",
          "option_b": "Aurobindo Ghosh and Bipin Chandra Pal",
          "option_c": "Rash Behari Bose and Sachindra Nath Sanyal",
          "option_d": "Surya Sen and Kalpana Dutt",
          "option_a_hi": "बारिन्द्र कुमार घोष और भूपेंद्रनाथ दत्त",
          "option_b_hi": "अरबिंदो घोष और बिपिन चंद्र पाल",
          "option_c_hi": "रास बिहारी बोस और शचींद्र नाथ सान्याल",
          "option_d_hi": "सूर्य सेन और कल्पना दत्त",
          "correct_option": 1,
          "explanation": "Barindra Kumar Ghosh and Bhupendranath Dutta (brother of Swami Vivekananda) started the Jugantar weekly.",
          "explanation_hi": "बारिन्द्र कुमार घोष और भूपेंद्रनाथ दत्त (स्वामी विवेकानंद के भाई) ने युगांतर साप्ताहिक शुरू किया।"
        },
        {
          "question": "The Muzaffarpur Bomb Case (1908) was an attempt to assassinate Kingsford, the unpopular judge. Who threw the bomb?",
          "question_hi": "मुजफ्फरपुर बम कांड (1908) अलोकप्रिय न्यायाधीश किंग्सफोर्ड की हत्या का एक प्रयास था। बम किसने फेंका?",
          "option_a": "Khudiram Bose and Prafulla Chaki",
          "option_b": "Bhagat Singh and Batukeshwar Dutt",
          "option_c": "Surya Sen and Ananta Singh",
          "option_d": "Rash Behari Bose and Basant Kumar Biswas",
          "option_a_hi": "खुदीराम बोस और प्रफुल्ल चाकी",
          "option_b_hi": "भगत सिंह और बटुकेश्वर दत्त",
          "option_c_hi": "सूर्य सेन और अनंत सिंह",
          "option_d_hi": "रास बिहारी बोस और बसंत कुमार विश्वास",
          "correct_option": 1,
          "explanation": "Khudiram Bose and Prafulla Chaki threw a bomb at a carriage believed to be carrying Kingsford, but mistakenly killed two British ladies.",
          "explanation_hi": "खुदीराम बोस और प्रफुल्ल चाकी ने एक गाड़ी पर बम फेंका, जिसके बारे में माना जाता था कि उसमें किंग्सफोर्ड सवार था, लेकिन गलती से दो ब्रिटिश महिलाओं की मौत हो गई।"
        },
        {
          "question": "Following the Muzaffarpur Bomb Case, which revolutionary committed suicide to avoid arrest?",
          "question_hi": "मुजफ्फरपुर बम कांड के बाद, किस क्रांतिकारी ने गिरफ्तारी से बचने के लिए आत्महत्या कर ली?",
          "option_a": "Khudiram Bose",
          "option_b": "Prafulla Chaki",
          "option_c": "Barindra Kumar Ghosh",
          "option_d": "Ullaskar Dutt",
          "option_a_hi": "खुदीराम बोस",
          "option_b_hi": "प्रफुल्ल चाकी",
          "option_c_hi": "बारिन्द्र कुमार घोष",
          "option_d_hi": "उल्लासकर दत्त",
          "correct_option": 2,
          "explanation": "Prafulla Chaki shot himself, while Khudiram Bose was arrested and hanged at the young age of 18.",
          "explanation_hi": "प्रफुल्ल चाकी ने खुद को गोली मार ली, जबकि खुदीराम बोस को गिरफ्तार कर लिया गया और 18 साल की छोटी उम्र में फांसी दे दी गई।"
        },
        {
          "question": "In the Alipore Bomb Conspiracy Case (1908), who successfully defended Aurobindo Ghosh in court?",
          "question_hi": "अलीपुर बम साजिश मामले (1908) में, अदालत में अरबिंदो घोष का सफलतापूर्वक बचाव किसने किया?",
          "option_a": "Motilal Nehru",
          "option_b": "Tej Bahadur Sapru",
          "option_c": "Chittaranjan Das (C.R. Das)",
          "option_d": "Bhulabhai Desai",
          "option_a_hi": "मोतीलाल नेहरू",
          "option_b_hi": "तेज बहादुर सप्रू",
          "option_c_hi": "चित्तरंजन दास (C.R. Das)",
          "option_d_hi": "भूलाभाई देसाई",
          "correct_option": 3,
          "explanation": "C.R. Das brilliantly defended Aurobindo Ghosh, resulting in his acquittal.",
          "explanation_hi": "सी.आर. दास ने शानदार ढंग से अरबिंदो घोष का बचाव किया, जिसके परिणामस्वरूप उन्हें बरी कर दिया गया।"
        },
        {
          "question": "Who was the mastermind behind the attempt to assassinate Viceroy Lord Hardinge in Delhi in 1912?",
          "question_hi": "1912 में दिल्ली में वायसराय लॉर्ड हार्डिंग की हत्या के प्रयास के पीछे किसका मास्टरमाइंड था?",
          "option_a": "Rash Behari Bose",
          "option_b": "Sachindra Nath Sanyal",
          "option_c": "Aurobindo Ghosh",
          "option_d": "Bagha Jatin",
          "option_a_hi": "रास बिहारी बोस",
          "option_b_hi": "शचींद्र नाथ सान्याल",
          "option_c_hi": "अरबिंदो घोष",
          "option_d_hi": "बाघा जतिन",
          "correct_option": 1,
          "explanation": "Rash Behari Bose organized the bomb throwing at Lord Hardinge during his ceremonial procession in Delhi.",
          "explanation_hi": "रास बिहारी बोस ने दिल्ली में अपने औपचारिक जुलूस के दौरान लॉर्ड हार्डिंग पर बम फेंकने का आयोजन किया।"
        },
        {
          "question": "Jatindranath Mukherjee, widely known as 'Bagha Jatin', died a heroic death fighting the British police at the battle of:",
          "question_hi": "जतींद्रनाथ मुखर्जी, जिन्हें व्यापक रूप से 'बाघा जतिन' के नाम से जाना जाता है, की किस लड़ाई में ब्रिटिश पुलिस से लड़ते हुए वीरतापूर्ण मृत्यु हुई थी?",
          "option_a": "Chittagong",
          "option_b": "Buribalam (Balasore)",
          "option_c": "Midnapore",
          "option_d": "Alipore",
          "option_a_hi": "चटगांव",
          "option_b_hi": "बूरीबलम (बालासोर)",
          "option_c_hi": "मिदनापुर",
          "option_d_hi": "अलीपुर",
          "correct_option": 2,
          "explanation": "Bagha Jatin died in September 1915 after a gunfight with the police near the Buribalam river in Balasore, Odisha.",
          "explanation_hi": "बाघा जतिन की सितंबर 1915 में ओडिशा के बालासोर में बूढ़ीबलम नदी के पास पुलिस के साथ मुठभेड़ के बाद मृत्यु हो गई थी।"
        },
        {
          "question": "The 'Zimmermann Plan' during World War I involved Indian revolutionaries securing arms from which country to organize a pan-India mutiny?",
          "question_hi": "प्रथम विश्व युद्ध के दौरान 'ज़िमरमैन योजना' में अखिल भारतीय विद्रोह को आयोजित करने के लिए भारतीय क्रांतिकारियों को किस देश से हथियार प्राप्त करना शामिल था?",
          "option_a": "Russia",
          "option_b": "Japan",
          "option_c": "Germany",
          "option_d": "France",
          "option_a_hi": "रूस",
          "option_b_hi": "जापान",
          "option_c_hi": "जर्मनी",
          "option_d_hi": "फ्रांस",
          "correct_option": 3,
          "explanation": "The Indo-German Conspiracy (Zimmermann Plan) aimed to provoke an armed rebellion in India with German arms and support.",
          "explanation_hi": "इंडो-जर्मन षडयंत्र (ज़िमरमैन योजना) का उद्देश्य जर्मन हथियारों और समर्थन के साथ भारत में एक सशस्त्र विद्रोह को भड़काना था।"
        },
        {
          "question": "Who founded the 'Mitra Mela', a secret society in Maharashtra that later became 'Abhinav Bharat'?",
          "question_hi": "महाराष्ट्र में एक गुप्त समाज 'मित्र मेला' की स्थापना किसने की थी, जो बाद में 'अभिनव भारत' बन गया?",
          "option_a": "V.D. Savarkar",
          "option_b": "Chapekar Brothers",
          "option_c": "Bal Gangadhar Tilak",
          "option_d": "Vasudev Balwant Phadke",
          "option_a_hi": "वी.डी. सावरकर",
          "option_b_hi": "चापेकर बंधु",
          "option_c_hi": "बाल गंगाधर तिलक",
          "option_d_hi": "वासुदेव बलवंत फड़के",
          "correct_option": 1,
          "explanation": "V.D. Savarkar and his brother Ganesh founded Mitra Mela in 1899, renamed Abhinav Bharat in 1904.",
          "explanation_hi": "वी.डी. सावरकर और उनके भाई गणेश ने 1899 में मित्र मेला की स्थापना की, जिसका नाम 1904 में अभिनव भारत रखा गया।"
        },
        {
          "question": "Who shot dead the unpopular Plague Commissioner of Pune, W.C. Rand, in 1897?",
          "question_hi": "1897 में पुणे के अलोकप्रिय प्लेग कमिश्नर, डब्लू.सी. रैंड की गोली मारकर हत्या किसने की?",
          "option_a": "Anant Kanhere",
          "option_b": "Chapekar Brothers",
          "option_c": "V.D. Savarkar",
          "option_d": "Madan Lal Dhingra",
          "option_a_hi": "अनंत कान्हेरे",
          "option_b_hi": "चापेकर बंधु",
          "option_c_hi": "वी.डी. सावरकर",
          "option_d_hi": "मदन लाल ढींगरा",
          "correct_option": 2,
          "explanation": "The Chapekar brothers (Damodar and Balkrishna) assassinated Rand and Lt. Ayerst in anger over the oppressive plague measures.",
          "explanation_hi": "चापेकर बंधुओं (दामोदर और बालकृष्ण) ने दमनकारी प्लेग उपायों के गुस्से में रैंड और लेफ्टिनेंट आयर्स्ट की हत्या कर दी।"
        }
      ]
    }
  },
  {
    fileName: "revolutionary_abroad_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1024,
        "title": "Revolutionary Movement Abroad (Ghadar etc.)",
        "title_hi": "विदेशों में क्रांतिकारी आंदोलन (ग़दर आदि)",
        "description": "Indian revolutionaries abroad.",
        "description_hi": "विदेशों में भारतीय क्रांतिकारी।",
        "difficulty": "Moderate",
        "total_questions": 10,
        "time_limit_mins": 15,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The Ghadar Party was founded in 1913 in which city?",
          "question_hi": "ग़दर पार्टी की स्थापना 1913 में किस शहर में हुई थी?",
          "option_a": "London",
          "option_b": "Berlin",
          "option_c": "San Francisco",
          "option_d": "Tokyo",
          "option_a_hi": "लंदन",
          "option_b_hi": "बर्लिन",
          "option_c_hi": "सैन फ्रांसिस्को",
          "option_d_hi": "टोक्यो",
          "correct_option": 3,
          "explanation": "The Ghadar Party was headquartered at the Yugantar Ashram in San Francisco, USA.",
          "explanation_hi": "ग़दर पार्टी का मुख्यालय अमेरिका के सैन फ्रांसिस्को में युगांतर आश्रम में था।"
        },
        {
          "question": "Who among the following were the founding leaders of the Ghadar Party?",
          "question_hi": "निम्नलिखित में से कौन ग़दर पार्टी के संस्थापक नेता थे?",
          "option_a": "Lala Hardayal and Sohan Singh Bhakna",
          "option_b": "Shyamji Krishna Varma and V.D. Savarkar",
          "option_c": "Madame Cama and Ajit Singh",
          "option_d": "Rash Behari Bose and Subhas Chandra Bose",
          "option_a_hi": "लाला हरदयाल और सोहन सिंह भकना",
          "option_b_hi": "श्यामजी कृष्ण वर्मा और वी.डी. सावरकर",
          "option_c_hi": "मैडम कामा और अजीत सिंह",
          "option_d_hi": "रास बिहारी बोस और सुभाष चंद्र बोस",
          "correct_option": 1,
          "explanation": "Sohan Singh Bhakna was the President and Lala Hardayal was the prominent ideologue and founder.",
          "explanation_hi": "सोहन सिंह भकना अध्यक्ष थे और लाला हरदयाल प्रमुख विचारक और संस्थापक थे।"
        },
        {
          "question": "Which tragic incident in 1914 fueled the anti-British sentiments among Punjabis in North America and accelerated the Ghadar movement?",
          "question_hi": "1914 की किस दुखद घटना ने उत्तरी अमेरिका में पंजाबियों के बीच ब्रिटिश विरोधी भावनाओं को भड़काया और ग़दर आंदोलन को तेज कर दिया?",
          "option_a": "Jallianwala Bagh Massacre",
          "option_b": "Komagata Maru Incident",
          "option_c": "Kakori Conspiracy",
          "option_d": "Chauri Chaura Incident",
          "option_a_hi": "जलियांवाला बाग हत्याकांड",
          "option_b_hi": "कामागाटामारू घटना",
          "option_c_hi": "काकोरी कांड",
          "option_d_hi": "चौरी चौरा घटना",
          "correct_option": 2,
          "explanation": "The Komagata Maru, a Japanese ship carrying Indian immigrants, was turned away from Canada and forced back to Calcutta, leading to a clash with the police.",
          "explanation_hi": "भारतीय प्रवासियों को ले जा रहे एक जापानी जहाज कामागाटामारू को कनाडा से वापस कर दिया गया और कलकत्ता वापस जाने के लिए मजबूर किया गया, जिससे पुलिस के साथ झड़प हुई।"
        },
        {
          "question": "Who set up the 'India House' in London as a center for Indian revolutionaries?",
          "question_hi": "भारतीय क्रांतिकारियों के केंद्र के रूप में लंदन में 'इंडिया हाउस' की स्थापना किसने की?",
          "option_a": "V.D. Savarkar",
          "option_b": "Shyamji Krishna Varma",
          "option_c": "Madan Lal Dhingra",
          "option_d": "Lala Hardayal",
          "option_a_hi": "वी.डी. सावरकर",
          "option_b_hi": "श्यामजी कृष्ण वर्मा",
          "option_c_hi": "मदन लाल ढींगरा",
          "option_d_hi": "लाला हरदयाल",
          "correct_option": 2,
          "explanation": "Shyamji Krishna Varma started India House in 1905, along with the journal 'The Indian Sociologist'.",
          "explanation_hi": "श्यामजी कृष्ण वर्मा ने 1905 में 'द इंडियन सोशियोलॉजिस्ट' पत्रिका के साथ इंडिया हाउस की शुरुआत की।"
        },
        {
          "question": "Madan Lal Dhingra, associated with India House, assassinated which British official in London in 1909?",
          "question_hi": "इंडिया हाउस से जुड़े मदन लाल ढींगरा ने 1909 में लंदन में किस ब्रिटिश अधिकारी की हत्या कर दी थी?",
          "option_a": "Lord Curzon",
          "option_b": "Curzon Wyllie",
          "option_c": "General Dyer",
          "option_d": "Michael O'Dwyer",
          "option_a_hi": "लॉर्ड कर्जन",
          "option_b_hi": "कर्जन वायली",
          "option_c_hi": "जनरल डायर",
          "option_d_hi": "माइकल ओ डायर",
          "correct_option": 2,
          "explanation": "Dhingra assassinated Curzon Wyllie, a high-ranking official at the India Office.",
          "explanation_hi": "ढींगरा ने भारत कार्यालय में एक उच्च पदस्थ अधिकारी कर्जन वायली की हत्या कर दी।"
        },
        {
          "question": "Who is known as the 'Mother of Indian Revolution' for hoisting the first version of the Indian national flag at Stuttgart, Germany in 1907?",
          "question_hi": "1907 में जर्मनी के स्टटगार्ट में भारतीय राष्ट्रीय ध्वज का पहला संस्करण फहराने के लिए किसे 'भारतीय क्रांति की जननी' के रूप में जाना जाता है?",
          "option_a": "Sarojini Naidu",
          "option_b": "Annie Besant",
          "option_c": "Bhikaji Cama (Madame Cama)",
          "option_d": "Preetilata Waddedar",
          "option_a_hi": "सरोजिनी नायडू",
          "option_b_hi": "एनी बेसेंट",
          "option_c_hi": "भीकाजी कामा (मैडम कामा)",
          "option_d_hi": "प्रीतिलता वाडेदार",
          "correct_option": 3,
          "explanation": "Madame Bhikaji Cama unfurled the 'Flag of Indian Independence' at the International Socialist Conference in Stuttgart.",
          "explanation_hi": "मैडम भीकाजी कामा ने स्टटगार्ट में अंतर्राष्ट्रीय समाजवादी सम्मेलन में 'भारतीय स्वतंत्रता का ध्वज' फहराया।"
        },
        {
          "question": "During World War I, Raja Mahendra Pratap established the first Provisional Government of Free India in which city?",
          "question_hi": "प्रथम विश्व युद्ध के दौरान, राजा महेंद्र प्रताप ने किस शहर में स्वतंत्र भारत की पहली अनंतिम सरकार की स्थापना की थी?",
          "option_a": "Kabul",
          "option_b": "Berlin",
          "option_c": "Singapore",
          "option_d": "Tokyo",
          "option_a_hi": "काबुल",
          "option_b_hi": "बर्लिन",
          "option_c_hi": "सिंगापुर",
          "option_d_hi": "टोक्यो",
          "correct_option": 1,
          "explanation": "In 1915, Raja Mahendra Pratap, with Barkatullah, set up a provisional government in Kabul (Afghanistan) with German-Turkish support.",
          "explanation_hi": "1915 में, राजा महेंद्र प्रताप ने बरकतुल्ला के साथ मिलकर जर्मन-तुर्की समर्थन से काबुल (अफगानिस्तान) में एक अनंतिम सरकार की स्थापना की।"
        },
        {
          "question": "The 'Berlin Committee for Indian Independence' was established in 1915 by:",
          "question_hi": "'भारतीय स्वतंत्रता के लिए बर्लिन समिति' की स्थापना 1915 में किसके द्वारा की गई थी?",
          "option_a": "Virendranath Chattopadhyay",
          "option_b": "M.N. Roy",
          "option_c": "Subhas Chandra Bose",
          "option_d": "Lala Lajpat Rai",
          "option_a_hi": "वीरेंद्रनाथ चट्टोपाध्याय",
          "option_b_hi": "एम.एन. रॉय",
          "option_c_hi": "सुभाष चंद्र बोस",
          "option_d_hi": "लाला लाजपत राय",
          "correct_option": 1,
          "explanation": "Virendranath Chattopadhyay (Chatto), Bhupendranath Dutta, and Lala Hardayal formed the Berlin Committee with German help.",
          "explanation_hi": "वीरेंद्रनाथ चट्टोपाध्याय (चट्टो), भूपेंद्रनाथ दत्त और लाला हरदयाल ने जर्मन मदद से बर्लिन समिति का गठन किया।"
        },
        {
          "question": "The primary aim of the Ghadar Party was to:",
          "question_hi": "ग़दर पार्टी का प्राथमिक उद्देश्य क्या था?",
          "option_a": "Demand Dominion status through constitutional means",
          "option_b": "Overthrow British rule in India through an armed revolution",
          "option_c": "Improve the condition of Indian laborers in America",
          "option_d": "Promote Hindu-Muslim unity abroad",
          "option_a_hi": "संवैधानिक साधनों के माध्यम से डोमिनियन स्टेटस की मांग करना",
          "option_b_hi": "सशस्त्र क्रांति के माध्यम से भारत में ब्रिटिश शासन को उखाड़ फेंकना",
          "option_c_hi": "अमेरिका में भारतीय मजदूरों की स्थिति में सुधार",
          "option_d_hi": "विदेशों में हिंदू-मुस्लिम एकता को बढ़ावा देना",
          "correct_option": 2,
          "explanation": "The Ghadarites were revolutionaries whose declared aim was to liberate India through an armed uprising.",
          "explanation_hi": "गदरवादी क्रांतिकारी थे जिनका घोषित उद्देश्य सशस्त्र विद्रोह के माध्यम से भारत को मुक्त कराना था।"
        },
        {
          "question": "Which Indian revolutionary fled to Japan to escape British authorities, and later helped organize the Indian National Army (INA)?",
          "question_hi": "कौन सा भारतीय क्रांतिकारी ब्रिटिश अधिकारियों से बचने के लिए जापान भाग गया, और बाद में भारतीय राष्ट्रीय सेना (INA) को संगठित करने में मदद की?",
          "option_a": "Rash Behari Bose",
          "option_b": "Subhas Chandra Bose",
          "option_c": "M.N. Roy",
          "option_d": "Sachindra Nath Sanyal",
          "option_a_hi": "रास बिहारी बोस",
          "option_b_hi": "सुभाष चंद्र बोस",
          "option_c_hi": "एम.एन. रॉय",
          "option_d_hi": "शचींद्र नाथ सान्याल",
          "correct_option": 1,
          "explanation": "After the failed 1915 mutiny and the Hardinge bomb case, Rash Behari Bose escaped to Japan.",
          "explanation_hi": "1915 के विफल विद्रोह और हार्डिंग बम कांड के बाद, रास बिहारी बोस जापान भाग गए।"
        }
      ]
    }
  },
  {
    fileName: "revolutionary_hsra_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1024,
        "title": "Revolutionary Movements: HSRA & Bhagat Singh",
        "title_hi": "क्रांतिकारी आंदोलन: एचएसआरए और भगत सिंह",
        "description": "Hindustan Socialist Republican Association.",
        "description_hi": "हिंदुस्तान सोशलिस्ट रिपब्लिकन एसोसिएशन।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The Hindustan Republican Association (HRA) was founded in 1924 in:",
          "question_hi": "हिंदुस्तान रिपब्लिकन एसोसिएशन (HRA) की स्थापना 1924 में कहाँ हुई थी?",
          "option_a": "Delhi",
          "option_b": "Kanpur",
          "option_c": "Lahore",
          "option_d": "Calcutta",
          "option_a_hi": "दिल्ली",
          "option_b_hi": "कानपुर",
          "option_c_hi": "लाहौर",
          "option_d_hi": "कलकत्ता",
          "correct_option": 2,
          "explanation": "HRA was founded in Kanpur by Sachindra Nath Sanyal, Ram Prasad Bismil, and Jogesh Chandra Chatterjee.",
          "explanation_hi": "HRA की स्थापना कानपुर में शचींद्र नाथ सान्याल, राम प्रसाद बिस्मिल और जोगेश चंद्र चटर्जी ने की थी।"
        },
        {
          "question": "Which of the following events is associated with the HRA revolutionaries in 1925?",
          "question_hi": "1925 में HRA क्रांतिकारियों से निम्नलिखित में से कौन सी घटना जुड़ी है?",
          "option_a": "Chittagong Armoury Raid",
          "option_b": "Kakori Train Robbery",
          "option_c": "Central Assembly Bomb Case",
          "option_d": "Lahore Conspiracy Case",
          "option_a_hi": "चटगांव शस्त्रागार छापा",
          "option_b_hi": "काकोरी ट्रेन डकैती",
          "option_c_hi": "केंद्रीय विधानसभा बम कांड",
          "option_d_hi": "लाहौर षडयंत्र केस",
          "correct_option": 2,
          "explanation": "The Kakori train robbery (1925) was carried out by Ram Prasad Bismil, Ashfaqullah Khan, and others to fund the HRA.",
          "explanation_hi": "काकोरी ट्रेन डकैती (1925) राम प्रसाद बिस्मिल, अशफाकुल्ला खान और अन्य लोगों द्वारा HRA को निधि देने के लिए की गई थी।"
        },
        {
          "question": "Who among the following was NOT hanged in the Kakori Conspiracy Case?",
          "question_hi": "निम्नलिखित में से किसे काकोरी षडयंत्र मामले में फांसी नहीं दी गई थी?",
          "option_a": "Ram Prasad Bismil",
          "option_b": "Ashfaqullah Khan",
          "option_c": "Rajendra Lahiri",
          "option_d": "Chandrashekhar Azad",
          "option_a_hi": "राम प्रसाद बिस्मिल",
          "option_b_hi": "अशफाकुल्ला खान",
          "option_c_hi": "राजेंद्र लाहिड़ी",
          "option_d_hi": "चंद्रशेखर आज़ाद",
          "correct_option": 4,
          "explanation": "Chandrashekhar Azad evaded arrest. Bismil, Ashfaqullah, Lahiri, and Roshan Singh were hanged.",
          "explanation_hi": "चंद्रशेखर आजाद गिरफ्तारी से बच निकले। बिस्मिल, अशफाकुल्ला, लाहिड़ी और रोशन सिंह को फांसी दी गई।"
        },
        {
          "question": "The HRA was reorganized and renamed as Hindustan Socialist Republican Association (HSRA) in 1928 at:",
          "question_hi": "HRA को 1928 में कहाँ पुनर्गठित किया गया और इसका नाम बदलकर हिंदुस्तान सोशलिस्ट रिपब्लिकन एसोसिएशन (HSRA) कर दिया गया?",
          "option_a": "Feroz Shah Kotla, Delhi",
          "option_b": "Jallianwala Bagh, Amritsar",
          "option_c": "Alfred Park, Allahabad",
          "option_d": "Eden Gardens, Calcutta",
          "option_a_hi": "फ़िरोज़ शाह कोटला, दिल्ली",
          "option_b_hi": "जलियांवाला बाग, अमृतसर",
          "option_c_hi": "अल्फ्रेड पार्क, इलाहाबाद",
          "option_d_hi": "ईडन गार्डन्स, कलकत्ता",
          "correct_option": 1,
          "explanation": "Under the leadership of Chandrashekhar Azad and Bhagat Singh, the word 'Socialist' was added at a meeting in Feroz Shah Kotla.",
          "explanation_hi": "चंद्रशेखर आजाद और भगत सिंह के नेतृत्व में, फिरोज शाह कोटला में एक बैठक में 'सोशलिस्ट' शब्द जोड़ा गया था।"
        },
        {
          "question": "Bhagat Singh, Shivaram Rajguru, and Sukhdev Thapar assassinated John Saunders to avenge the death of:",
          "question_hi": "भगत सिंह, शिवराम राजगुरु और सुखदेव थापर ने किसकी मृत्यु का बदला लेने के लिए जॉन सॉन्डर्स की हत्या कर दी?",
          "option_a": "Bipin Chandra Pal",
          "option_b": "Lala Lajpat Rai",
          "option_c": "Bal Gangadhar Tilak",
          "option_d": "Ram Prasad Bismil",
          "option_a_hi": "बिपिन चंद्र पाल",
          "option_b_hi": "लाला लाजपत राय",
          "option_c_hi": "बाल गंगाधर तिलक",
          "option_d_hi": "राम प्रसाद बिस्मिल",
          "correct_option": 2,
          "explanation": "They assassinated Saunders, mistaking him for James A. Scott, the police chief who ordered the lathi charge on Lala Lajpat Rai.",
          "explanation_hi": "उन्होंने जेम्स ए. स्कॉट, पुलिस प्रमुख जिसने लाला लाजपत राय पर लाठीचार्ज का आदेश दिया था, की गलती से सांडर्स की हत्या कर दी।"
        },
        {
          "question": "Who accompanied Bhagat Singh to throw a bomb in the Central Legislative Assembly in April 1929?",
          "question_hi": "अप्रैल 1929 में केंद्रीय विधान सभा में बम फेंकने के लिए भगत सिंह के साथ कौन गया था?",
          "option_a": "Chandrashekhar Azad",
          "option_b": "Sukhdev",
          "option_c": "Batukeshwar Dutt",
          "option_d": "Rajguru",
          "option_a_hi": "चंद्रशेखर आज़ाद",
          "option_b_hi": "सुखदेव",
          "option_c_hi": "बटुकेश्वर दत्त",
          "option_d_hi": "राजगुरु",
          "correct_option": 3,
          "explanation": "Bhagat Singh and Batukeshwar Dutt threw harmless bombs in the Assembly to protest against the Public Safety Bill.",
          "explanation_hi": "भगत सिंह और बटुकेश्वर दत्त ने पब्लिक सेफ्टी बिल के विरोध में असेंबली में हानिरहित बम फेंके।"
        },
        {
          "question": "Which HSRA revolutionary died after a historic 63-day hunger strike in jail demanding political prisoner status?",
          "question_hi": "राजनीतिक कैदी के दर्जे की मांग को लेकर जेल में ऐतिहासिक 63 दिन की भूख हड़ताल के बाद किस HSRA क्रांतिकारी की मृत्यु हो गई?",
          "option_a": "Sachindra Nath Sanyal",
          "option_b": "Jatin Das",
          "option_c": "Bhagwati Charan Vohra",
          "option_d": "Ram Prasad Bismil",
          "option_a_hi": "शचींद्र नाथ सान्याल",
          "option_b_hi": "जतिन दास",
          "option_c_hi": "भगवती चरण वोहरा",
          "option_d_hi": "राम प्रसाद बिस्मिल",
          "correct_option": 2,
          "explanation": "Jatin Das died on September 13, 1929, creating a massive uproar across the country.",
          "explanation_hi": "13 सितंबर, 1929 को जतिन दास की मृत्यु हो गई, जिससे पूरे देश में भारी हंगामा हुआ।"
        },
        {
          "question": "Chandrashekhar Azad shot himself rather than being captured alive during an encounter with the police at:",
          "question_hi": "चंद्रशेखर आजाद ने पुलिस के साथ मुठभेड़ में जिंदा पकड़े जाने के बजाय खुद को गोली मार ली थी:",
          "option_a": "Company Bagh, Kanpur",
          "option_b": "Jallianwala Bagh, Amritsar",
          "option_c": "Alfred Park, Allahabad",
          "option_d": "Feroz Shah Kotla, Delhi",
          "option_a_hi": "कंपनी बाग, कानपुर",
          "option_b_hi": "जलियांवाला बाग, अमृतसर",
          "option_c_hi": "अल्फ्रेड पार्क, इलाहाबाद",
          "option_d_hi": "फ़िरोज़ शाह कोटला, दिल्ली",
          "correct_option": 3,
          "explanation": "He died in February 1931 at Alfred Park (now Chandrashekhar Azad Park) in Allahabad.",
          "explanation_hi": "फरवरी 1931 में इलाहाबाद के अल्फ्रेड पार्क (अब चंद्रशेखर आज़ाद पार्क) में उनकी मृत्यु हो गई।"
        },
        {
          "question": "Bhagat Singh, Rajguru, and Sukhdev were hanged on March 23, 1931. This day is observed in India as:",
          "question_hi": "भगत सिंह, राजगुरु और सुखदेव को 23 मार्च, 1931 को फांसी दी गई थी। इस दिन को भारत में किस रूप में मनाया जाता है?",
          "option_a": "Parakram Diwas",
          "option_b": "Shaheed Diwas (Martyrs' Day)",
          "option_c": "Krantikari Diwas",
          "option_d": "Swaraj Diwas",
          "option_a_hi": "पराक्रम दिवस",
          "option_b_hi": "शहीद दिवस (Martyrs' Day)",
          "option_c_hi": "क्रांतिकारी दिवस",
          "option_d_hi": "स्वराज दिवस",
          "correct_option": 2,
          "explanation": "March 23 is observed as Shaheed Diwas to honor their supreme sacrifice.",
          "explanation_hi": "उनके सर्वोच्च बलिदान के सम्मान में 23 मार्च को शहीद दिवस के रूप में मनाया जाता है।"
        },
        {
          "question": "Who authored the famous tract 'The Philosophy of the Bomb'?",
          "question_hi": "प्रसिद्ध लेख 'द फिलॉसफी ऑफ द बॉम्ब' (The Philosophy of the Bomb) के लेखक कौन हैं?",
          "option_a": "Bhagat Singh",
          "option_b": "Chandrashekhar Azad",
          "option_c": "Bhagwati Charan Vohra",
          "option_d": "Sachindra Nath Sanyal",
          "option_a_hi": "भगत सिंह",
          "option_b_hi": "चंद्रशेखर आज़ाद",
          "option_c_hi": "भगवती चरण वोहरा",
          "option_d_hi": "शचींद्र नाथ सान्याल",
          "correct_option": 3,
          "explanation": "Bhagwati Charan Vohra wrote it as a response to Gandhi's article 'The Cult of the Bomb'.",
          "explanation_hi": "भगवती चरण वोहरा ने इसे गांधी के लेख 'द कल्ट ऑफ द बॉम्ब' के जवाब में लिखा था।"
        },
        {
          "question": "The Chittagong Armoury Raid (1930) in Bengal was led by:",
          "question_hi": "बंगाल में चटगांव शस्त्रागार छापे (1930) का नेतृत्व किसके द्वारा किया गया था?",
          "option_a": "Surya Sen",
          "option_b": "Jatindra Nath Das",
          "option_c": "Sachindra Nath Sanyal",
          "option_d": "Rash Behari Bose",
          "option_a_hi": "सूर्य सेन",
          "option_b_hi": "जतींद्र नाथ दास",
          "option_c_hi": "शचींद्र नाथ सान्याल",
          "option_d_hi": "रास बिहारी बोस",
          "correct_option": 1,
          "explanation": "Surya Sen, affectionately known as 'Masterda', organized the Chittagong armoury raid with his group, the Indian Republican Army.",
          "explanation_hi": "सूर्य सेन, जिन्हें प्यार से 'मास्टरदा' कहा जाता था, ने अपने समूह, इंडियन रिपब्लिकन आर्मी के साथ चटगांव शस्त्रागार छापे का आयोजन किया।"
        },
        {
          "question": "Which of the following women revolutionaries participated in the Chittagong armoury raid?",
          "question_hi": "निम्नलिखित में से किस महिला क्रांतिकारी ने चटगांव शस्त्रागार छापे में भाग लिया था?",
          "option_a": "Kalpana Dutt and Pritilata Waddedar",
          "option_b": "Bhikaji Cama and Sarojini Naidu",
          "option_c": "Kasturba Gandhi and Kamala Nehru",
          "option_d": "Rani Gaidinliu and Matangini Hazra",
          "option_a_hi": "कल्पना दत्त और प्रीतिलता वाडेदार",
          "option_b_hi": "भीकाजी कामा और सरोजिनी नायडू",
          "option_c_hi": "कस्तूरबा गांधी और कमला नेहरू",
          "option_d_hi": "रानी गाईदिन्ल्यू और मातंगिनी हाजरा",
          "correct_option": 1,
          "explanation": "Surya Sen actively recruited women. Pritilata Waddedar led a raid on the Pahartali European Club and took cyanide to avoid arrest.",
          "explanation_hi": "सूर्य सेन ने महिलाओं की सक्रिय रूप से भर्ती की। प्रीतिलता वाडेदार ने पहाड़तली यूरोपीय क्लब पर छापे का नेतृत्व किया और गिरफ्तारी से बचने के लिए साइनाइड खा लिया।"
        },
        {
          "question": "The revolutionary organization 'Naujawan Bharat Sabha' was founded by:",
          "question_hi": "क्रांतिकारी संगठन 'नौजवान भारत सभा' की स्थापना किसके द्वारा की गई थी?",
          "option_a": "Bhagat Singh",
          "option_b": "Subhas Chandra Bose",
          "option_c": "Chandrashekhar Azad",
          "option_d": "V.D. Savarkar",
          "option_a_hi": "भगत सिंह",
          "option_b_hi": "सुभाष चंद्र बोस",
          "option_c_hi": "चंद्रशेखर आज़ाद",
          "option_d_hi": "वी.डी. सावरकर",
          "correct_option": 1,
          "explanation": "Bhagat Singh founded it in 1926 to encourage youth to join the freedom struggle.",
          "explanation_hi": "भगत सिंह ने युवाओं को स्वतंत्रता संग्राम में शामिल होने के लिए प्रोत्साहित करने के लिए 1926 में इसकी स्थापना की थी।"
        },
        {
          "question": "What was the justification given by Bhagat Singh and B.K. Dutt in court for throwing the bomb?",
          "question_hi": "भगत सिंह और बी.के. दत्त ने बम फेंकने के लिए अदालत में क्या औचित्य दिया?",
          "option_a": "To kill the Viceroy",
          "option_b": "To make the deaf hear",
          "option_c": "To steal British weapons",
          "option_d": "To initiate an armed mutiny in Delhi",
          "option_a_hi": "वायसराय को मारने के लिए",
          "option_b_hi": "बहरों को सुनाने के लिए",
          "option_c_hi": "ब्रिटिश हथियार चुराने के लिए",
          "option_d_hi": "दिल्ली में सशस्त्र विद्रोह शुरू करने के लिए",
          "correct_option": 2,
          "explanation": "Their leaflet read, 'It takes a loud voice to make the deaf hear'. Their intent was to protest, not to kill.",
          "explanation_hi": "उनके पर्चे में लिखा था, 'बहरों को सुनाने के लिए तेज आवाज की जरूरत होती है'। उनका इरादा विरोध करना था, मारना नहीं।"
        },
        {
          "question": "Who among the following was the founder of the 'Anushilan Samiti' in Dhaka?",
          "question_hi": "ढाका में 'अनुशीलन समिति' के संस्थापक निम्नलिखित में से कौन थे?",
          "option_a": "Barindra Kumar Ghosh",
          "option_b": "Pulin Behari Das",
          "option_c": "Sachindra Nath Sanyal",
          "option_d": "Aurobindo Ghosh",
          "option_a_hi": "बारिन्द्र कुमार घोष",
          "option_b_hi": "पुलिन बिहारी दास",
          "option_c_hi": "शचींद्र नाथ सान्याल",
          "option_d_hi": "अरबिंदो घोष",
          "correct_option": 2,
          "explanation": "The Dhaka branch of Anushilan Samiti was founded and led by Pulin Behari Das in 1906.",
          "explanation_hi": "अनुशीलन समिति की ढाका शाखा की स्थापना और नेतृत्व 1906 में पुलिन बिहारी दास ने की थी।"
        }
      ]
    }
  },
  {
    fileName: "home_rule_quiz.json",
    data: {
      "quiz": {
        "topic_id": 1025,
        "title": "Home Rule Movement & Lucknow Pact",
        "title_hi": "होमरूल आंदोलन और लखनऊ समझौता",
        "description": "Annie Besant, Tilak, and the 1916 Pact.",
        "description_hi": "एनी बेसेंट, तिलक, और 1916 का समझौता।",
        "difficulty": "Moderate",
        "total_questions": 15,
        "time_limit_mins": 20,
        "is_previous_year": false
      },
      "questions": [
        {
          "question": "The idea of starting a Home Rule League in India was inspired by a similar movement in which country?",
          "question_hi": "भारत में होमरूल लीग शुरू करने का विचार किस देश में इसी तरह के आंदोलन से प्रेरित था?",
          "option_a": "USA",
          "option_b": "Ireland",
          "option_c": "South Africa",
          "option_d": "Russia",
          "option_a_hi": "संयुक्त राज्य अमेरिका (USA)",
          "option_b_hi": "आयरलैंड",
          "option_c_hi": "दक्षिण अफ्रीका",
          "option_d_hi": "रूस",
          "correct_option": 2,
          "explanation": "Annie Besant modeled the movement on the Irish Home Rule League.",
          "explanation_hi": "एनी बेसेंट ने इस आंदोलन को आयरिश होमरूल लीग की तर्ज पर तैयार किया।"
        },
        {
          "question": "Who launched the first Home Rule League in April 1916?",
          "question_hi": "अप्रैल 1916 में पहली होमरूल लीग की शुरुआत किसने की?",
          "option_a": "Annie Besant",
          "option_b": "Bal Gangadhar Tilak",
          "option_c": "Mahatma Gandhi",
          "option_d": "Jawaharlal Nehru",
          "option_a_hi": "एनी बेसेंट",
          "option_b_hi": "बाल गंगाधर तिलक",
          "option_c_hi": "महात्मा गांधी",
          "option_d_hi": "जवाहरलाल नेहरू",
          "correct_option": 2,
          "explanation": "Tilak set up his Home Rule League in April 1916 at Belgaum, while Besant formally launched hers in September 1916.",
          "explanation_hi": "तिलक ने अप्रैल 1916 में बेलगाम में अपनी होमरूल लीग की स्थापना की, जबकि बेसेंट ने औपचारिक रूप से सितंबर 1916 में अपनी लीग शुरू की।"
        },
        {
          "question": "Tilak's Home Rule League was restricted to which areas?",
          "question_hi": "तिलक की होमरूल लीग किन क्षेत्रों तक सीमित थी?",
          "option_a": "Maharashtra (excluding Bombay city), Karnataka, Central Provinces, and Berar",
          "option_b": "All of India",
          "option_c": "Only Bombay and Madras cities",
          "option_d": "Bengal and Punjab",
          "option_a_hi": "महाराष्ट्र (बंबई शहर को छोड़कर), कर्नाटक, मध्य प्रांत और बरार",
          "option_b_hi": "पूरे भारत में",
          "option_c_hi": "केवल बंबई और मद्रास शहर में",
          "option_d_hi": "बंगाल और पंजाब",
          "correct_option": 1,
          "explanation": "Tilak's League covered these specific areas. Annie Besant's League covered the rest of India (including Bombay city).",
          "explanation_hi": "तिलक की लीग ने इन विशिष्ट क्षेत्रों को कवर किया। एनी बेसेंट की लीग ने भारत के बाकी हिस्सों (बंबई शहर सहित) को कवर किया।"
        },
        {
          "question": "Which two newspapers were launched by Annie Besant to propagate the ideas of the Home Rule movement?",
          "question_hi": "होमरूल आंदोलन के विचारों का प्रचार करने के लिए एनी बेसेंट ने कौन से दो समाचार पत्र शुरू किए थे?",
          "option_a": "Kesari and Mahratta",
          "option_b": "New India and Commonweal",
          "option_c": "Young India and Harijan",
          "option_d": "Al-Hilal and Al-Balagh",
          "option_a_hi": "केसरी और मराठा",
          "option_b_hi": "न्यू इंडिया और कॉमनवील",
          "option_c_hi": "यंग इंडिया और हरिजन",
          "option_d_hi": "अल-हिलाल और अल-बलाग",
          "correct_option": 2,
          "explanation": "Annie Besant started the daily 'New India' and the weekly 'Commonweal'.",
          "explanation_hi": "एनी बेसेंट ने दैनिक 'न्यू इंडिया' और साप्ताहिक 'कॉमनवील' की शुरुआत की।"
        },
        {
          "question": "The historic Lucknow Pact (1916) was an agreement between:",
          "question_hi": "ऐतिहासिक लखनऊ समझौता (1916) किसके बीच एक समझौता था?",
          "option_a": "Moderates and Extremists",
          "option_b": "Indian National Congress and Muslim League",
          "option_c": "British Government and Indian Princes",
          "option_d": "Gandhi and Ambedkar",
          "option_a_hi": "नरमपंथियों और चरमपंथियों",
          "option_b_hi": "भारतीय राष्ट्रीय कांग्रेस और मुस्लिम लीग",
          "option_c_hi": "ब्रिटिश सरकार और भारतीय राजकुमारों",
          "option_d_hi": "गांधी और अम्बेडकर",
          "correct_option": 2,
          "explanation": "The Lucknow Pact was an agreement between the INC and the Muslim League. (Though the 1916 session also saw the reunion of Moderates and Extremists).",
          "explanation_hi": "लखनऊ समझौता INC और मुस्लिम लीग के बीच एक समझौता था। (हालाँकि 1916 के सत्र में नरमपंथियों और चरमपंथियों का पुनर्मिलन भी देखा गया था)।"
        },
        {
          "question": "Who presided over the 1916 Lucknow Session of the Indian National Congress where the Moderates and Extremists reunited?",
          "question_hi": "भारतीय राष्ट्रीय कांग्रेस के 1916 के लखनऊ अधिवेशन की अध्यक्षता किसने की थी जहाँ नरमपंथी और चरमपंथी फिर से एकजुट हुए थे?",
          "option_a": "Annie Besant",
          "option_b": "Ambika Charan Majumdar",
          "option_c": "Rash Behari Ghosh",
          "option_d": "Madan Mohan Malaviya",
          "option_a_hi": "एनी बेसेंट",
          "option_b_hi": "अंबिका चरण मजूमदार",
          "option_c_hi": "रास बिहारी घोष",
          "option_d_hi": "मदन मोहन मालवीय",
          "correct_option": 2,
          "explanation": "A.C. Majumdar, a Moderate leader, presided over this historic session.",
          "explanation_hi": "एक उदारवादी नेता, ए.सी. मजूमदार ने इस ऐतिहासिक सत्र की अध्यक्षता की।"
        },
        {
          "question": "A major concession given by the Congress to the Muslim League in the Lucknow Pact was:",
          "question_hi": "लखनऊ समझौते में कांग्रेस द्वारा मुस्लिम लीग को दी गई एक बड़ी रियायत क्या थी?",
          "option_a": "Acceptance of a separate nation for Muslims",
          "option_b": "Acceptance of separate electorates for Muslims",
          "option_c": "Reservation of 50% seats in the Central Legislature",
          "option_d": "Agreement to ban cow slaughter",
          "option_a_hi": "मुसलमानों के लिए एक अलग राष्ट्र की स्वीकृति",
          "option_b_hi": "मुसलमानों के लिए अलग निर्वाचक मंडल (separate electorates) की स्वीकृति",
          "option_c_hi": "केंद्रीय विधानमंडल में 50% सीटों का आरक्षण",
          "option_d_hi": "गौ हत्या पर प्रतिबंध लगाने का समझौता",
          "correct_option": 2,
          "explanation": "Congress formally accepted the provision of separate electorates for Muslims (originally granted in the 1909 Morley-Minto reforms).",
          "explanation_hi": "कांग्रेस ने औपचारिक रूप से मुसलमानों के लिए अलग निर्वाचक मंडल (मूल रूप से 1909 के मॉर्ले-मिंटो सुधारों में दिए गए) के प्रावधान को स्वीकार कर लिया।"
        },
        {
          "question": "Who was the chief architect of the Lucknow Pact from the Muslim League side, earning the title 'Ambassador of Hindu-Muslim Unity' from Sarojini Naidu?",
          "question_hi": "मुस्लिम लीग की ओर से लखनऊ समझौते के मुख्य वास्तुकार कौन थे, जिन्हें सरोजिनी नायडू ने 'हिंदू-मुस्लिम एकता के राजदूत' की उपाधि दी थी?",
          "option_a": "Aga Khan",
          "option_b": "Syed Ahmad Khan",
          "option_c": "Muhammad Ali Jinnah",
          "option_d": "Maulana Abul Kalam Azad",
          "option_a_hi": "आगा खान",
          "option_b_hi": "सैयद अहमद खान",
          "option_c_hi": "मुहम्मद अली जिन्ना",
          "option_d_hi": "मौलाना अबुल कलाम आजाद",
          "correct_option": 3,
          "explanation": "Jinnah played a crucial role in bringing the League and Congress together in 1916.",
          "explanation_hi": "जिन्ना ने 1916 में लीग और कांग्रेस को एक साथ लाने में महत्वपूर्ण भूमिका निभाई थी।"
        },
        {
          "question": "The Home Rule Movement faded out by 1919 due to:",
          "question_hi": "1919 तक होमरूल आंदोलन किस कारण से फीका पड़ गया?",
          "option_a": "The arrest of Tilak and Besant",
          "option_b": "The Montagu Declaration (1917) and emergence of Gandhi",
          "option_c": "The passing of the Rowlatt Act",
          "option_d": "The split in the Home Rule League",
          "option_a_hi": "तिलक और बेसेंट की गिरफ्तारी",
          "option_b_hi": "मोंटेग्यू घोषणा (1917) और गांधी का उदय",
          "option_c_hi": "रॉलेट एक्ट का पारित होना",
          "option_d_hi": "होमरूल लीग में विभाजन",
          "correct_option": 2,
          "explanation": "The Montagu Declaration promised responsible government, pacifying Moderates. Besant accepted the reforms, Tilak went to London, and Gandhi took center stage.",
          "explanation_hi": "मोंटेग्यू घोषणा ने जिम्मेदार सरकार का वादा किया, जिससे नरमपंथी शांत हो गए। बेसेंट ने सुधारों को स्वीकार कर लिया, तिलक लंदन चले गए, और गांधी ने मुख्य मंच ले लिया।"
        },
        {
          "question": "Who among the following declined to join the Home Rule League?",
          "question_hi": "निम्नलिखित में से किसने होमरूल लीग में शामिल होने से इनकार कर दिया?",
          "option_a": "Motilal Nehru",
          "option_b": "Jawaharlal Nehru",
          "option_c": "Gopal Krishna Gokhale (Servants of India Society)",
          "option_d": "C.R. Das",
          "option_a_hi": "मोतीलाल नेहरू",
          "option_b_hi": "जवाहरलाल नेहरू",
          "option_c_hi": "गोपाल कृष्ण गोखले (सर्वेंट्स ऑफ इंडिया सोसाइटी)",
          "option_d_hi": "सी.आर. दास",
          "correct_option": 3,
          "explanation": "Members of Gokhale's Servants of India Society were not permitted to join the Home Rule League, though many sympathized.",
          "explanation_hi": "गोखले की सर्वेंट्स ऑफ इंडिया सोसाइटी के सदस्यों को होमरूल लीग में शामिल होने की अनुमति नहीं थी, हालांकि कई सहानुभूति रखते थे।"
        },
        {
          "question": "In which year did Annie Besant become the first woman President of the Indian National Congress?",
          "question_hi": "एनी बेसेंट किस वर्ष भारतीय राष्ट्रीय कांग्रेस की पहली महिला अध्यक्ष बनीं?",
          "option_a": "1915",
          "option_b": "1916",
          "option_c": "1917",
          "option_d": "1925",
          "option_a_hi": "1915",
          "option_b_hi": "1916",
          "option_c_hi": "1917",
          "option_d_hi": "1925",
          "correct_option": 3,
          "explanation": "Due to the immense popularity of the Home Rule movement, she was elected President at the 1917 Calcutta Session.",
          "explanation_hi": "होमरूल आंदोलन की अपार लोकप्रियता के कारण, उन्हें 1917 के कलकत्ता अधिवेशन में अध्यक्ष चुना गया।"
        },
        {
          "question": "What was the main objective of the Home Rule Movement?",
          "question_hi": "होमरूल आंदोलन का मुख्य उद्देश्य क्या था?",
          "option_a": "Complete independence from British rule",
          "option_b": "Self-government within the British Empire",
          "option_c": "Overthrow the British via armed struggle",
          "option_d": "Establishment of a socialist state",
          "option_a_hi": "ब्रिटिश शासन से पूर्ण स्वतंत्रता",
          "option_b_hi": "ब्रिटिश साम्राज्य के भीतर स्वशासन (Self-government)",
          "option_c_hi": "सशस्त्र संघर्ष के माध्यम से अंग्रेजों को उखाड़ फेंकना",
          "option_d_hi": "एक समाजवादी राज्य की स्थापना",
          "correct_option": 2,
          "explanation": "Like the Irish Home Rule, the aim was self-government (Dominion status) within the British Empire using constitutional means.",
          "explanation_hi": "आयरिश होमरूल की तरह, इसका उद्देश्य संवैधानिक साधनों का उपयोग करके ब्रिटिश साम्राज्य के भीतर स्वशासन (डोमिनियन स्टेटस) प्राप्त करना था।"
        },
        {
          "question": "Which prominent Indian leader renounced his knighthood in protest against the arrest of Annie Besant in 1917?",
          "question_hi": "1917 में एनी बेसेंट की गिरफ्तारी के विरोध में किस प्रमुख भारतीय नेता ने अपनी नाइटहुड की उपाधि त्याग दी?",
          "option_a": "Rabindranath Tagore",
          "option_b": "Subramaniya Iyer",
          "option_c": "Tej Bahadur Sapru",
          "option_d": "Surendranath Banerjee",
          "option_a_hi": "रवींद्रनाथ टैगोर",
          "option_b_hi": "सुब्रमण्यम अय्यर",
          "option_c_hi": "तेज बहादुर सप्रू",
          "option_d_hi": "सुरेंद्रनाथ बनर्जी",
          "correct_option": 2,
          "explanation": "Sir S. Subramaniya Iyer renounced his knighthood in protest when the government arrested Annie Besant, B.P. Wadia, and George Arundale.",
          "explanation_hi": "सर एस. सुब्रमण्यम अय्यर ने सरकार द्वारा एनी बेसेंट, बी.पी. वाडिया और जॉर्ज अरुंडेल को गिरफ्तार करने के विरोध में अपनी नाइटहुड की उपाधि त्याग दी।"
        },
        {
          "question": "The historic 'August Declaration' (Montagu Declaration) was made in which year?",
          "question_hi": "ऐतिहासिक 'अगस्त घोषणा' (मोंटेग्यू घोषणा) किस वर्ष की गई थी?",
          "option_a": "1916",
          "option_b": "1917",
          "option_c": "1918",
          "option_d": "1919",
          "option_a_hi": "1916",
          "option_b_hi": "1917",
          "option_c_hi": "1918",
          "option_d_hi": "1919",
          "correct_option": 2,
          "explanation": "On 20 August 1917, Secretary of State Edwin Montagu declared the policy of 'increasing association of Indians in every branch of administration'.",
          "explanation_hi": "20 अगस्त 1917 को, राज्य सचिव एडविन मोंटेग्यू ने 'प्रशासन की प्रत्येक शाखा में भारतीयों की बढ़ती भागीदारी' की नीति की घोषणा की।"
        },
        {
          "question": "Why did Tilak have to go to England in 1918, which severely impacted the Home Rule movement?",
          "question_hi": "1918 में तिलक को इंग्लैंड क्यों जाना पड़ा, जिसने होमरूल आंदोलन को गंभीर रूप से प्रभावित किया?",
          "option_a": "To attend the Round Table Conference",
          "option_b": "To pursue a libel case against Valentine Chirol",
          "option_c": "To meet the British Prime Minister regarding Home Rule",
          "option_d": "He was exiled by the Indian government",
          "option_a_hi": "गोलमेज सम्मेलन में भाग लेने के लिए",
          "option_b_hi": "वैलेंटाइन चिरोल के खिलाफ मानहानि का मुकदमा चलाने के लिए",
          "option_c_hi": "होमरूल के संबंध में ब्रिटिश प्रधान मंत्री से मिलने के लिए",
          "option_d_hi": "उन्हें भारत सरकार द्वारा निर्वासित किया गया था",
          "correct_option": 2,
          "explanation": "Tilak went to England to fight a libel suit against Valentine Chirol (author of 'Indian Unrest'), leaving the movement leaderless in India.",
          "explanation_hi": "तिलक वैलेंटाइन चिरोल ('इंडियन अनरेस्ट' के लेखक) के खिलाफ मानहानि का मुकदमा लड़ने के लिए इंग्लैंड गए थे, जिससे भारत में आंदोलन नेतृत्वविहीन हो गया।"
        }
      ]
    }
  }
];

async function insertAll() {
  for (const q of quizzes) {
    fs.writeFileSync(q.fileName, JSON.stringify(q.data, null, 2));
  }
}
insertAll();
