
-- Create subtopics table
CREATE TABLE IF NOT EXISTS subtopics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  name_hi TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Add subtopic_id columns (SQLite doesn't error if they exist, but ALTER TABLE doesn't support IF NOT EXISTS in old SQLite.
-- We'll try to add them via a migration wrapper or just run it directly.
ALTER TABLE quizzes ADD COLUMN subtopic_id INTEGER;
ALTER TABLE quiz_attempts ADD COLUMN subtopic_id INTEGER;

-- Clear old data
DELETE FROM subjects;
DELETE FROM topics;

-- Insert Subjects
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (1, 'Paper 1 · General Studies (India)', '🏛️', 'History of India & Indian Freedom Struggle', 1);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (2, 'Paper 1 · General Studies (India)', '🗺️', 'Physical Geography of India', 2);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (3, 'Paper 1 · General Studies (India)', '⚖️', 'Social Geography of India', 3);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (4, 'Paper 1 · General Studies (India)', '💰', 'Economic Geography of India', 4);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (5, 'Paper 1 · General Studies (India)', '🔬', 'Indian Constitution', 5);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (6, 'Paper 1 · General Studies (India)', '🎭', 'Indian Polity / State System', 6);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (7, 'Paper 1 · General Studies (India)', '🌱', 'Indian Economy', 7);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (8, 'Paper 1 · General Studies (India)', '📰', 'General Science', 8);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (9, 'Paper 1 · General Studies (India)', '⚙️', 'Technology', 9);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (10, 'Paper 1 · General Studies (India)', '🤔', 'Indian Philosophy', 10);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (11, 'Paper 1 · General Studies (India)', '🎨', 'Art, Literature & Culture of India', 11);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (12, 'Paper 1 · General Studies (India)', '📅', 'Current Affairs (National/International)', 12);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (13, 'Paper 1 · General Studies (India)', '🏏', 'Sports', 13);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (14, 'Paper 1 · General Studies (India)', '🌲', 'Environment', 14);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (15, 'Paper 1 · General Studies (India)', '🏔️', 'History of Chhattisgarh', 15);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (16, 'Paper 1 · General Studies (India)', '📜', 'Chhattisgarh''s Role in Freedom Movement', 16);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (17, 'Paper 1 · General Studies (India)', '🌄', 'Geography of Chhattisgarh', 17);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (18, 'Paper 1 · General Studies (India)', '📊', 'Census & Demographics of Chhattisgarh', 18);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (19, 'Paper 1 · General Studies (India)', '🛕', 'Archaeological & Tourist Centres', 19);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (20, 'Paper 1 · General Studies (India)', '✍️', 'Literature of Chhattisgarh', 20);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (21, 'Paper 1 · General Studies (India)', '💃', 'Music, Dance, Art & Culture', 21);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (22, 'Paper 1 · General Studies (India)', '🗨️', 'Chhattisgarhi Idioms, Proverbs & Folk Sayings', 22);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (23, 'Paper 1 · General Studies (India)', '🏹', 'Tribes of Chhattisgarh', 23);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (24, 'Paper 1 · General Studies (India)', '🎪', 'Special Traditions, Teej & Festivals', 24);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (25, 'Paper 1 · General Studies (India)', '📉', 'Economy of Chhattisgarh', 25);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (26, 'Paper 1 · General Studies (India)', '🌾', 'Forest & Agriculture of Chhattisgarh', 26);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (27, 'Paper 1 · General Studies (India)', '🏢', 'Administrative Structure of Chhattisgarh', 27);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (28, 'Paper 1 · General Studies (India)', '🏘️', 'Local Government & Panchayati Raj', 28);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (29, 'Paper 1 · General Studies (India)', '🏭', 'Industry, Energy, Water & Mineral Resources', 29);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (30, 'Paper 1 · General Studies (India)', '🗞️', 'Current Affairs of Chhattisgarh', 30);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (31, 'Paper 1 · General Studies (India)', '🧩', 'Interpersonal & Communication Skills', 31);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (32, 'Paper 1 · General Studies (India)', '🔢', 'Logical Reasoning', 32);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (33, 'Paper 1 · General Studies (India)', '🧠', 'Analytical Ability', 33);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (34, 'Paper 1 · General Studies (India)', '💡', 'Decision Making & Problem Solving', 34);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (35, 'Paper 1 · General Studies (India)', '🎲', 'General Mental Ability', 35);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (36, 'Paper 1 · General Studies (India)', '➗', 'Basic Numeracy (Class X Level)', 36);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (37, 'Paper 1 · General Studies (India)', '📈', 'Data Interpretation', 37);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (38, 'Paper 1 · General Studies (India)', '🗣️', 'Hindi Language Knowledge (Class X Level)', 38);
INSERT INTO subjects (id, paper, icon, name, sort_order) VALUES (39, 'Paper 1 · General Studies (India)', '💬', 'Chhattisgarhi Language Knowledge', 39);

-- Insert Topics
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1001, 1, 'Pre-historic & Proto-historic India (Stone Age, Chalcolithic)', 1001);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1002, 1, 'Indus Valley Civilization', 1002);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1003, 1, 'Vedic Age (Early & Later Vedic)', 1003);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1004, 1, 'Jainism & Buddhism origins and spread', 1004);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1005, 1, 'Mahajanapadas & Rise of Magadha', 1005);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1006, 1, 'Mauryan Empire (Chandragupta, Ashoka, Administration)', 1006);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1007, 1, 'Post-Mauryan dynasties (Shunga, Kanva, Satavahana, Indo-Greeks)', 1007);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1008, 1, 'Gupta Empire (Polity, Economy, Golden Age)', 1008);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1009, 1, 'Post-Gupta period & Harshavardhana', 1009);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1010, 1, 'South Indian Dynasties (Chola, Chera, Pandya, Pallava)', 1010);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1011, 1, 'Delhi Sultanate (Slave, Khilji, Tughlaq, Sayyid, Lodi dynasties)', 1011);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1012, 1, 'Mughal Empire (Babur to Aurangzeb, administration, art)', 1012);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1013, 1, 'Vijayanagara & Bahmani Kingdoms', 1013);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1014, 1, 'Bhakti & Sufi Movements', 1014);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1015, 1, 'Maratha Empire (Shivaji to Peshwas)', 1015);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1016, 1, 'Advent of Europeans (Portuguese, Dutch, French, British)', 1016);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1017, 1, 'Anglo-Indian Wars (Carnatic, Mysore, Maratha, Sikh Wars)', 1017);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1018, 1, 'British Expansion — Diplomacy & Doctrine of Lapse', 1018);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1019, 1, 'Economic Impact of British Rule (Land Revenue Systems, Deindustrialization)', 1019);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1020, 1, 'Social & Religious Reform Movements (Brahmo Samaj, Arya Samaj, etc.)', 1020);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1021, 1, 'Revolt of 1857 — Causes, Course, Consequences', 1021);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1022, 1, 'Formation & Early Phase of Indian National Congress', 1022);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1023, 1, 'Partition of Bengal & Swadeshi Movement', 1023);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1024, 1, 'Rise of Extremism & Revolutionary Movements', 1024);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1025, 1, 'Home Rule Movement', 1025);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1026, 1, 'Gandhian Era (Non-Cooperation, Civil Disobedience, Quit India)', 1026);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1027, 1, 'Peasant, Worker & Tribal Movements', 1027);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1028, 1, 'Dalit Reform Movements (Ambedkar''s contributions)', 1028);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1029, 1, 'Muslim Reform Movements & Aligarh Movement', 1029);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1030, 1, 'Azad Hind Fauj (Subhas Chandra Bose, INA)', 1030);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1031, 1, 'Independence & Partition of India (1947)', 1031);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1032, 1, 'Integration of Princely States', 1032);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1033, 2, 'Location, Extent & Neighbouring Countries', 1033);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1034, 2, 'Geological Structure & Physiographic Divisions (Himalayas, Plains, Plateau, Coasts, Islands)', 1034);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1035, 2, 'Drainage System (Himalayan & Peninsular Rivers)', 1035);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1036, 2, 'Climate of India (Monsoon mechanism, seasons)', 1036);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1037, 2, 'Soil Types of India', 1037);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1038, 2, 'Natural Vegetation & Forest Types', 1038);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1039, 2, 'Wildlife & Biodiversity Conservation Areas', 1039);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1040, 3, 'Population Census & Demographic Trends', 1040);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1041, 3, 'Population Growth, Density & Distribution', 1041);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1042, 3, 'Birth Rate, Death Rate, Infant Mortality Rate', 1042);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1043, 3, 'Migration Patterns', 1043);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1044, 3, 'Literacy Rate & Occupational Structure', 1044);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1045, 3, 'Urbanization Trends', 1045);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1046, 4, 'Agriculture — Cropping Patterns (Foodgrains, Pulses, Oilseeds, Cash Crops)', 1046);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1047, 4, 'Irrigation Systems & Multipurpose Projects', 1047);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1048, 4, 'Green, White & Blue Revolutions', 1048);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1049, 4, 'Mineral Resources — Distribution & Production', 1049);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1050, 4, 'Energy Resources (Coal, Petroleum, Thermal, Nuclear, Non-conventional)', 1050);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1051, 4, 'Industries — Development, Types & Location Factors', 1051);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1052, 5, 'Constitutional Development (1773–1950 — Regulating Act to Government of India Acts)', 1052);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1053, 5, 'Making of the Constitution (Constituent Assembly)', 1053);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1054, 5, 'Preamble — Features & Significance', 1054);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1055, 5, 'Nature of the Constitution (Federal/Unitary features)', 1055);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1056, 5, 'Fundamental Rights', 1056);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1057, 5, 'Fundamental Duties', 1057);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1058, 5, 'Directive Principles of State Policy', 1058);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1059, 5, 'Constitutional Amendments & Basic Structure Doctrine', 1059);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1060, 5, 'Emergency Provisions (National, State, Financial)', 1060);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1061, 6, 'Union Executive (President, Vice-President, PM, Council of Ministers)', 1061);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1062, 6, 'Union Legislature (Parliament — Lok Sabha, Rajya Sabha)', 1062);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1063, 6, 'Union Judiciary (Supreme Court, Judicial Review, Judicial Activism)', 1063);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1064, 6, 'Attorney General of India', 1064);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1065, 6, 'State Executive (Governor, CM, Council of Ministers)', 1065);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1066, 6, 'State Legislature', 1066);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1067, 6, 'State Judiciary (High Court, Advocate General)', 1067);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1068, 6, 'Centre-State Relations (Legislative, Administrative, Financial)', 1068);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1069, 6, 'All India Services', 1069);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1070, 6, 'UPSC & State Public Service Commissions', 1070);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1071, 6, 'Right to Constitutional Remedies & PILs', 1071);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1072, 6, 'Panchayati Raj & Municipalities (73rd & 74th Amendments)', 1072);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1073, 6, 'Lokpal & Lokayukta', 1073);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1074, 6, 'Right to Information Act', 1074);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1075, 6, 'Election Commission & Electoral Process', 1075);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1076, 6, 'Chhattisgarh''s Administrative/Legislative/Judicial Structure', 1076);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1077, 7, 'National Income & Per Capita Income concepts', 1077);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1078, 7, 'GDP, GNP, Structural Changes in Economy', 1078);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1079, 7, 'Five Year Plans & NITI Aayog', 1079);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1080, 7, 'Economic Reforms (LPG — 1991 reforms)', 1080);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1081, 7, 'Poverty & Unemployment (types, measurement)', 1081);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1082, 7, 'Banking System (RBI, Commercial Banks, NBFCs)', 1082);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1083, 7, 'Monetary Policy & Credit Control', 1083);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1084, 7, 'Public Finance (Revenue, Expenditure, Fiscal Deficit)', 1084);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1085, 7, 'Taxation System (Direct/Indirect, GST)', 1085);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1086, 7, 'Foreign Trade & Balance of Payments', 1086);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1087, 7, 'Inflation & Price Stability', 1087);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1088, 8, 'Physics — Mechanics, Light, Electricity, Modern Physics basics', 1088);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1089, 8, 'Chemistry — Chemical reactions, Metals/Non-metals, Organic compounds', 1089);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1090, 8, 'Biology — Human body systems, Plant physiology, Genetics basics', 1090);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1091, 8, 'Everyday Science Applications', 1091);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1092, 9, 'Basics of Computers & IT', 1092);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1093, 9, 'Role of IT in Rural Development', 1093);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1094, 9, 'Space Technology (ISRO milestones)', 1094);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1095, 9, 'Defence Technology', 1095);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1096, 9, 'Communication Technology', 1096);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1097, 9, 'Biotechnology Applications', 1097);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1098, 9, 'Nuclear Technology & Energy', 1098);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1099, 10, 'Vedic & Upanishadic Thought', 1099);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1100, 10, 'Astika Schools (Nyaya, Vaisheshika, Samkhya, Yoga, Mimamsa, Vedanta)', 1100);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1101, 10, 'Nastika Schools (Charvaka, Jain, Buddhist philosophy)', 1101);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1102, 10, 'Bhagavad Gita''s Philosophy', 1102);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1103, 10, 'Modern Indian Thinkers (Vivekananda, Aurobindo, Gandhi, Ambedkar)', 1103);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1104, 11, 'Classical Dance Forms', 1104);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1105, 11, 'Classical & Folk Music', 1105);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1106, 11, 'Indian Architecture (Temple styles, Indo-Islamic architecture)', 1106);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1107, 11, 'Indian Paintings & Sculpture', 1107);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1108, 11, 'Sangam, Classical & Medieval Literature', 1108);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1109, 11, 'Fairs, Festivals & Religious Traditions', 1109);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1110, 11, 'UNESCO World Heritage Sites in India', 1110);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1111, 11, 'Languages & Literary Academies', 1111);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1112, 12, 'National Events, Policies & Schemes (last 1 year)', 1112);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1113, 12, 'International Relations & Summits', 1113);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1114, 12, 'Government Schemes & Missions', 1114);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1115, 12, 'Awards & Honours', 1115);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1116, 12, 'Appointments (national/international bodies)', 1116);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1117, 12, 'Books & Authors', 1117);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1118, 12, 'Obituaries (notable personalities)', 1118);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1119, 13, 'National & International Tournaments', 1119);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1120, 13, 'Olympics, Commonwealth, Asian Games', 1120);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1121, 13, 'Sports Awards (Khel Ratna, Arjuna, Dronacharya)', 1121);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1122, 13, 'Records & Achievements', 1122);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1123, 13, 'Sports Bodies & Terminology', 1123);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1124, 14, 'Ecosystem & Biodiversity Basics', 1124);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1125, 14, 'Environmental Pollution (Air, Water, Soil, Noise)', 1125);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1126, 14, 'Climate Change & Global Warming', 1126);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1127, 14, 'International Environmental Agreements (Paris Accord, Kyoto Protocol)', 1127);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1128, 14, 'National Environmental Policies & Laws', 1128);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1129, 14, 'Protected Areas — National Parks, Sanctuaries, Biosphere Reserves', 1129);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1130, 14, 'Sustainable Development Goals', 1130);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1131, 15, 'Ancient Period (Vedic to Gupta era in region)', 1131);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1132, 15, 'Major Dynasties — Rajarshitulya Kula, Nala, Sharabhpuriya, Panduvanshi, Somvanshi', 1132);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1133, 15, 'Kalchuri Dynasty & Administration (Ratanpur & Raipur branches)', 1133);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1134, 15, 'Maratha Rule in Chhattisgarh', 1134);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1135, 15, 'British Protectorate Period', 1135);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1136, 15, 'Former Princely States & Zamindaris of Chhattisgarh', 1136);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1137, 15, 'Feudal Administration System', 1137);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1138, 16, 'Revolt of 1857 in Chhattisgarh (Narayan Singh, etc.)', 1138);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1139, 16, 'Local Freedom Fighters & Movements', 1139);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1140, 16, 'Formation of Chhattisgarh as Separate State (2000) — background', 1140);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1141, 17, 'Location, Extent & Boundary', 1141);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1142, 17, 'Geological Structure & Physical Divisions', 1142);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1143, 17, 'Drainage System (Mahanadi, Shivnath, Indravati basins)', 1143);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1144, 17, 'Climate & Rainfall Pattern', 1144);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1145, 17, 'Soil Types', 1145);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1146, 18, 'Population Growth, Density, Distribution', 1146);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1147, 18, 'Birth/Death/Infant Mortality Rates', 1147);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1148, 18, 'Sex Ratio & Age Groups', 1148);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1149, 18, 'Migration', 1149);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1150, 18, 'Scheduled Tribe Population Data', 1150);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1151, 18, 'Literacy & Occupational Structure', 1151);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1152, 18, 'Urbanization', 1152);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1153, 18, 'Family Welfare Programmes', 1153);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1154, 19, 'Archaeological Sites & Excavated Places (Sirpur, Malhar, etc.)', 1154);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1155, 19, 'Protected Monuments', 1155);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1156, 19, 'Tourist Destinations (notified by CG Govt.)', 1156);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1157, 19, 'Waterfalls & Caves (esp. Bastar region)', 1157);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1158, 19, 'National Parks & Wildlife Sanctuaries', 1158);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1159, 20, 'History & Development of Chhattisgarhi Literature', 1159);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1160, 20, 'Major Litterateurs & Their Works', 1160);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1161, 20, 'Literary Institutions of the State', 1161);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1162, 21, 'Folk Music of Chhattisgarh', 1162);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1163, 21, 'Folk Dance Forms', 1163);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1164, 21, 'Folk Theatre', 1164);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1165, 21, 'Folk Art traditions', 1165);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1166, 21, 'State-established Cultural Institutions', 1166);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1167, 21, 'State Awards/Honours in Literature, Music, Fine Arts', 1167);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1168, 22, 'जनऊला (Riddles)', 1168);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1169, 22, 'मुहावरे (Idioms)', 1169);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1170, 22, 'हाना (Sayings)', 1170);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1171, 22, 'लोकोक्तियाँ (Proverbs)', 1171);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1172, 22, 'Vocabulary & Grammar basics (word formation, prefixes/suffixes)', 1172);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1173, 23, 'Special Primitive/Particularly Vulnerable Tribal Groups (PVTGs)', 1173);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1174, 23, 'Major & Minor Tribes', 1174);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1175, 23, 'Tribal Social Organization (Marriage, Family, Clan, Youth Dormitories/Ghotul)', 1175);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1176, 23, 'Ornaments & Traditional Attire of Tribes', 1176);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1177, 23, 'Tribal Development History, Programmes & Constitutional Provisions', 1177);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1178, 23, 'Tribal Problems — Isolation, Migration, Acculturation', 1178);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1179, 23, 'Scheduled Castes & Other Backward Classes of Chhattisgarh', 1179);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1180, 24, 'Major Fairs (Melas) of Chhattisgarh', 1180);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1181, 24, 'Religious & Seasonal Festivals', 1181);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1182, 24, 'Tribal Festivals & Rituals', 1182);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1183, 24, 'Prominent Saints of Chhattisgarh (Guru Ghasidas, etc.)', 1183);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1184, 25, 'State Income & Economic Indicators', 1184);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1185, 25, 'Socio-economic Backwardness of SC/ST/OBC/Minorities', 1185);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1186, 25, 'Employment & Income Distribution trends', 1186);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1187, 25, 'Women''s Socio-Political-Economic Empowerment', 1187);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1188, 25, 'Child Labour Issues', 1188);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1189, 25, 'Rural Development Programmes', 1189);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1190, 25, 'State Finance — Budget, Tax Structure, Central Tax Share', 1190);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1191, 25, 'Public Debt Composition', 1191);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1192, 25, 'Rural Credit — Institutional/Non-institutional sources', 1192);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1193, 25, 'Co-operative Sector — Structure & Growth', 1193);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1194, 26, 'Major Crops (Foodgrains, Pulses, Oilseeds)', 1194);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1195, 26, 'Production & Distribution of Crops', 1195);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1196, 26, 'Irrigation Projects in Chhattisgarh', 1196);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1197, 26, 'Problems of Agriculture & State Schemes for Farmers', 1197);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1198, 26, 'Forest Cover & Forest Types', 1198);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1199, 26, 'Forest Policy & Conservation', 1199);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1200, 26, 'Wildlife Management (Parks & Sanctuaries)', 1200);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1201, 27, 'State Executive, Legislature, Judiciary', 1201);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1202, 27, 'District Administration Setup', 1202);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1203, 27, 'Revenue Administration', 1203);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1204, 28, 'Panchayati Raj Institutions in CG', 1204);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1205, 28, 'Urban Local Bodies (Municipal structure)', 1205);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1206, 28, '73rd/74th Amendment implementation in state context', 1206);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1207, 29, 'Mineral Resources — Types, Reserves, Production, Distribution', 1207);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1208, 29, 'Energy Resources (Coal, Thermal Power, Non-conventional sources)', 1208);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1209, 29, 'Industrial Development & Structure (Large, Medium, Small scale)', 1209);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1210, 29, 'Agriculture, Forest & Mineral-based Industries', 1210);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1211, 29, 'Means of Transport in Chhattisgarh', 1211);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1212, 30, 'Recent State Government Schemes & Policies', 1212);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1213, 30, 'Recent Appointments & Awards (state level)', 1213);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1214, 30, 'State Government Initiatives (last 1 year)', 1214);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1215, 30, 'Recent Infrastructure/Development Projects', 1215);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1216, 31, 'Comprehension-based reasoning', 1216);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1217, 31, 'Effective communication concepts', 1217);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1218, 32, 'Analogy / Similarity-based questions', 1218);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1219, 32, 'Odd One Out (word/number)', 1219);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1220, 32, 'Odd Pair of Words', 1220);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1221, 32, 'Coding-Decoding', 1221);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1222, 32, 'Blood Relations', 1222);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1223, 32, 'Alphabet Test', 1223);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1224, 32, 'Series Completion (Number/Figure/Letter)', 1224);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1225, 32, 'Statement & Assertion-Reason', 1225);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1226, 32, 'Situation Reaction Test', 1226);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1227, 32, 'Missing Number/Word Insertion', 1227);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1228, 33, 'Logical analysis of words', 1228);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1229, 33, 'Data sufficiency', 1229);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1230, 33, 'Pattern recognition', 1230);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1231, 34, 'Case-based decision scenarios', 1231);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1232, 34, 'Problem-solving techniques', 1232);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1233, 35, 'Puzzles', 1233);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1234, 35, 'Visual/figure reasoning', 1234);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1235, 36, 'Number Systems & Basic Arithmetic Operations', 1235);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1236, 36, 'Ratio & Proportion', 1236);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1237, 36, 'Percentage, Profit & Loss', 1237);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1238, 36, 'Simple & Compound Interest', 1238);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1239, 36, 'Time, Speed & Distance (incl. boats & streams)', 1239);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1240, 36, 'Averages', 1240);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1241, 36, 'LCM & HCF, Factorization', 1241);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1242, 36, 'Vedic Mathematics techniques (Squares, Cubes, Roots)', 1242);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1243, 36, 'Banking Calculations (Savings, FD, RD interest)', 1243);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1244, 36, 'Income Tax Calculation basics', 1244);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1245, 36, 'Indian Mathematicians (Aryabhata, Brahmagupta, Bhaskaracharya, Ramanujan)', 1245);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1246, 37, 'Charts & Graphs', 1246);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1247, 37, 'Tables', 1247);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1248, 37, 'Data Sufficiency', 1248);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1249, 37, 'Statistical Measures (Mean, Median, Mode)', 1249);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1250, 37, 'Probability (basic theorems)', 1250);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1251, 38, 'Grammar basics', 1251);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1252, 38, 'Comprehension', 1252);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1253, 39, 'Basic vocabulary & comprehension', 1253);
INSERT INTO topics (id, subject_id, name, sort_order) VALUES (1254, 39, 'Common usage', 1254);
