const fs = require('fs');
const path = require('path');

const csvData = `"Q(EN)","Q(HI)","OptA(EN)","OptA(HI)","OptB(EN)","OptB(HI)","OptC(EN)","OptC(HI)","OptD(EN)","OptD(HI)","Correct(1-4)","Exp(EN)","Exp(HI)"
"Consider the following statements regarding Guru Ghasidas National Park:\\n\\n1. It is the largest national park in Chhattisgarh with an area of approximately 1441 sq. km.\\n2. It was established in 1981 and its former name was Sanjay National Park.\\n3. It is primarily spread across the Bastar and Kondagaon districts.\\n\\nWhich of the statement(s) given above is/are correct?","गुरु घासीदास राष्ट्रीय उद्यान के संबंध में निम्नलिखित कथनों पर विचार करें:\\n\\n1. यह लगभग 1441 वर्ग किमी क्षेत्रफल के साथ छत्तीसगढ़ का सबसे बड़ा राष्ट्रीय उद्यान है।\\n2. इसकी स्थापना 1981 में हुई थी और इसका पूर्व नाम संजय राष्ट्रीय उद्यान था।\\n3. यह मुख्य रूप से बस्तर और कोंडागांव जिलों में फैला हुआ है।\\n\\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3","1","Statements 1 and 2 are perfectly correct. Statement 3 is incorrect because Guru Ghasidas National Park is located in the northern part of the state, spanning across Koriya, Manendragarh-Chirmiri-Bharatpur (MCB), and Surajpur districts.","कथन 1 और 2 बिल्कुल सही हैं। कथन 3 गलत है क्योंकि गुरु घासीदास राष्ट्रीय उद्यान राज्य के उत्तरी भाग में कोरिया, मनेंद्रगढ़-चिरमिरी-भरतपुर (MCB) और सूरजपुर जिलों में फैला हुआ है।"
"Match the National Parks of Chhattisgarh with their year of establishment:\\n\\nList-I (National Park)\\n(a) Indravati\\n(b) Guru Ghasidas\\n(c) Kanger Valley\\n\\nList-II (Year)\\n(i) 1981\\n(ii) 1982\\n(iii) 1978\\n\\nCodes:","छत्तीसगढ़ के राष्ट्रीय उद्यानों को उनकी स्थापना के वर्ष के साथ सुमेलित करें:\\n\\nसूची-I (राष्ट्रीय उद्यान)\\n(a) इंद्रावती\\n(b) गुरु घासीदास\\n(c) कांगेर घाटी\\n\\nसूची-II (वर्ष)\\n(i) 1981\\n(ii) 1982\\n(iii) 1978\\n\\nकूट:","(a)-(iii), (b)-(i), (c)-(ii)","(a)-(iii), (b)-(i), (c)-(ii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(iii), (b)-(ii), (c)-(i)","(a)-(iii), (b)-(ii), (c)-(i)","(a)-(ii), (b)-(i), (c)-(iii)","(a)-(ii), (b)-(i), (c)-(iii)","1","Indravati was the first National Park established in 1978. Guru Ghasidas was established in 1981. Kanger Valley, the smallest, was established in 1982.","इंद्रावती पहला राष्ट्रीय उद्यान था जिसकी स्थापना 1978 में हुई थी। गुरु घासीदास की स्थापना 1981 में हुई थी। कांगेर घाटी, जो सबसे छोटा है, की स्थापना 1982 में हुई थी।"
"Which is the only 'Game Sanctuary' in Chhattisgarh, and within which National Park is it situated?","छत्तीसगढ़ का एकमात्र 'गेम सेंचुरी' (Game Sanctuary) कौन सा है, और यह किस राष्ट्रीय उद्यान के भीतर स्थित है?","Kutru Game Sanctuary, Indravati National Park","कुटरू गेम सेंचुरी, इंद्रावती राष्ट्रीय उद्यान","Koleng Game Sanctuary, Kanger Valley National Park","कोलेंग गेम सेंचुरी, कांगेर घाटी राष्ट्रीय उद्यान","Sonhat Game Sanctuary, Guru Ghasidas National Park","सोनहत गेम सेंचुरी, गुरु घासीदास राष्ट्रीय उद्यान","Pamed Game Sanctuary, Indravati National Park","पामेड़ गेम सेंचुरी, इंद्रावती राष्ट्रीय उद्यान","1","The Kutru Game Sanctuary is the only game sanctuary in the state, and it is located within the Indravati National Park in the Bijapur district.","कुटरू गेम सेंचुरी राज्य का एकमात्र गेम अभयारण्य है, और यह बीजापुर जिले में इंद्रावती राष्ट्रीय उद्यान के भीतर स्थित है।"
"Assertion (A): Kanger Valley National Park was declared Asia's first Biosphere Reserve in 1982.\\n\\nReason (R): It holds this Biosphere Reserve status currently and is recognized globally by UNESCO.\\n\\nCodes:","कथन (A): कांगेर घाटी राष्ट्रीय उद्यान को 1982 में एशिया का पहला बायोस्फीयर रिजर्व घोषित किया गया था।\\n\\nकारण (R): यह वर्तमान में इस बायोस्फीयर रिजर्व का दर्जा रखता है और यूनेस्को द्वारा विश्व स्तर पर मान्यता प्राप्त है।\\n\\nकूट:","Both (A) and (R) are true and (R) is the correct explanation of (A)","(A) और (R) दोनों सही हैं और (R), (A) का सही स्पष्टीकरण है","Both (A) and (R) are true but (R) is NOT the correct explanation of (A)","(A) और (R) दोनों सही हैं लेकिन (R), (A) का सही स्पष्टीकरण नहीं है","(A) is true but (R) is false","(A) सही है लेकिन (R) गलत है","(A) is false but (R) is true","(A) गलत है लेकिन (R) सही है","3","The assertion is true as it was declared Asia's first Biosphere Reserve between 1982-1985. However, the reason is false because it currently does NOT hold this status. The only active Biosphere Reserve in the state is Achanakmar-Amarkantak.","कथन सत्य है क्योंकि इसे 1982-1985 के बीच एशिया का पहला बायोस्फीयर रिजर्व घोषित किया गया था। हालाँकि, कारण गलत है क्योंकि वर्तमान में इसे यह दर्जा प्राप्त नहीं है। राज्य में एकमात्र सक्रिय बायोस्फीयर रिजर्व अचानकमार-अमरकंटक है।"
"The state bird of Chhattisgarh, the 'Pahari Myna' (Hill Myna), is primarily conserved in which of the following National Parks?","छत्तीसगढ़ के राज्य पक्षी 'पहाड़ी मैना' (Hill Myna) का संरक्षण मुख्य रूप से निम्नलिखित में से किस राष्ट्रीय उद्यान में किया जाता है?","Guru Ghasidas National Park","गुरु घासीदास राष्ट्रीय उद्यान","Kanger Valley National Park","कांगेर घाटी राष्ट्रीय उद्यान","Indravati National Park","इंद्रावती राष्ट्रीय उद्यान","Kanger Valley and Indravati National Parks both","कांगेर घाटी और इंद्रावती राष्ट्रीय उद्यान दोनों","2","The Kanger Valley National Park in Bastar is specifically renowned for the conservation of the human-voice-mimicking Pahari Myna, the state bird of Chhattisgarh.","बस्तर में कांगेर घाटी राष्ट्रीय उद्यान विशेष रूप से मानव-आवाज की नकल करने वाली पहाड़ी मैना (छत्तीसगढ़ का राज्य पक्षी) के संरक्षण के लिए प्रसिद्ध है।"
"Which among the following National Parks of Chhattisgarh was the first to be included in 'Project Tiger' in 1983?","छत्तीसगढ़ के निम्नलिखित राष्ट्रीय उद्यानों में से किसे 1983 में सबसे पहले 'प्रोजेक्ट टाइगर' में शामिल किया गया था?","Kanger Valley National Park","कांगेर घाटी राष्ट्रीय उद्यान","Sitanadi National Park","सीतानदी राष्ट्रीय उद्यान","Guru Ghasidas National Park","गुरु घासीदास राष्ट्रीय उद्यान","Indravati National Park","इंद्रावती राष्ट्रीय उद्यान","4","Indravati National Park was the state's first National Park (1978) and the first to be included in Project Tiger in 1983. It later gained Tiger Reserve status in 2009.","इंद्रावती राष्ट्रीय उद्यान राज्य का पहला राष्ट्रीय उद्यान (1978) था और 1983 में प्रोजेक्ट टाइगर में शामिल होने वाला पहला उद्यान था। बाद में 2009 में इसे टाइगर रिजर्व का दर्जा मिला।"
"Which of the following caves is NOT located within the Kanger Valley National Park?","निम्नलिखित में से कौन सी गुफा कांगेर घाटी राष्ट्रीय उद्यान के भीतर स्थित नहीं है?","Kutumsar Cave","कुटुमसर गुफा","Kailash Cave","कैलाश गुफा","Dandak Cave","दंडक गुफा","Sita Bengra Cave","सीता बेंगरा गुफा","4","Sita Bengra and Jogimara caves are located in the Ramgarh hills of the Surguja district. Kutumsar, Kailash, and Dandak caves are integral parts of the Kanger Valley National Park in Bastar.","सीता बेंगरा और जोगीमारा गुफाएं सरगुजा जिले की रामगढ़ पहाड़ियों में स्थित हैं। कुटुमसर, कैलाश और दंडक गुफाएं बस्तर में कांगेर घाटी राष्ट्रीय उद्यान का अभिन्न अंग हैं।"
"With reference to the geographical extent of National Parks, which one of the following is correctly matched with its total area?","राष्ट्रीय उद्यानों के भौगोलिक विस्तार के संदर्भ में, निम्नलिखित में से कौन सा अपने कुल क्षेत्रफल के साथ सही सुमेलित है?","Indravati National Park - 200 sq. km.","इंद्रावती राष्ट्रीय उद्यान - 200 वर्ग किमी।","Kanger Valley National Park - 1441 sq. km.","कांगेर घाटी राष्ट्रीय उद्यान - 1441 वर्ग किमी।","Guru Ghasidas National Park - 1441 sq. km.","गुरु घासीदास राष्ट्रीय उद्यान - 1441 वर्ग किमी।","Indravati National Park - 559 sq. km.","इंद्रावती राष्ट्रीय उद्यान - 559 वर्ग किमी।","3","Guru Ghasidas National Park is the largest with approximately 1441 sq. km. Indravati covers 1258 sq. km, and Kanger Valley is the smallest at 200 sq. km.","गुरु घासीदास राष्ट्रीय उद्यान लगभग 1441 वर्ग किमी के साथ सबसे बड़ा है। इंद्रावती 1258 वर्ग किमी को कवर करता है, और कांगेर घाटी 200 वर्ग किमी पर सबसे छोटा है।"
"The Neelkanth and Chul waterfalls are significant tourist attractions located within which protected area?","नीलकंठ और चूल जलप्रपात किस संरक्षित क्षेत्र के भीतर स्थित महत्वपूर्ण पर्यटक आकर्षण हैं?","Indravati National Park","इंद्रावती राष्ट्रीय उद्यान","Guru Ghasidas National Park","गुरु घासीदास राष्ट्रीय उद्यान","Achanakmar Wildlife Sanctuary","अचानकमार वन्यजीव अभयारण्य","Kanger Valley National Park","कांगेर घाटी राष्ट्रीय उद्यान","2","The Neelkanth and Chul waterfalls are located inside the Guru Ghasidas National Park, alongside other attractions like the Aamapani and Gaangirani caves.","नीलकंठ और चूल जलप्रपात गुरु घासीदास राष्ट्रीय उद्यान के अंदर स्थित हैं, साथ ही यहाँ आमापानी और गांगीरानी गुफाएं जैसे अन्य आकर्षण भी हैं।"
"Which river forms the natural northern boundary of the Indravati National Park, separating it from the state of Maharashtra?","कौन सी नदी इंद्रावती राष्ट्रीय उद्यान की प्राकृतिक उत्तरी सीमा बनाती है, जो इसे महाराष्ट्र राज्य से अलग करती है?","Godavari River","गोदावरी नदी","Indravati River","इंद्रावती नदी","Sabari River","शबरी नदी","Kotri River","कोटरी नदी","2","The Indravati River flows from east to west through the park and forms the northern boundary of the reserve with the Indian state of Maharashtra.","इंद्रावती नदी पार्क के माध्यम से पूर्व से पश्चिम की ओर बहती है और महाराष्ट्र राज्य के साथ रिजर्व की उत्तरी सीमा बनाती है।"
"Match the following Wildlife Sanctuaries (Abhyaranya) with their respective districts:\\n\\nList-I\\n(a) Gomardah\\n(b) Barnawapara\\n(c) Semarsot\\n(d) Pamed\\n\\nList-II\\n(i) Balrampur\\n(ii) Sarangarh-Bilaigarh\\n(iii) Bijapur\\n(iv) Balodabazar-Mahasamund\\n\\nCodes:","निम्नलिखित वन्यजीव अभयारण्यों को उनके संबंधित जिलों के साथ सुमेलित करें:\\n\\nसूची-I\\n(a) गोमर्डा\\n(b) बारनवापारा\\n(c) सेमरसोत\\n(d) पामेड़\\n\\nसूची-II\\n(i) बलरामपुर\\n(ii) सारंगढ़-बिलाईगढ़\\n(iii) बीजापुर\\n(iv) बलौदाबाजार-महासमुंद\\n\\nकूट:","(a)-(ii), (b)-(iv), (c)-(i), (d)-(iii)","(a)-(ii), (b)-(iv), (c)-(i), (d)-(iii)","(a)-(ii), (b)-(iv), (c)-(iii), (d)-(i)","(a)-(ii), (b)-(iv), (c)-(iii), (d)-(i)","(a)-(iv), (b)-(ii), (c)-(i), (d)-(iii)","(a)-(iv), (b)-(ii), (c)-(i), (d)-(iii)","(a)-(i), (b)-(ii), (c)-(iv), (d)-(iii)","(a)-(i), (b)-(ii), (c)-(iv), (d)-(iii)","1","Gomardah is in Sarangarh-Bilaigarh (formerly Raigarh). Barnawapara spans Balodabazar-Mahasamund. Semarsot is in Balrampur. Pamed is in Bijapur.","गोमर्डा सारंगढ़-बिलाईगढ़ (पूर्व में रायगढ़) में है। बारनवापारा बलौदाबाजार-महासमुंद में फैला है। सेमरसोत बलरामपुर में है। पामेड़ बीजापुर में है।"
"Arrange the following Wildlife Sanctuaries in chronological order of their establishment (oldest to newest):\\n\\n1. Bhoramdeo\\n2. Sitanadi\\n3. Udanti\\n4. Achanakmar\\n\\nChoose the correct code:","निम्नलिखित वन्यजीव अभयारण्यों को उनकी स्थापना के कालानुक्रमिक क्रम (सबसे पुराने से नवीनतम) में व्यवस्थित करें:\\n\\n1. भोरमदेव\\n2. सीतानदी\\n3. उदंती\\n4. अचानकमार\\n\\nसही कूट चुनें:","2, 4, 3, 1","2, 4, 3, 1","2, 3, 4, 1","2, 3, 4, 1","4, 2, 3, 1","4, 2, 3, 1","2, 4, 1, 3","2, 4, 1, 3","1","Sitanadi is the oldest (1974). Achanakmar was established in 1975. Udanti was established in 1983. Bhoramdeo is the newest (2001). Thus, 2, 4, 3, 1.","सीतानदी सबसे पुराना (1974) है। अचानकमार की स्थापना 1975 में हुई थी। उदंती 1983 में स्थापित हुआ। भोरमदेव सबसे नया (2001) है। इस प्रकार, 2, 4, 3, 1।"
"Consider the following statements regarding the Wildlife Sanctuaries of Chhattisgarh:\\n\\n1. Tamor Pingla is the largest sanctuary with an area of 608 sq. km.\\n2. Badalkhol is the smallest sanctuary with an area of 105 sq. km.\\n3. Badalkhol sanctuary is located in the Surajpur district.\\n\\nWhich of the statement(s) given above is/are correct?","छत्तीसगढ़ के वन्यजीव अभयारण्यों के संबंध में निम्नलिखित कथनों पर विचार करें:\\n\\n1. तमोर पिंगला 608 वर्ग किमी क्षेत्रफल के साथ सबसे बड़ा अभयारण्य है।\\n2. बादलखोल 105 वर्ग किमी क्षेत्रफल के साथ सबसे छोटा अभयारण्य है।\\n3. बादलखोल अभयारण्य सूरजपुर जिले में स्थित है।\\n\\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3","1","Statements 1 and 2 are correct. Statement 3 is a common trap; Badalkhol is located in the Jashpur district, whereas Tamor Pingla is in the Surajpur district.","कथन 1 और 2 सही हैं। कथन 3 एक सामान्य ट्रैप है; बादलखोल जशपुर जिले में स्थित है, जबकि तमोर पिंगला सूरजपुर जिले में है।"
"The 'Son Kutta' (Wild Dog or Dhole) is the primary wildlife species protected and famously sighted in which of the following sanctuaries?","'सोन कुत्ता' (जंगली कुत्ता या ढोल) प्राथमिक वन्यजीव प्रजाति है जो मुख्य रूप से किस अभयारण्य में संरक्षित है और देखी जाती है?","Sitanadi Sanctuary","सीतानदी अभयारण्य","Gomardah Sanctuary","गोमर्डा अभयारण्य","Semarsot Sanctuary","सेमरसोत अभयारण्य","Bhairamgarh Sanctuary","भैरमगढ़ अभयारण्य","2","The Gomardah Wildlife Sanctuary, located in the Sarangarh-Bilaigarh district, is specifically famous for the presence of the Indian Wild Dog, locally known as 'Son Kutta'.","सारंगढ़-बिलाईगढ़ जिले में स्थित गोमर्डा वन्यजीव अभयारण्य विशेष रूप से भारतीय जंगली कुत्ते, जिसे स्थानीय रूप से 'सोन कुत्ता' के रूप में जाना जाता है, की उपस्थिति के लिए प्रसिद्ध है।"
"Which of the following sanctuaries in the Bijapur district were established in 1983 primarily for the conservation of the endangered Wild Buffalo (Van Bhainsa)?","बीजापुर जिले में निम्नलिखित में से कौन सा अभयारण्य 1983 में मुख्य रूप से लुप्तप्राय वन भैंसे (Wild Buffalo) के संरक्षण के लिए स्थापित किया गया था?","Pamed and Bhairamgarh","पामेड़ और भैरमगढ़","Udanti and Sitanadi","उदंती और सीतानदी","Badalkhol and Semarsot","बादलखोल और सेमरसोत","Gomardah and Pamed","गोमर्डा और पामेड़","1","Pamed and Bhairamgarh sanctuaries, both located in the Bijapur district and established in 1983, serve specifically as protection areas for the state animal, the Wild Buffalo. (Udanti is in Gariaband).","बीजापुर जिले में स्थित पामेड़ और भैरमगढ़ अभयारण्य, दोनों 1983 में स्थापित किए गए थे, जो विशेष रूप से राज्य पशु वन भैंसे के संरक्षण क्षेत्र के रूप में कार्य करते हैं। (उदंती गरियाबंद में है)।"
"Assertion (A): The Balamdehi river flows through the Barnawapara Wildlife Sanctuary.\\n\\nReason (R): The famous Devdhara waterfall and the historical Turturiya Ashram are located on the banks of the Balamdehi river within this sanctuary.\\n\\nCodes:","कथन (A): बालमदेही नदी बारनवापारा वन्यजीव अभयारण्य से होकर बहती है।\\n\\nकारण (R): प्रसिद्ध देवधारा जलप्रपात और ऐतिहासिक तुरतुरिया आश्रम इस अभयारण्य के भीतर बालमदेही नदी के तट पर स्थित हैं।\\n\\nकूट:","Both (A) and (R) are true and (R) is the correct explanation of (A)","(A) और (R) दोनों सही हैं और (R), (A) का सही स्पष्टीकरण है","Both (A) and (R) are true but (R) is NOT the correct explanation of (A)","(A) और (R) दोनों सही हैं लेकिन (R), (A) का सही स्पष्टीकरण नहीं है","(A) is true but (R) is false","(A) सही है लेकिन (R) गलत है","(A) is false but (R) is true","(A) गलत है लेकिन (R) सही है","2","Both statements are true. However, the reason merely states facts about the river's geography and attractions; it does not logically 'explain' why the river flows through the sanctuary.","दोनों कथन सत्य हैं। हालाँकि, कारण केवल नदी के भूगोल और आकर्षण के बारे में तथ्य बताता है; यह तार्किक रूप से यह 'स्पष्ट' नहीं करता है कि नदी अभयारण्य से क्यों बहती है।"
"Through which of the following Wildlife Sanctuaries does the Tropic of Cancer (Kark Rekha) pass?","निम्नलिखित में से किस वन्यजीव अभयारण्य से कर्क रेखा (Tropic of Cancer) गुजरती है?","Tamor Pingla Sanctuary","तमोर पिंगला अभयारण्य","Achanakmar Sanctuary","अचानकमार अभयारण्य","Semarsot Sanctuary","सेमरसोत अभयारण्य","Bhoramdeo Sanctuary","भोरमदेव अभयारण्य","3","The Semarsot Wildlife Sanctuary is situated in the Balrampur district. Geographically, the Tropic of Cancer passes through this northern sanctuary from east to west.","सेमरसोत वन्यजीव अभयारण्य बलरामपुर जिले में स्थित है। भौगोलिक दृष्टि से, कर्क रेखा इस उत्तरी अभयारण्य से पूर्व से पश्चिम की ओर गुजरती है।"
"Which newly established sanctuary is located near the Maikal ranges and is the ONLY sanctuary created after the formation of the Chhattisgarh state?","कौन सा नव स्थापित अभयारण्य मैकल पर्वतमाला के पास स्थित है और छत्तीसगढ़ राज्य के गठन के बाद बनाया गया एकमात्र अभयारण्य है?","Bhoramdeo Sanctuary","भोरमदेव अभयारण्य","Pamed Sanctuary","पामेड़ अभयारण्य","Udanti Sanctuary","उदंती अभयारण्य","Badalkhol Sanctuary","बादलखोल अभयारण्य","1","Bhoramdeo Sanctuary (established in 2001 in Kabirdham) is the newest sanctuary and the only one established after Chhattisgarh became a separate state in 2000.","भोरमदेव अभयारण्य (कबीरधाम में 2001 में स्थापित) सबसे नया अभयारण्य है और 2000 में छत्तीसगढ़ के एक अलग राज्य बनने के बाद स्थापित किया गया एकमात्र अभयारण्य है।"
"In 2009, three protected areas in Chhattisgarh were officially upgraded to 'Tiger Reserve' status. Which of the following was NOT among those three?","2009 में, छत्तीसगढ़ में तीन संरक्षित क्षेत्रों को आधिकारिक तौर पर 'टाइगर रिजर्व' का दर्जा दिया गया था। निम्नलिखित में से कौन सा उन तीनों में शामिल नहीं था?","Indravati","इंद्रावती","Achanakmar","अचानकमार","Sitanadi-Udanti","सीतानदी-उदंती","Guru Ghasidas-Tamor Pingla","गुरु घासीदास-तमोर पिंगला","4","In 2009, Indravati, Achanakmar, and Sitanadi-Udanti were declared Tiger Reserves. Guru Ghasidas-Tamor Pingla was officially notified much later (in 2024) as the 4th Tiger Reserve of the state.","2009 में इंद्रावती, अचानकमार और सीतानदी-उदंती को टाइगर रिजर्व घोषित किया गया था। गुरु घासीदास-तमोर पिंगला को बहुत बाद में (2024 में) राज्य के चौथे टाइगर रिजर्व के रूप में आधिकारिक तौर पर अधिसूचित किया गया।"
"Identify the INCORRECT pair regarding the Wildlife Sanctuary and its defining characteristic:","वन्यजीव अभयारण्य और उसकी परिभाषित विशेषता के संबंध में गलत युग्म की पहचान करें:","Sitanadi - Oldest Sanctuary","सीतानदी - सबसे पुराना अभयारण्य","Badalkhol - Smallest Sanctuary","बादलखोल - सबसे छोटा अभयारण्य","Tamor Pingla - Largest Sanctuary","तमोर पिंगला - सबसे बड़ा अभयारण्य","Barnawapara - Highest Tiger Population","बारनवापारा - सर्वाधिक बाघों की आबादी","4","Barnawapara is famous for its high snake population (and herbivores). Achanakmar historically holds the highest tiger population among the state's sanctuaries/reserves.","बारनवापारा अपनी उच्च सांपों की आबादी (और शाकाहारी जीवों) के लिए प्रसिद्ध है। अचानकमार में ऐतिहासिक रूप से राज्य के अभयारण्यों/रिजर्व में बाघों की सर्वाधिक आबादी है।"
"The 'Deepasha Project' (Asha Deep), initiated by the state government, is aimed at the specialized breeding and conservation of which animal?","राज्य सरकार द्वारा शुरू की गई 'दीपाशा परियोजना' (आशा दीप) का उद्देश्य किस जानवर का विशेष प्रजनन और संरक्षण है?","Pahari Myna (Hill Myna)","पहाड़ी मैना","Tiger (Bagh)","बाघ","Wild Buffalo (Van Bhainsa)","वन भैंसा","Elephant (Hathi)","हाथी","3","The Deepasha (or Asha Deep) project was started in the Udanti Sanctuary for the conservation and artificial insemination of the highly endangered Wild Buffalo (Van Bhainsa).","दीपाशा (या आशा दीप) परियोजना की शुरुआत उदंती अभयारण्य में अत्यधिक लुप्तप्राय वन भैंसों के संरक्षण और कृत्रिम गर्भाधान के लिए की गई थी।"
"If you are visiting the natural habitat of the Wild Buffalo (Van Bhainsa) and enjoying the scenic Godna Waterfall, which Wildlife Sanctuary are you in?","यदि आप वन भैंसे के प्राकृतिक आवास का दौरा कर रहे हैं और सुंदर गोदना जलप्रपात का आनंद ले रहे हैं, तो आप किस वन्यजीव अभयारण्य में हैं?","Sitanadi Sanctuary","सीतानदी अभयारण्य","Udanti Sanctuary","उदंती अभयारण्य","Bhairamgarh Sanctuary","भैरमगढ़ अभयारण्य","Pamed Sanctuary","पामेड़ अभयारण्य","2","The Udanti Wildlife Sanctuary in Gariaband district is famous for Wild Buffaloes and features the Godna Waterfall formed by the Udanti river.","गरियाबंद जिले में उदंती वन्यजीव अभयारण्य वन भैंसों के लिए प्रसिद्ध है और यहाँ उदंती नदी द्वारा निर्मित गोदना जलप्रपात है।"
"According to the official Wildlife census and conservation reports, 'Bhainsadarha' and 'Jatloor' are natural conservation centers for which reptile?","आधिकारिक वन्यजीव गणना और संरक्षण रिपोर्टों के अनुसार, 'भैंसादरहा' और 'जाटलूर' किस सरीसृप (Reptile) के लिए प्राकृतिक संरक्षण केंद्र हैं?","Indian Python","भारतीय अजगर","Freshwater Crocodile","मीठे पानी का मगरमच्छ","King Cobra","किंग कोबरा","Monitor Lizard","मॉनिटर छिपकली","2","Bhainsadarha (on Kanger river in Bastar) and Jatloor (on Jatloor river in Narayanpur) are natural conservation centers for Crocodiles in Chhattisgarh. Kotmi Sonar is artificial.","भैंसादरहा (बस्तर में कांगेर नदी पर) और जाटलूर (नारायणपुर में जाटलूर नदी पर) छत्तीसगढ़ में मगरमच्छों के प्राकृतिक संरक्षण केंद्र हैं। कोटमी सोनार कृत्रिम है।"
"Which of the following sanctuaries is structurally considered a 'Tiger Corridor' linking the Kanha Tiger Reserve (MP) and the Achanakmar Tiger Reserve?","निम्नलिखित में से किस अभयारण्य को संरचनात्मक रूप से कान्हा टाइगर रिजर्व (MP) और अचानकमार टाइगर रिजर्व को जोड़ने वाला 'टाइगर कॉरिडोर' माना जाता है?","Bhoramdeo Sanctuary","भोरमदेव अभयारण्य","Barnawapara Sanctuary","बारनवापारा अभयारण्य","Semarsot Sanctuary","सेमरसोत अभयारण्य","Gomardah Sanctuary","गोमर्डा अभयारण्य","1","The Bhoramdeo Wildlife Sanctuary (Kabirdham district) in the Maikal hills acts as a critical tiger corridor connecting the Kanha Tiger Reserve to Achanakmar.","मैकल पहाड़ियों में भोरमदेव वन्यजीव अभयारण्य (कबीरधाम जिला) कान्हा टाइगर रिजर्व को अचानकमार से जोड़ने वाले एक महत्वपूर्ण टाइगर कॉरिडोर के रूप में कार्य करता है।"
"Match the following conservation projects with their establishment/announcement years:\\n\\nList-I\\n(a) Elephant Project (Gajraj)\\n(b) Jamvant Project (Bear)\\n(c) Lemru Elephant Reserve\\n\\nList-II\\n(i) 2014\\n(ii) 2011\\n(iii) 2019\\n\\nCodes:","निम्नलिखित संरक्षण परियोजनाओं को उनके स्थापना/घोषणा वर्षों के साथ सुमेलित करें:\\n\\nसूची-I\\n(a) हाथी परियोजना (गजराज)\\n(b) जामवंत परियोजना (भालू)\\n(c) लेमरू हाथी रिजर्व\\n\\nसूची-II\\n(i) 2014\\n(ii) 2011\\n(iii) 2019\\n\\nकूट:","(a)-(ii), (b)-(i), (c)-(iii)","(a)-(ii), (b)-(i), (c)-(iii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(ii), (b)-(iii), (c)-(i)","(a)-(ii), (b)-(iii), (c)-(i)","(a)-(iii), (b)-(i), (c)-(ii)","(a)-(iii), (b)-(i), (c)-(ii)","1","The Elephant Project in Tamor Pingla/Badalkhol started in 2011. The Jamvant (Bear) Project started in 2014. The Lemru Elephant Reserve was officially announced in 2019.","तमोर पिंगला/बादलखोल में हाथी परियोजना 2011 में शुरू हुई। जामवंत (भालू) परियोजना 2014 में शुरू हुई। लेमरू हाथी रिजर्व की आधिकारिक घोषणा 2019 में की गई थी।"
"Consider the following statements regarding the Lemru Elephant Reserve:\\n\\n1. It was officially announced in 2019 to mitigate human-elephant conflicts.\\n2. It encompasses an expansive area of exactly 1995 sq. km.\\n3. It is situated exclusively in the Surguja district.\\n\\nWhich of the statement(s) given above is/are NOT correct?","लेमरू हाथी रिजर्व के संबंध में निम्नलिखित कथनों पर विचार करें:\\n\\n1. मानव-हाथी संघर्ष को कम करने के लिए आधिकारिक तौर पर 2019 में इसकी घोषणा की गई थी।\\n2. इसमें ठीक 1995 वर्ग किमी का विस्तृत क्षेत्र शामिल है।\\n3. यह विशेष रूप से केवल सरगुजा जिले में स्थित है।\\n\\nऊपर दिए गए कथनों में से कौन सा/से सही नहीं है/हैं?","Only 1","केवल 1","Only 2","केवल 2","Only 3","केवल 3","1 and 3","1 और 3","3","Statements 1 and 2 are perfectly correct. Statement 3 is incorrect because the reserve spans multiple districts, mainly Korba, Raigarh, and Surguja, not exclusively Surguja.","कथन 1 और 2 बिल्कुल सही हैं। कथन 3 गलत है क्योंकि यह रिजर्व कई जिलों में फैला है, मुख्य रूप से कोरबा, रायगढ़ और सरगुजा, विशेष रूप से केवल सरगुजा में नहीं।"
"Where was Chhattisgarh's first Bird Festival (Pakshi Mahotsav) held to promote the conservation of local and wintering migratory birds?","स्थानीय और सर्दियों में आने वाले प्रवासी पक्षियों के संरक्षण को बढ़ावा देने के लिए छत्तीसगढ़ का पहला पक्षी महोत्सव (Bird Festival) कहाँ आयोजित किया गया था?","Rahangi (Bilaspur)","रहंगी (बिलासपुर)","Gidhwa-Parsada (Bemetara)","गिधवा-परसदा (बेमेतरा)","Nandanvan (Raipur)","नंदनवन (रायपुर)","Lamni (Jagdalpur)","लमनी (जगदलपुर)","2","The first bird festival in Chhattisgarh was organized at the Gidhwa-Parsada reservoir in the Bemetara district, which is a major bird conservation site.","छत्तीसगढ़ में पहला पक्षी महोत्सव बेमेतरा जिले के गिधवा-परसदा जलाशय में आयोजित किया गया था, जो एक प्रमुख पक्षी संरक्षण स्थल है।"
"Which of the following combinations correctly represents the four recognized Tiger Reserves of Chhattisgarh as of 2024?","निम्नलिखित में से कौन सा संयोजन 2024 तक छत्तीसगढ़ के चार मान्यता प्राप्त टाइगर रिजर्व का सही प्रतिनिधित्व करता है?","Indravati, Achanakmar, Sitanadi-Udanti, Guru Ghasidas-Tamor Pingla","इंद्रावती, अचानकमार, सीतानदी-उदंती, गुरु घासीदास-तमोर पिंगला","Indravati, Kanger Valley, Sitanadi, Barnawapara","इंद्रावती, कांगेर घाटी, सीतानदी, बारनवापारा","Guru Ghasidas, Achanakmar, Pamed, Bhairamgarh","गुरु घासीदास, अचानकमार, पामेड़, भैरमगढ़","Achanakmar, Kanger Valley, Udanti, Tamor Pingla","अचानकमार, कांगेर घाटी, उदंती, तमोर पिंगला","1","The four officially notified Tiger Reserves in Chhattisgarh are Indravati, Achanakmar, the combined Sitanadi-Udanti reserve, and the newly notified Guru Ghasidas-Tamor Pingla reserve.","छत्तीसगढ़ में चार आधिकारिक रूप से अधिसूचित टाइगर रिजर्व इंद्रावती, अचानकमार, संयुक्त सीतानदी-उदंती रिजर्व और नव अधिसूचित गुरु घासीदास-तमोर पिंगला रिजर्व हैं।"
"What is the total area covered by the Achanakmar-Amarkantak Biosphere Reserve, and how much of it falls within Chhattisgarh?","अचानकमार-अमरकंटक बायोस्फीयर रिजर्व का कुल क्षेत्रफल कितना है, और इसका कितना हिस्सा छत्तीसगढ़ के अंतर्गत आता है?","Total 3835.51 sq. km; 2610 sq. km in CG","कुल 3835.51 वर्ग किमी; सीजी में 2610 वर्ग किमी","Total 4500 sq. km; 1500 sq. km in CG","कुल 4500 वर्ग किमी; सीजी में 1500 वर्ग किमी","Total 2610 sq. km; 1258 sq. km in CG","कुल 2610 वर्ग किमी; सीजी में 1258 वर्ग किमी","Total 5550 sq. km; 3835 sq. km in CG","कुल 5550 वर्ग किमी; सीजी में 3835 वर्ग किमी","1","The Achanakmar-Amarkantak Biosphere Reserve (established in 2005) covers a total area of 3835.51 sq. km across MP and CG, out of which exactly 2610.53 sq. km lies in Chhattisgarh.","अचानकमार-अमरकंटक बायोस्फीयर रिजर्व (2005 में स्थापित) एमपी और सीजी में 3835.51 वर्ग किमी के कुल क्षेत्रफल को कवर करता है, जिसमें से ठीक 2610.53 वर्ग किमी छत्तीसगढ़ में है।"
"Assertion (A): Kotmi Sonar is a natural habitat for crocodiles in Chhattisgarh.\\n\\nReason (R): It is located in the Janjgir-Champa district and was developed as a conservation center in 2006-07.\\n\\nCodes:","कथन (A): कोटमी सोनार छत्तीसगढ़ में मगरमच्छों का एक प्राकृतिक आवास है।\\n\\nकारण (R): यह जांजगीर-चांपा जिले में स्थित है और इसे 2006-07 में एक संरक्षण केंद्र के रूप में विकसित किया गया था।\\n\\nकूट:","Both (A) and (R) are true and (R) is the correct explanation of (A)","(A) और (R) दोनों सही हैं और (R), (A) का सही स्पष्टीकरण है","Both (A) and (R) are true but (R) is NOT the correct explanation of (A)","(A) और (R) दोनों सही हैं लेकिन (R), (A) का सही स्पष्टीकरण नहीं है","(A) is true but (R) is false","(A) सही है लेकिन (R) गलत है","(A) is false but (R) is true","(A) गलत है लेकिन (R) सही है","4","The assertion is false because Kotmi Sonar is an 'artificial' (Kritrim) conservation reserve, not a natural one. The reason is factually true as it is in Janjgir-Champa and was established in 2006-07.","कथन गलत है क्योंकि कोटमी सोनार एक 'कृत्रिम' संरक्षण रिजर्व है, न कि प्राकृतिक। कारण तथ्यात्मक रूप से सत्य है क्योंकि यह जांजगीर-चांपा में है और 2006-07 में स्थापित किया गया था।"
"Which of the following is the only recognized 'Butterfly Park' (Titali Park) in Chhattisgarh, designed to boost micro-biodiversity?","निम्नलिखित में से कौन सा छत्तीसगढ़ में एकमात्र मान्यता प्राप्त 'तितली पार्क' (Butterfly Park) है, जिसे सूक्ष्म-जैव विविधता को बढ़ावा देने के लिए डिज़ाइन किया गया है?","Jungle Safari, Nawa Raipur","जंगल सफारी, नवा रायपुर","Kanger Valley National Park, Bastar","कांगेर घाटी राष्ट्रीय उद्यान, बस्तर","Achanakmar Sanctuary, Mungeli","अचानकमार अभयारण्य, मुंगेली","Sitanadi Sanctuary, Dhamtari","सीतानदी अभयारण्य, धमतरी","2","The Kanger Valley National Park in Bastar houses the state's first dedicated Butterfly Park, aiming to conserve the unique insect biodiversity of the dense Dandakaranya forests.","बस्तर में कांगेर घाटी राष्ट्रीय उद्यान में राज्य का पहला समर्पित तितली पार्क है, जिसका उद्देश्य घने दंडकारण्य जंगलों की अनूठी कीट जैव विविधता को संरक्षित करना है।"
"Regarding the Achanakmar Wildlife Sanctuary, consider the following statements:\\n\\n1. It was designated as a Biosphere Reserve in 2005.\\n2. It was included in UNESCO's Man and the Biosphere (MAB) program in 2012.\\n3. The Maniyari River flows through it.\\n\\nWhich of the above statements are correct?","अचानकमार वन्यजीव अभयारण्य के संबंध में, निम्नलिखित कथनों पर विचार करें:\\n\\n1. इसे 2005 में बायोस्फीयर रिजर्व के रूप में नामित किया गया था।\\n2. इसे 2012 में यूनेस्को के मैन एंड द बायोस्फीयर (MAB) कार्यक्रम में शामिल किया गया था।\\n3. मनियारी नदी इससे होकर बहती है।\\n\\nउपरोक्त में से कौन से कथन सही हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3","4","All statements are correct. Achanakmar-Amarkantak was made India's 14th Biosphere Reserve in 2005, added to the MAB list in 2012, and the Maniyari river passes right through it.","सभी कथन सही हैं। अचानकमार-अमरकंटक को 2005 में भारत का 14वां बायोस्फीयर रिजर्व बनाया गया, 2012 में MAB सूची में जोड़ा गया, और मनियारी नदी इसके ठीक बीच से होकर गुजरती है।"
"The state's first 'Jungle Safari', recognized as Asia's largest human-made safari (202.87 hectares), is located in which area?","राज्य की पहली 'जंगल सफारी', जिसे एशिया की सबसे बड़ी मानव निर्मित सफारी (202.87 हेक्टेयर) के रूप में मान्यता प्राप्त है, किस क्षेत्र में स्थित है?","Khandwa Village, Nawa Raipur","खंडवा ग्राम, नवा रायपुर","Kanan Pendari, Bilaspur","कानन पेंडारी, बिलासपुर","Maitri Bagh, Bhilai","मैत्री बाग, भिलाई","Ramchuha, Kabirdham","रामचुआ, कबीरधाम","1","The first Jungle Safari of Chhattisgarh is located in Khandwa village near Nawa Raipur (Atal Nagar). The second proposed safari is at Ramchuha (Kabirdham).","छत्तीसगढ़ की पहली जंगल सफारी नवा रायपुर (अटल नगर) के पास खंडवा ग्राम में स्थित है। दूसरी प्रस्तावित सफारी रामचुआ (कबीरधाम) में है।"
"In which district is the 'Badalkhol Wildlife Sanctuary' located, and which major animal is specifically seen migrating through its forest corridor?","'बादलखोल वन्यजीव अभयारण्य' किस जिले में स्थित है, और विशेष रूप से कौन सा प्रमुख जानवर इसके वन गलियारे (Corridor) से प्रवास करता हुआ देखा जाता है?","Surguja, Tigers","सरगुजा, बाघ","Jashpur, Elephants","जशपुर, हाथी","Raigarh, Wild Dogs","रायगढ़, जंगली कुत्ते","Balrampur, Nilgai","बलरामपुर, नीलगाय","2","The Badalkhol Sanctuary (the smallest at 105 sq. km) is located in Jashpur. It acts as a major corridor for wild Elephants migrating between Jharkhand and Chhattisgarh.","बादलखोल अभयारण्य (105 वर्ग किमी पर सबसे छोटा) जशपुर में स्थित है। यह झारखंड और छत्तीसगढ़ के बीच प्रवास करने वाले जंगली हाथियों के लिए एक प्रमुख गलियारे के रूप में कार्य करता है।"
"Match the zoological parks/safaris with their respective districts:\\n\\nList-I\\n(a) Kanan Pendari\\n(b) Maitri Bagh\\n(c) Nandanvan\\n\\nList-II\\n(i) Durg\\n(ii) Raipur\\n(iii) Bilaspur\\n\\nCodes:","प्राणी उद्यानों/सफारियों को उनके संबंधित जिलों के साथ सुमेलित करें:\\n\\nसूची-I\\n(a) कानन पेंडारी\\n(b) मैत्री बाग\\n(c) नंदनवन\\n\\nसूची-II\\n(i) दुर्ग\\n(ii) रायपुर\\n(iii) बिलासपुर\\n\\nकूट:","(a)-(iii), (b)-(i), (c)-(ii)","(a)-(iii), (b)-(i), (c)-(ii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(i), (b)-(ii), (c)-(iii)","(a)-(ii), (b)-(iii), (c)-(i)","(a)-(ii), (b)-(iii), (c)-(i)","(a)-(iii), (b)-(ii), (c)-(i)","(a)-(iii), (b)-(ii), (c)-(i)","1","Kanan Pendari is located in Bilaspur. Maitri Bagh (established as a symbol of Indo-Russian friendship) is in Bhilai (Durg). Nandanvan is in Raipur.","कानन पेंडारी बिलासपुर में स्थित है। मैत्री बाग (भारत-रूस मित्रता के प्रतीक के रूप में स्थापित) भिलाई (दुर्ग) में है। नंदनवन रायपुर में है。"`;

// Parse CSV
const lines = csvData.split('\\n');
const records = [];
let currentRecord = [];
let currentField = '';
let inQuotes = false;

for (let i = 0; i < csvData.length; i++) {
    let c = csvData[i];
    if (inQuotes) {
        if (c === '"') {
            if (i + 1 < csvData.length && csvData[i+1] === '"') {
                currentField += '"';
                i++;
            } else {
                inQuotes = false;
            }
        } else {
            currentField += c;
        }
    } else {
        if (c === '"') {
            inQuotes = true;
        } else if (c === ',') {
            currentRecord.push(currentField);
            currentField = '';
        } else if (c === '\n') {
            currentRecord.push(currentField);
            if (currentRecord.length >= 12) {
                records.push(currentRecord);
            }
            currentRecord = [];
            currentField = '';
        } else {
            currentField += c;
        }
    }
}
if (currentField || currentRecord.length > 0) {
    currentRecord.push(currentField);
    if (currentRecord.length >= 12) records.push(currentRecord);
}

// Remove header
if (records.length > 0 && records[0][0].includes('Q(EN)')) {
    records.shift();
}

console.log('Parsed', records.length, 'records.');

const topicId = 1200; // Wildlife Management (Parks & Sanctuaries)
const quizId = 1305;
const titleEn = 'Wildlife Management (Parks & Sanctuaries) Master Quiz';
const titleHi = 'वन्यजीव प्रबंधन (उद्यान एवं अभयारण्य) मास्टर क्विज़';
const descEn = "A highly authentic CGPSC Prelims quiz covering Chhattisgarh's National Parks, 11 Wildlife Sanctuaries, and major conservation projects (Lemru, Crocodile, Tiger Reserves) with precise dates, areas, and district locations.";
const descHi = "यह एक अत्यंत प्रामाणिक सीजीपीएससी प्रारंभिक क्विज़ है, जिसमें छत्तीसगढ़ के राष्ट्रीय उद्यानों, 11 वन्यजीव अभयारण्यों और प्रमुख संरक्षण परियोजनाओं (लेमरू, मगरमच्छ, टाइगर रिजर्व) को सटीक तिथियों, क्षेत्रों और जिलों के साथ कवर किया गया है।";

let sql = `INSERT INTO quizzes (id, topic_id, title, title_hi, description, description_hi, difficulty, total_questions, time_limit_mins, is_previous_year, created_at) VALUES
(${quizId}, ${topicId}, '${titleEn.replace(/'/g, "''")}', '${titleHi.replace(/'/g, "''")}', '${descEn.replace(/'/g, "''")}', '${descHi.replace(/'/g, "''")}', 'Hard', ${records.length}, ${Math.ceil(records.length * 1.5)}, 0, CURRENT_TIMESTAMP);

`;

sql += `INSERT INTO questions (quiz_id, topic_id, question, question_hi, option_a, option_a_hi, option_b, option_b_hi, option_c, option_c_hi, option_d, option_d_hi, correct_option, explanation, explanation_hi, sort_order) VALUES\n`;

let valueStrings = [];
let sortOrder = 1;
for (const r of records) {
    if (r.length < 13) continue;
    const q_en = r[0].replace(/'/g, "''").replace(/\\n/g, "\n");
    const q_hi = r[1].replace(/'/g, "''").replace(/\\n/g, "\n");
    const oa_en = r[2].replace(/'/g, "''");
    const oa_hi = r[3].replace(/'/g, "''");
    const ob_en = r[4].replace(/'/g, "''");
    const ob_hi = r[5].replace(/'/g, "''");
    const oc_en = r[6].replace(/'/g, "''");
    const oc_hi = r[7].replace(/'/g, "''");
    const od_en = r[8].replace(/'/g, "''");
    const od_hi = r[9].replace(/'/g, "''");
    const correct = parseInt(r[10]);
    const exp_en = r[11].replace(/'/g, "''");
    const exp_hi = r[12] ? r[12].replace(/'/g, "''") : '';
    
    valueStrings.push(`(${quizId}, ${topicId}, '${q_en}', '${q_hi}', '${oa_en}', '${oa_hi}', '${ob_en}', '${ob_hi}', '${oc_en}', '${oc_hi}', '${od_en}', '${od_hi}', ${correct}, '${exp_en}', '${exp_hi}', ${sortOrder++})`);
}

sql += valueStrings.join(',\n') + ';\n';

fs.writeFileSync(path.join(__dirname, 'import_wildlife.sql'), sql, 'utf8');
console.log('Wrote import_wildlife.sql');
