import csv
import json

csv_data = """Q(EN),Q(HI),OptA(EN),OptA(HI),OptB(EN),OptB(HI),OptC(EN),OptC(HI),OptD(EN),OptD(HI),Correct(1-4),Exp(EN),Exp(HI)
"Which of the following is the smallest Wildlife Sanctuary in Chhattisgarh based on geographical area?","भौगोलिक क्षेत्रफल के आधार पर छत्तीसगढ़ का सबसे छोटा वन्यजीव अभयारण्य निम्नलिखित में से कौन सा है?","Bhairamgarh","भैरमगढ़","Badalkhol","बादलखोल","Gomarda","गोमर्डा","Bhoramdeo","भोरमदेव",2,"Badalkhol Wildlife Sanctuary, located in the Jashpur district, is the smallest sanctuary in Chhattisgarh with an area of 105 sq km. It was established in 1975.","जशपुर जिले में स्थित बादलखोल वन्यजीव अभयारण्य छत्तीसगढ़ का सबसे छोटा अभयारण्य है, जिसका क्षेत्रफल 105 वर्ग किमी है। इसकी स्थापना 1975 में हुई थी।"
"Which Wildlife Sanctuary in Chhattisgarh is renowned for its significant population of 'Sonkutta' (Wild Dogs)?","छत्तीसगढ़ का कौन सा वन्यजीव अभयारण्य 'सोनकुत्ता' (जंगली कुत्ते) की महत्वपूर्ण आबादी के लिए प्रसिद्ध है?","Achanakmar","अचानकमार","Sitanadi","सीतानदी","Gomarda","गोमर्डा","Semarsot","सेमरसोत",3,"Gomarda Wildlife Sanctuary, located in the Sarangarh-Bilaigarh district (formerly Raigarh), was established in 1975 and is specially famous for the natural habitat of Sonkutta (Wild Dogs).","सारंगढ़-बिलाईगढ़ जिले (पूर्व में रायगढ़) में स्थित गोमर्डा वन्यजीव अभयारण्य की स्थापना 1975 में हुई थी और यह विशेष रूप से सोनकुत्ता के प्राकृतिक आवास के लिए प्रसिद्ध है।"
"Consider the following statements regarding Barnawapara Wildlife Sanctuary:\n\n1. It is bordered by the Balamdehi river and Jonk river.\n2. The historical Turturiya Ashram is located within its vicinity.\n3. It is officially the largest wildlife sanctuary in the state.\n\nWhich of the statement(s) given above is/are correct?","बारनवापारा वन्यजीव अभयारण्य के संबंध में निम्नलिखित कथनों पर विचार करें:\n\n1. यह बलमदेही नदी और जोंक नदी से घिरा हुआ है।\n2. ऐतिहासिक तुरतुरिया आश्रम इसके आसपास के क्षेत्र में स्थित है।\n3. यह आधिकारिक तौर पर राज्य का सबसे बड़ा वन्यजीव अभयारण्य है।\n\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3",1,"Statements 1 and 2 are correct. Statement 3 is false because Tamor Pingla (608 sq km) is the largest sanctuary in Chhattisgarh, while Barnawapara covers an area of 245 sq km.","कथन 1 और 2 सही हैं। कथन 3 गलत है क्योंकि तमोर पिंगला (608 वर्ग किमी) छत्तीसगढ़ का सबसे बड़ा अभयारण्य है, जबकि बारनवापारा का क्षेत्रफल 245 वर्ग किमी है।"
"Match the Wildlife Sanctuaries with their respective establishment years:\n\nList-I (Sanctuary)\n(a) Sitanadi\n(b) Semarsot\n(c) Pamed\n(d) Bhoramdeo\n\nList-II (Year)\n(i) 1978\n(ii) 1983\n(iii) 2001\n(iv) 1974\n\nCodes:","वन्यजीव अभयारण्यों को उनके संबंधित स्थापना वर्षों के साथ सुमेलित करें:\n\nसूची-I (अभयारण्य)\n(a) सीतानदी\n(b) सेमरसोत\n(c) पामेड़\n(d) भोरमदेव\n\nसूची-II (वर्ष)\n(i) 1978\n(ii) 1983\n(iii) 2001\n(iv) 1974\n\nकूट:","(a)-(iv), (b)-(i), (c)-(ii), (d)-(iii)","(a)-(iv), (b)-(i), (c)-(ii), (d)-(iii)","(a)-(i), (b)-(iv), (c)-(iii), (d)-(ii)","(a)-(i), (b)-(iv), (c)-(iii), (d)-(ii)","(a)-(iv), (b)-(ii), (c)-(i), (d)-(iii)","(a)-(iv), (b)-(ii), (c)-(i), (d)-(iii)","(a)-(ii), (b)-(i), (c)-(iv), (d)-(iii)","(a)-(ii), (b)-(i), (c)-(iv), (d)-(iii)",1,"Sitanadi is the oldest (1974). Semarsot and Tamor Pingla were established in 1978. Pamed and Bhairamgarh were established in 1983. Bhoramdeo is the newest (2001).","सीतानदी सबसे पुराना (1974) है। सेमरसोत और तमोर पिंगला की स्थापना 1978 में हुई थी। पामेड़ और भैरमगढ़ 1983 में स्थापित हुए। भोरमदेव सबसे नया (2001) है।"
"Assertion (A): Bhoramdeo Wildlife Sanctuary is considered the newest sanctuary in Chhattisgarh.\n\nReason (R): It is the only wildlife sanctuary in the state established after the formation of Chhattisgarh in the year 2001.\n\nCodes:","कथन (A): भोरमदेव वन्यजीव अभयारण्य को छत्तीसगढ़ का नवीनतम अभयारण्य माना जाता है।\n\nकारण (R): यह राज्य का एकमात्र वन्यजीव अभयारण्य है जिसकी स्थापना वर्ष 2001 में छत्तीसगढ़ के गठन के बाद हुई थी।\n\nकूट:","Both A and R are true, and R is the correct explanation of A.","A और R दोनों सत्य हैं, और R, A का सही स्पष्टीकरण है।","Both A and R are true, but R is not the correct explanation of A.","A और R दोनों सत्य हैं, लेकिन R, A का सही स्पष्टीकरण नहीं है।","A is true, but R is false.","A सत्य है, लेकिन R असत्य है।","A is false, but R is true.","A असत्य है, लेकिन R सत्य है。",1,"Both assertion and reason are true, and the reason correctly explains why Bhoramdeo (163 sq km, Kabirdham district) is the newest sanctuary, having been established in 2001 post-statehood.","कथन और कारण दोनों सत्य हैं, और कारण सही ढंग से स्पष्ट करता है कि भोरमदेव (163 वर्ग किमी, कबीरधाम जिला) नवीनतम अभयारण्य क्यों है, क्योंकि इसकी स्थापना राज्य निर्माण के बाद 2001 में हुई थी।"
"Arrange the following Wildlife Sanctuaries in descending order of their total geographical area:\n\n1. Achanakmar\n2. Sitanadi\n3. Tamor Pingla\n4. Badalkhol\n\nChoose the correct code:","निम्नलिखित वन्यजीव अभयारण्यों को उनके कुल भौगोलिक क्षेत्रफल के अवरोही (घटते) क्रम में व्यवस्थित करें:\n\n1. अचानकमार\n2. सीतानदी\n3. तमोर पिंगला\n4. बादलखोल\n\nसही कूट चुनें:","3, 2, 1, 4","3, 2, 1, 4","3, 1, 2, 4","3, 1, 2, 4","2, 3, 1, 4","2, 3, 1, 4","1, 2, 3, 4","1, 2, 3, 4",1,"The correct descending order by area is: Tamor Pingla (608 sq km) > Sitanadi (559 sq km) > Achanakmar (552 sq km) > Badalkhol (105 sq km).","क्षेत्रफल के अनुसार सही अवरोही क्रम है: तमोर पिंगला (608 वर्ग किमी) > सीतानदी (559 वर्ग किमी) > अचानकमार (552 वर्ग किमी) > बादलखोल (105 वर्ग किमी)।"
"Which of the following Wildlife Sanctuaries is NOT located in the Bijapur district of Chhattisgarh?","निम्नलिखित में से कौन सा वन्यजीव अभयारण्य छत्तीसगढ़ के बीजापुर जिले में स्थित नहीं है?","Pamed","पामेड़","Bhairamgarh","भैरमगढ़","Udanti","उदंती","None of the above","उपरोक्त में से कोई नहीं",3,"Udanti Wildlife Sanctuary is located in the Gariaband district. Pamed (265 sq km) and Bhairamgarh (139 sq km) are both located in the Bijapur district and are known for Wild Buffalo conservation.","उदंती वन्यजीव अभयारण्य गरियाबंद जिले में स्थित है। पामेड़ (265 वर्ग किमी) और भैरमगढ़ (139 वर्ग किमी) दोनों बीजापुर जिले में स्थित हैं और वन भैंसा संरक्षण के लिए जाने जाते हैं।"
"The 'Deepasha' (दीपाशा) project, which involved the successful artificial insemination and cloning research of the endangered Wild Buffalo, was conducted in which sanctuary?","'दीपाशा' परियोजना, जिसमें लुप्तप्राय वन भैंसों का सफल कृत्रिम गर्भाधान और क्लोनिंग अनुसंधान शामिल था, किस अभयारण्य में संचालित की गई थी?","Pamed Sanctuary","पामेड़ अभयारण्य","Udanti Sanctuary","उदंती अभयारण्य","Sitanadi Sanctuary","सीतानदी अभयारण्य","Bhairamgarh Sanctuary","भैरमगढ़ अभयारण्य",2,"Deepasha is the name of a female wild buffalo calf born through artificial insemination (with help from Karnal Research Institute) in the Udanti Sanctuary (Gariaband district) to conserve the endangered pure breed.","दीपाशा एक मादा वन भैंसा बछड़े का नाम है जिसका जन्म लुप्तप्राय शुद्ध नस्ल के संरक्षण के लिए उदंती अभयारण्य (गरियाबंद जिले) में कृत्रिम गर्भाधान (करनाल रिसर्च इंस्टीट्यूट की मदद से) के माध्यम से हुआ था।"
"Match the Wildlife Sanctuaries with their associated geographical features/rivers:\n\nList-I\n(a) Achanakmar\n(b) Tamor Pingla\n(c) Sitanadi\n(d) Udanti\n\nList-II\n(i) Godena Waterfall\n(ii) Sondur Reservoir\n(iii) Rihand River\n(iv) Maniyari River\n\nCodes:","वन्यजीव अभयारण्यों को उनकी संबंधित भौगोलिक विशेषताओं/नदियों के साथ सुमेलित करें:\n\nसूची-I\n(a) अचानकमार\n(b) तमोर पिंगला\n(c) सीतानदी\n(d) उदंती\n\nसूची-II\n(i) गोदना जलप्रपात\n(ii) सोंढूर जलाशय\n(iii) रिहंद नदी\n(iv) मनियारी नदी\n\nकूट:","(a)-(iii), (b)-(iv), (c)-(ii), (d)-(i)","(a)-(iii), (b)-(iv), (c)-(ii), (d)-(i)","(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)","(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)","(a)-(iv), (b)-(iii), (c)-(i), (d)-(ii)","(a)-(iv), (b)-(iii), (c)-(i), (d)-(ii)","(a)-(ii), (b)-(i), (c)-(iv), (d)-(iii)","(a)-(ii), (b)-(i), (c)-(iv), (d)-(iii)",2,"The Maniyari river flows through Achanakmar. Rihand river flows through Tamor Pingla. Sondur Reservoir is near Sitanadi, and Godena waterfall is situated on the Udanti river in Udanti Sanctuary.","मनियारी नदी अचानकमार से होकर बहती है। रिहंद नदी तमोर पिंगला से होकर बहती है। सोंढूर जलाशय सीतानदी के पास है, और गोदना जलप्रपात उदंती अभयारण्य में उदंती नदी पर स्थित है।"
"Consider the following statements regarding the Tropic of Cancer in Chhattisgarh:\n\n1. It passes through the Semarsot Wildlife Sanctuary.\n2. It passes through the Tamor Pingla Wildlife Sanctuary.\n\nWhich of the statement(s) given above is/are correct?","छत्तीसगढ़ में कर्क रेखा के संबंध में निम्नलिखित कथनों पर विचार करें:\n\n1. यह सेमरसोत वन्यजीव अभयारण्य से होकर गुजरती है।\n2. यह तमोर पिंगला वन्यजीव अभयारण्य से होकर गुजरती है।\n\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","Only 1","केवल 1","Only 2","केवल 2","Both 1 and 2","1 और 2 दोनों","Neither 1 nor 2","न तो 1 और न ही 2",1,"The Tropic of Cancer passes through the Semarsot Wildlife Sanctuary (Balrampur district), but it does not pass through the Tamor Pingla Wildlife Sanctuary (Surajpur district).","कर्क रेखा सेमरसोत वन्यजीव अभयारण्य (बलरामपुर जिला) से होकर गुजरती है, लेकिन यह तमोर पिंगला वन्यजीव अभयारण्य (सूरजपुर जिला) से होकर नहीं गुजरती है।"
"Which of the following Wildlife Sanctuaries in Chhattisgarh is geographically characterized by the presence of the Ramgarh hills in its northern region?","छत्तीसगढ़ के निम्नलिखित में से किस वन्यजीव अभयारण्य की भौगोलिक विशेषता इसके उत्तरी क्षेत्र में रामगढ़ पहाड़ियों की उपस्थिति है?","Semarsot","सेमरसोत","Badalkhol","बादलखोल","Gomarda","गोमर्डा","Tamor Pingla","तमोर पिंगला",1,"Semarsot Wildlife Sanctuary (430 sq km), established in 1978 in the Balrampur district, is situated in the northern part of the famous Ramgarh hills.","बलरामपुर जिले में 1978 में स्थापित सेमरसोत वन्यजीव अभयारण्य (430 वर्ग किमी), प्रसिद्ध रामगढ़ पहाड़ियों के उत्तरी भाग में स्थित है।"
"Identify the INCORRECT pair of Wildlife Sanctuary and its respective district:","वन्यजीव अभयारण्य और उसके संबंधित जिले के गलत युग्म की पहचान करें:","Gomarda - Sarangarh-Bilaigarh","गोमर्डा - सारंगढ़-बिलाईगढ़","Bhoramdeo - Kabirdham","भोरमदेव - कबीरधाम","Pamed - Narayanpur","पामेड़ - नारायणपुर","Badalkhol - Jashpur","बादलखोल - जशपुर",3,"Pamed Wildlife Sanctuary (265 sq km) is located in the Bijapur district, not Narayanpur. All other pairs are correctly matched.","पामेड़ वन्यजीव अभयारण्य (265 वर्ग किमी) बीजापुर जिले में स्थित है, न कि नारायणपुर में। अन्य सभी युग्म सही सुमेलित हैं।"
"Consider the following statements about Achanakmar Wildlife Sanctuary:\n\n1. It was declared a Biosphere Reserve under UNESCO's MAB program in 2012.\n2. It acts as an ecological corridor connecting with the Kanha Tiger Reserve of Madhya Pradesh.\n3. It was established in the year 1975.\n\nWhich of the statement(s) given above is/are correct?","अचानकमार वन्यजीव अभयारण्य के बारे में निम्नलिखित कथनों पर विचार करें:\n\n1. इसे 2012 में यूनेस्को के MAB कार्यक्रम के तहत बायोस्फीयर रिजर्व घोषित किया गया था।\n2. यह मध्य प्रदेश के कान्हा टाइगर रिजर्व से जुड़ने वाले एक पारिस्थितिक गलियारे के रूप में कार्य करता है।\n3. इसकी स्थापना वर्ष 1975 में हुई थी।\n\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3",4,"All three statements are correct. Achanakmar (1975) was declared India's 14th Biosphere Reserve in 2005 and added to the UNESCO MAB list in 2012. It connects with Kanha and Bandhavgarh reserves.","तीनों कथन सही हैं। अचानकमार (1975) को 2005 में भारत का 14वां बायोस्फीयर रिजर्व घोषित किया गया था और 2012 में यूनेस्को MAB सूची में जोड़ा गया था। यह कान्हा और बांधवगढ़ रिजर्व से जुड़ता है।"
"The 'Pawai Waterfall' is geographically situated within the boundaries of which Wildlife Sanctuary?","'पवई जलप्रपात' भौगोलिक रूप से किस वन्यजीव अभयारण्य की सीमाओं के भीतर स्थित है?","Tamor Pingla","तमोर पिंगला","Semarsot","सेमरसोत","Badalkhol","बादलखोल","Gomarda","गोमर्डा",2,"The Pawai waterfall is located on the Chanan river within the Semarsot Wildlife Sanctuary in the Balrampur district.","पवई जलप्रपात बलरामपुर जिले में सेमरसोत वन्यजीव अभयारण्य के भीतर चानन नदी पर स्थित है।"
"Assertion (A): Sitanadi is the oldest Wildlife Sanctuary in Chhattisgarh.\n\nReason (R): It was established in 1974 immediately following the enactment of the Wildlife Protection Act, 1972.\n\nCodes:","कथन (A): सीतानदी छत्तीसगढ़ का सबसे पुराना वन्यजीव अभयारण्य है。\n\nकारण (R): इसकी स्थापना 1974 में वन्यजीव संरक्षण अधिनियम, 1972 के अधिनियमन के तुरंत बाद की गई थी。\n\nकूट:","Both A and R are true, and R is the correct explanation of A.","A और R दोनों सत्य हैं, और R, A का सही स्पष्टीकरण है।","Both A and R are true, but R is not the correct explanation of A.","A और R दोनों सत्य हैं, लेकिन R, A का सही स्पष्टीकरण नहीं है।","A is true, but R is false.","A सत्य है, लेकिन R असत्य है।","A is false, but R is true.","A असत्य है, लेकिन R सत्य है。",1,"Sitanadi (Dhamtari) was the first sanctuary established in the state in 1974, closely following the national push for conservation under the 1972 Act.","सीतानदी (धमतरी) राज्य में 1974 में स्थापित पहला अभयारण्य था, जो 1972 अधिनियम के तहत संरक्षण के लिए राष्ट्रीय स्तर पर किए गए प्रयासों के तुरंत बाद स्थापित हुआ था।"
"Match the Wildlife Sanctuaries with their total geographical areas:\n\nList-I\n(a) Pamed\n(b) Gomarda\n(c) Barnawapara\n(d) Bhairamgarh\n\nList-II\n(i) 245 sq km\n(ii) 139 sq km\n(iii) 265 sq km\n(iv) 278 sq km\n\nCodes:","वन्यजीव अभयारण्यों को उनके कुल भौगोलिक क्षेत्रफल के साथ सुमेलित करें:\n\nसूची-I\n(a) पामेड़\n(b) गोमर्डा\n(c) बारनवापारा\n(d) भैरमगढ़\n\nसूची-II\n(i) 245 वर्ग किमी\n(ii) 139 वर्ग किमी\n(iii) 265 वर्ग किमी\n(iv) 278 वर्ग किमी\n\nकूट:","(a)-(iii), (b)-(iv), (c)-(i), (d)-(ii)","(a)-(iii), (b)-(iv), (c)-(i), (d)-(ii)","(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)","(a)-(iv), (b)-(iii), (c)-(ii), (d)-(i)","(a)-(iii), (b)-(i), (c)-(iv), (d)-(ii)","(a)-(iii), (b)-(i), (c)-(iv), (d)-(ii)","(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)","(a)-(ii), (b)-(i), (c)-(iii), (d)-(iv)",1,"Exact areas: Pamed = 265 sq km, Gomarda = 278 sq km, Barnawapara = 245 sq km, and Bhairamgarh = 139 sq km.","सटीक क्षेत्रफल: पामेड़ = 265 वर्ग किमी, गोमर्डा = 278 वर्ग किमी, बारनवापारा = 245 वर्ग किमी, और भैरमगढ़ = 139 वर्ग किमी।"
"In which Wildlife Sanctuary of Chhattisgarh are you most likely to find 'Black Panthers' (Melanistic Leopards), a rare phenomenon recently sighted globally?","छत्तीसगढ़ के किस वन्यजीव अभयारण्य में आपको 'ब्लैक पैंथर' (मेलेनिस्टिक तेंदुआ) मिलने की सबसे अधिक संभावना है, जो हाल ही में विश्व स्तर पर देखी गई एक दुर्लभ घटना है?","Barnawapara","बारनवापारा","Sitanadi","सीतानदी","Achanakmar","अचानकमार","Tamor Pingla","तमोर पिंगला",3,"Recently, a rare Black Panther (locally known as Bagheera) was sighted in the Achanakmar Tiger Reserve (Sanctuary), making it a significant spot for rare melanistic leopards.","हाल ही में, अचानकमार टाइगर रिजर्व (अभयारण्य) में एक दुर्लभ ब्लैक पैंथर (स्थानीय रूप से बघीरा के रूप में जाना जाता है) देखा गया था, जो इसे दुर्लभ मेलेनिस्टिक तेंदुओं के लिए एक महत्वपूर्ण स्थान बनाता है।"
"Consider the following statements regarding the Udanti and Sitanadi Sanctuaries:\n\n1. They were jointly included in Project Tiger in the year 2006.\n2. Sitanadi Sanctuary is larger in area compared to Udanti Sanctuary.\n3. Both sanctuaries fall entirely within the Bastar division.\n\nWhich of the statement(s) given above is/are correct?","उदंती और सीतानदी अभयारण्यों के संबंध में निम्नलिखित कथनों पर विचार करें:\n\n1. इन्हें वर्ष 2006 में संयुक्त रूप से प्रोजेक्ट टाइगर में शामिल किया गया था।\n2. उदंती अभयारण्य की तुलना में सीतानदी अभयारण्य क्षेत्रफल में बड़ा है।\n3. दोनों अभयारण्य पूरी तरह से बस्तर संभाग के अंतर्गत आते हैं।\n\nऊपर दिए गए कथनों में से कौन सा/से सही है/हैं?","1 and 2 only","केवल 1 और 2","2 and 3 only","केवल 2 और 3","1 and 3 only","केवल 1 और 3","1, 2, and 3","1, 2, और 3",1,"Statements 1 and 2 are correct (Sitanadi is 559 sq km, Udanti is 230 sq km). Statement 3 is incorrect because Dhamtari (Sitanadi) and Gariaband (Udanti) belong to the Raipur division, not Bastar.","कथन 1 और 2 सही हैं (सीतानदी 559 वर्ग किमी है, उदंती 230 वर्ग किमी है)। कथन 3 गलत है क्योंकि धमतरी (सीतानदी) और गरियाबंद (उदंती) रायपुर संभाग के अंतर्गत आते हैं, न कि बस्तर संभाग के।"
"Which of the following Wildlife Sanctuaries is NOT part of the Lemru Elephant Reserve project spanning across northern Chhattisgarh?","निम्नलिखित में से कौन सा वन्यजीव अभयारण्य उत्तरी छत्तीसगढ़ में फैले लेमरू एलीफेंट रिजर्व (हाथी रिजर्व) परियोजना का हिस्सा नहीं है?","Badalkhol","बादलखोल","Semarsot","सेमरसोत","Tamor Pingla","तमोर पिंगला","Gomarda","गोमर्डा",4,"The Surguja-Jashpur Elephant Reserve encompasses Badalkhol, Semarsot, and Tamor Pingla sanctuaries. Gomarda (Sarangarh-Bilaigarh district) is not part of this elephant corridor.","सरगुजा-जशपुर एलीफेंट रिजर्व में बादलखोल, सेमरसोत और तमोर पिंगला अभयारण्य शामिल हैं। गोमर्डा (सारंगढ़-बिलाईगढ़ जिला) इस हाथी गलियारे का हिस्सा नहीं है।"
"Arrange the establishment years of the following protected areas in chronological order:\n\n1. Barnawapara Sanctuary\n2. Gomarda Sanctuary\n3. Bhoramdeo Sanctuary\n4. Sitanadi Sanctuary\n\nChoose the correct code:","निम्नलिखित संरक्षित क्षेत्रों के स्थापना वर्षों को कालानुक्रमिक क्रम (समय के अनुसार) में व्यवस्थित करें:\n\n1. बारनवापारा अभयारण्य\n2. गोमर्डा अभयारण्य\n3. भोरमदेव अभयारण्य\n4. सीतानदी अभयारण्य\n\nसही कूट चुनें:","4, 1, 2, 3","4, 1, 2, 3","4, 2, 1, 3","4, 2, 1, 3","2, 4, 1, 3","2, 4, 1, 3","1, 2, 4, 3","1, 2, 4, 3",2,"The correct chronological order is: Sitanadi (1974) -> Gomarda (1975) -> Barnawapara (1976) -> Bhoramdeo (2001).","सही कालानुक्रमिक क्रम है: सीतानदी (1974) -> गोमर्डा (1975) -> बारनवापारा (1976) -> भोरमदेव (2001)।"
"""

def escape_sql_string(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

reader = csv.reader(csv_data.strip().splitlines())
header = next(reader)
rows = list(reader)

quiz_id = 1299
topic_id = 1158
title = "Wildlife Sanctuaries (Abhyaranya) Master Quiz"
title_hi = "वन्यजीव अभयारण्य (Abhyaranya) मास्टर क्विज़"
desc = "Master Chhattisgarh's Wildlife Sanctuaries with this highly focused CGPSC Prelims quiz. Test your knowledge on the exact establishment years, areas, districts, and specific wildlife of the 11 sanctuaries."
desc_hi = "इस अत्यधिक केंद्रित सीजीपीएससी प्रीलिम्स क्विज़ के साथ छत्तीसगढ़ के वन्यजीव अभयारण्यों पर अपनी पकड़ मजबूत करें। 11 अभयारण्यों के सटीक स्थापना वर्षों, क्षेत्रों, जिलों और विशिष्ट वन्यजीवों पर अपने ज्ञान का परीक्षण करें।"
total_q = len(rows)
time_limit = total_q
is_premium = 0
difficulty = "Medium"
is_pyq = 0

sql = f'''INSERT INTO quizzes (id, topic_id, title, title_hi, total_questions, time_limit_mins, is_premium, difficulty, is_previous_year, description, description_hi) VALUES ({quiz_id}, {topic_id}, {escape_sql_string(title)}, {escape_sql_string(title_hi)}, {total_q}, {time_limit}, {is_premium}, {escape_sql_string(difficulty)}, {is_pyq}, {escape_sql_string(desc)}, {escape_sql_string(desc_hi)});
'''

for i, row in enumerate(rows):
    q_en, q_hi, oa_en, oa_hi, ob_en, ob_hi, oc_en, oc_hi, od_en, od_hi, correct, exp_en, exp_hi = row
    
    sql += f'''INSERT INTO questions (quiz_id, topic_id, question, question_hi, option_a, option_a_hi, option_b, option_b_hi, option_c, option_c_hi, option_d, option_d_hi, correct_option, explanation, explanation_hi, sort_order) VALUES ({quiz_id}, {topic_id}, {escape_sql_string(q_en)}, {escape_sql_string(q_hi)}, {escape_sql_string(oa_en)}, {escape_sql_string(oa_hi)}, {escape_sql_string(ob_en)}, {escape_sql_string(ob_hi)}, {escape_sql_string(oc_en)}, {escape_sql_string(oc_hi)}, {escape_sql_string(od_en)}, {escape_sql_string(od_hi)}, {correct}, {escape_sql_string(exp_en)}, {escape_sql_string(exp_hi)}, {i+1});
'''

with open("scratch/wildlife_quiz.sql", "w", encoding="utf-8") as f:
    f.write(sql)
print("SQL generated")
