-- Update topics name_hi

UPDATE topics SET name_hi = 'प्रागैतिहासिक और आद्य-ऐतिहासिक भारत (पाषाण काल, ताम्रपाषाण काल)' WHERE id = 1001;
UPDATE topics SET name_hi = 'सिंधु घाटी सभ्यता' WHERE id = 1002;
UPDATE topics SET name_hi = 'वैदिक काल (प्रारंभिक और उत्तर वैदिक)' WHERE id = 1003;
UPDATE topics SET name_hi = 'जैन और बौद्ध धर्म: उत्पत्ति और प्रसार' WHERE id = 1004;
UPDATE topics SET name_hi = 'महाजनपद और मगध का उत्कर्ष' WHERE id = 1005;
UPDATE topics SET name_hi = 'मौर्य साम्राज्य (चंद्रगुप्त, अशोक, प्रशासन)' WHERE id = 1006;
UPDATE topics SET name_hi = 'मौर्योत्तर राजवंश (शुंग, कण्व, सातवाहन, हिंद-यवन)' WHERE id = 1007;
UPDATE topics SET name_hi = 'गुप्त साम्राज्य (राजव्यवस्था, अर्थव्यवस्था, स्वर्ण युग)' WHERE id = 1008;
UPDATE topics SET name_hi = 'गुप्तोत्तर काल और हर्षवर्धन' WHERE id = 1009;
UPDATE topics SET name_hi = 'दक्षिण भारतीय राजवंश (चोल, चेर, पांड्य, पल्लव)' WHERE id = 1010;
UPDATE topics SET name_hi = 'दिल्ली सल्तनत (गुलाम, खिलजी, तुगलक, सैयद, लोदी राजवंश)' WHERE id = 1011;
UPDATE topics SET name_hi = 'मुगल साम्राज्य (बाबर से औरंगजेब, प्रशासन, कला)' WHERE id = 1012;
UPDATE topics SET name_hi = 'विजयनगर और बहमनी साम्राज्य' WHERE id = 1013;
UPDATE topics SET name_hi = 'भक्ति और सूफी आंदोलन' WHERE id = 1014;
UPDATE topics SET name_hi = 'मराठा साम्राज्य (शिवाजी से पेशवा तक)' WHERE id = 1015;
UPDATE topics SET name_hi = 'यूरोपीय शक्तियों का आगमन (पुर्तगाली, डच, फ्रांसीसी, ब्रिटिश)' WHERE id = 1016;
UPDATE topics SET name_hi = 'आंग्ल-भारतीय युद्ध (कर्नाटक, मैसूर, मराठा, सिख युद्ध)' WHERE id = 1017;
UPDATE topics SET name_hi = 'ब्रिटिश विस्तार - कूटनीति और व्यपगत का सिद्धांत (हड़प नीति)' WHERE id = 1018;
UPDATE topics SET name_hi = 'ब्रिटिश शासन का आर्थिक प्रभाव (भू-राजस्व व्यवस्था, विऔद्योगीकरण)' WHERE id = 1019;
UPDATE topics SET name_hi = 'सामाजिक और धार्मिक सुधार आंदोलन (ब्रह्म समाज, आर्य समाज आदि)' WHERE id = 1020;
UPDATE topics SET name_hi = '1857 का विद्रोह - कारण, विस्तार और परिणाम' WHERE id = 1021;
UPDATE topics SET name_hi = 'भारतीय राष्ट्रीय कांग्रेस का गठन और प्रारंभिक चरण' WHERE id = 1022;
UPDATE topics SET name_hi = 'बंगाल विभाजन और स्वदेशी आंदोलन' WHERE id = 1023;
UPDATE topics SET name_hi = 'उग्रवाद का उदय और क्रांतिकारी आंदोलन' WHERE id = 1024;
UPDATE topics SET name_hi = 'होमरूल आंदोलन' WHERE id = 1025;
UPDATE topics SET name_hi = 'गांधीवादी युग (असहयोग, सविनय अवज्ञा, भारत छोड़ो)' WHERE id = 1026;
UPDATE topics SET name_hi = 'किसान, मजदूर और जनजातीय आंदोलन' WHERE id = 1027;
UPDATE topics SET name_hi = 'दलित सुधार आंदोलन (अंबेडकर का योगदान)' WHERE id = 1028;
UPDATE topics SET name_hi = 'मुस्लिम सुधार आंदोलन और अलीगढ़ आंदोलन' WHERE id = 1029;
UPDATE topics SET name_hi = 'आजाद हिंद फौज (सुभाष चंद्र बोस, INA)' WHERE id = 1030;
UPDATE topics SET name_hi = 'स्वतंत्रता और भारत का विभाजन (1947)' WHERE id = 1031;
UPDATE topics SET name_hi = 'देसी रियासतों का एकीकरण' WHERE id = 1032;
UPDATE topics SET name_hi = 'भारत: स्थिति, विस्तार और पड़ोसी देश' WHERE id = 1033;
UPDATE topics SET name_hi = 'भूवैज्ञानिक संरचना और भौतिक विभाजन (हिमालय, मैदान, पठार, तट, द्वीप)' WHERE id = 1034;
UPDATE topics SET name_hi = 'अपवाह तंत्र (हिमालयी और प्रायद्वीपीय नदियां)' WHERE id = 1035;
UPDATE topics SET name_hi = 'भारत की जलवायु (मानसून की क्रियाविधि, ऋतुएं)' WHERE id = 1036;
UPDATE topics SET name_hi = 'भारत की मिट्टियां' WHERE id = 1037;
UPDATE topics SET name_hi = 'प्राकृतिक वनस्पति और वन प्रकार' WHERE id = 1038;
UPDATE topics SET name_hi = 'वन्यजीव और जैव विविधता संरक्षण क्षेत्र' WHERE id = 1039;
UPDATE topics SET name_hi = 'जनसंख्या जनगणना और जनसांख्यिकीय प्रवृत्तियां' WHERE id = 1040;
UPDATE topics SET name_hi = 'जनसंख्या वृद्धि, घनत्व और वितरण' WHERE id = 1041;
UPDATE topics SET name_hi = 'जन्म दर, मृत्यु दर, शिशु मृत्यु दर' WHERE id = 1042;
UPDATE topics SET name_hi = 'प्रवास के प्रतिरूप (माइग्रेशन)' WHERE id = 1043;
UPDATE topics SET name_hi = 'साक्षरता दर और व्यावसायिक संरचना' WHERE id = 1044;
UPDATE topics SET name_hi = 'शहरीकरण की प्रवृत्तियां' WHERE id = 1045;
UPDATE topics SET name_hi = 'कृषि - फसल प्रतिरूप (खाद्यान्न, दलहन, तिलहन, नकदी फसलें)' WHERE id = 1046;
UPDATE topics SET name_hi = 'सिंचाई प्रणाली और बहुउद्देशीय परियोजनाएं' WHERE id = 1047;
UPDATE topics SET name_hi = 'हरित, श्वेत और नीली क्रांतियां' WHERE id = 1048;
UPDATE topics SET name_hi = 'खनिज संसाधन - वितरण और उत्पादन' WHERE id = 1049;
UPDATE topics SET name_hi = 'ऊर्जा संसाधन (कोयला, पेट्रोलियम, तापीय, नाभिकीय, गैर-पारंपरिक)' WHERE id = 1050;
UPDATE topics SET name_hi = 'उद्योग - विकास, प्रकार और अवस्थिति कारक' WHERE id = 1051;
UPDATE topics SET name_hi = 'संवैधानिक विकास (1773-1950 - रेगुलेटिंग एक्ट से भारत सरकार अधिनियम तक)' WHERE id = 1052;
UPDATE topics SET name_hi = 'संविधान का निर्माण (संविधान सभा)' WHERE id = 1053;
UPDATE topics SET name_hi = 'प्रस्तावना - विशेषताएं और महत्व' WHERE id = 1054;
UPDATE topics SET name_hi = 'संविधान की प्रकृति (संघीय/एकात्मक विशेषताएं)' WHERE id = 1055;
UPDATE topics SET name_hi = 'मौलिक अधिकार' WHERE id = 1056;
UPDATE topics SET name_hi = 'मौलिक कर्तव्य' WHERE id = 1057;
UPDATE topics SET name_hi = 'राज्य के नीति निदेशक तत्व' WHERE id = 1058;
UPDATE topics SET name_hi = 'संविधान संशोधन और बुनियादी ढांचा सिद्धांत' WHERE id = 1059;
UPDATE topics SET name_hi = 'आपातकालीन प्रावधान (राष्ट्रीय, राज्य, वित्तीय)' WHERE id = 1060;
UPDATE topics SET name_hi = 'संघीय कार्यपालिका (राष्ट्रपति, उपराष्ट्रपति, प्रधानमंत्री, मंत्रिपरिषद)' WHERE id = 1061;
UPDATE topics SET name_hi = 'संघीय विधायिका (संसद - लोकसभा, राज्यसभा)' WHERE id = 1062;
UPDATE topics SET name_hi = 'संघीय न्यायपालिका (सर्वोच्च न्यायालय, न्यायिक समीक्षा, न्यायिक सक्रियता)' WHERE id = 1063;
UPDATE topics SET name_hi = 'भारत का महान्यायवादी (अटॉर्नी जनरल)' WHERE id = 1064;
UPDATE topics SET name_hi = 'राज्य कार्यपालिका (राज्यपाल, मुख्यमंत्री, मंत्रिपरिषद)' WHERE id = 1065;
UPDATE topics SET name_hi = 'राज्य विधायिका (विधानमंडल)' WHERE id = 1066;
UPDATE topics SET name_hi = 'राज्य न्यायपालिका (उच्च न्यायालय, महाधिवक्ता)' WHERE id = 1067;
UPDATE topics SET name_hi = 'केंद्र-राज्य संबंध (विधायी, प्रशासनिक, वित्तीय)' WHERE id = 1068;
UPDATE topics SET name_hi = 'अखिल भारतीय सेवाएं' WHERE id = 1069;
UPDATE topics SET name_hi = 'UPSC और राज्य लोक सेवा आयोग' WHERE id = 1070;
UPDATE topics SET name_hi = 'संवैधानिक उपचारों का अधिकार और जनहित याचिकाएं (PIL)' WHERE id = 1071;
UPDATE topics SET name_hi = 'पंचायती राज और नगर पालिकाएं (73वां और 74वां संशोधन)' WHERE id = 1072;
UPDATE topics SET name_hi = 'लोकपाल और लोकायुक्त' WHERE id = 1073;
UPDATE topics SET name_hi = 'सूचना का अधिकार (RTI)' WHERE id = 1074;
UPDATE topics SET name_hi = 'चुनाव आयोग और चुनावी प्रक्रिया' WHERE id = 1075;
UPDATE topics SET name_hi = 'छत्तीसगढ़ की प्रशासनिक/विधायी/न्यायिक संरचना' WHERE id = 1076;
UPDATE topics SET name_hi = 'राष्ट्रीय आय और प्रति व्यक्ति आय की अवधारणाएं' WHERE id = 1077;
UPDATE topics SET name_hi = 'जीडीपी, जीएनपी, अर्थव्यवस्था में संरचनात्मक परिवर्तन' WHERE id = 1078;
UPDATE topics SET name_hi = 'पंचवर्षीय योजनाएं और नीति आयोग' WHERE id = 1079;
UPDATE topics SET name_hi = 'आर्थिक सुधार (LPG - 1991 के सुधार)' WHERE id = 1080;
UPDATE topics SET name_hi = 'गरीबी और बेरोजगारी (प्रकार, मापन)' WHERE id = 1081;
UPDATE topics SET name_hi = 'बैंकिंग प्रणाली (RBI, वाणिज्यिक बैंक, NBFCs)' WHERE id = 1082;
UPDATE topics SET name_hi = 'मौद्रिक नीति और साख नियंत्रण' WHERE id = 1083;
UPDATE topics SET name_hi = 'लोक वित्त (राजस्व, व्यय, राजकोषीय घाटा)' WHERE id = 1084;
UPDATE topics SET name_hi = 'कराधान प्रणाली (प्रत्यक्ष/अप्रत्यक्ष, GST)' WHERE id = 1085;
UPDATE topics SET name_hi = 'विदेशी व्यापार और भुगतान संतुलन' WHERE id = 1086;
UPDATE topics SET name_hi = 'मुद्रास्फीति और मूल्य स्थिरता' WHERE id = 1087;
UPDATE topics SET name_hi = 'भौतिकी - यांत्रिकी, प्रकाश, विद्युत, आधुनिक भौतिकी के मूल तत्व' WHERE id = 1088;
UPDATE topics SET name_hi = 'रसायन विज्ञान - रासायनिक अभिक्रियाएं, धातु/अधातु, कार्बनिक यौगिक' WHERE id = 1089;
UPDATE topics SET name_hi = 'जीव विज्ञान - मानव शरीर तंत्र, पादप कार्यिकी, आनुवंशिकी के मूल तत्व' WHERE id = 1090;
UPDATE topics SET name_hi = 'दैनिक जीवन में विज्ञान के अनुप्रयोग' WHERE id = 1091;
UPDATE topics SET name_hi = 'कंप्यूटर और आईटी के मूल तत्व' WHERE id = 1092;
UPDATE topics SET name_hi = 'ग्रामीण विकास में आईटी की भूमिका' WHERE id = 1093;
UPDATE topics SET name_hi = 'अंतरिक्ष प्रौद्योगिकी (ISRO के कीर्तिमान)' WHERE id = 1094;
UPDATE topics SET name_hi = 'रक्षा प्रौद्योगिकी' WHERE id = 1095;
UPDATE topics SET name_hi = 'संचार प्रौद्योगिकी' WHERE id = 1096;
UPDATE topics SET name_hi = 'जैव प्रौद्योगिकी के अनुप्रयोग' WHERE id = 1097;
UPDATE topics SET name_hi = 'नाभिकीय प्रौद्योगिकी और ऊर्जा' WHERE id = 1098;
UPDATE topics SET name_hi = 'वैदिक और औपनिषदिक चिंतन' WHERE id = 1099;
UPDATE topics SET name_hi = 'आस्तिक दर्शन (न्याय, वैशेषिक, सांख्य, योग, मीमांसा, वेदांत)' WHERE id = 1100;
UPDATE topics SET name_hi = 'नास्तिक दर्शन (चार्वाक, जैन, बौद्ध दर्शन)' WHERE id = 1101;
UPDATE topics SET name_hi = 'भगवद गीता का दर्शन' WHERE id = 1102;
UPDATE topics SET name_hi = 'आधुनिक भारतीय विचारक (विवेकानंद, अरबिंदो, गांधी, अंबेडकर)' WHERE id = 1103;
UPDATE topics SET name_hi = 'शास्त्रीय नृत्य शैलियां' WHERE id = 1104;
UPDATE topics SET name_hi = 'शास्त्रीय और लोक संगीत' WHERE id = 1105;
UPDATE topics SET name_hi = 'भारतीय वास्तुकला (मंदिर शैलियां, इंडो-इस्लामिक वास्तुकला)' WHERE id = 1106;
UPDATE topics SET name_hi = 'भारतीय चित्रकला और मूर्तिकला' WHERE id = 1107;
UPDATE topics SET name_hi = 'संगम, शास्त्रीय और मध्यकालीन साहित्य' WHERE id = 1108;
UPDATE topics SET name_hi = 'मेले, त्योहार और धार्मिक परंपराएं' WHERE id = 1109;
UPDATE topics SET name_hi = 'भारत में यूनेस्को विश्व धरोहर स्थल' WHERE id = 1110;
UPDATE topics SET name_hi = 'भाषाएं और साहित्यिक अकादमियां' WHERE id = 1111;
UPDATE topics SET name_hi = 'राष्ट्रीय घटनाक्रम, नीतियां और योजनाएं (पिछले 1 वर्ष की)' WHERE id = 1112;
UPDATE topics SET name_hi = 'अंतर्राष्ट्रीय संबंध और शिखर सम्मेलन' WHERE id = 1113;
UPDATE topics SET name_hi = 'सरकारी योजनाएं और मिशन' WHERE id = 1114;
UPDATE topics SET name_hi = 'पुरस्कार और सम्मान' WHERE id = 1115;
UPDATE topics SET name_hi = 'नियुक्तियां (राष्ट्रीय/अंतर्राष्ट्रीय निकाय)' WHERE id = 1116;
UPDATE topics SET name_hi = 'पुस्तकें और लेखक' WHERE id = 1117;
UPDATE topics SET name_hi = 'निधन (प्रसिद्ध व्यक्तित्व)' WHERE id = 1118;
UPDATE topics SET name_hi = 'राष्ट्रीय और अंतर्राष्ट्रीय टूर्नामेंट' WHERE id = 1119;
UPDATE topics SET name_hi = 'ओलंपिक, राष्ट्रमंडल, एशियाई खेल' WHERE id = 1120;
UPDATE topics SET name_hi = 'खेल पुरस्कार (खेल रत्न, अर्जुन, द्रोणाचार्य)' WHERE id = 1121;
UPDATE topics SET name_hi = 'रिकॉर्ड और उपलब्धियां' WHERE id = 1122;
UPDATE topics SET name_hi = 'खेल निकाय और शब्दावली' WHERE id = 1123;
UPDATE topics SET name_hi = 'पारिस्थितिकी तंत्र और जैव विविधता के मूल तत्व' WHERE id = 1124;
UPDATE topics SET name_hi = 'पर्यावरणीय प्रदूषण (वायु, जल, मृदा, ध्वनि)' WHERE id = 1125;
UPDATE topics SET name_hi = 'जलवायु परिवर्तन और ग्लोबल वार्मिंग' WHERE id = 1126;
UPDATE topics SET name_hi = 'अंतर्राष्ट्रीय पर्यावरण समझौते (पेरिस समझौता, क्योटो प्रोटोकॉल)' WHERE id = 1127;
UPDATE topics SET name_hi = 'राष्ट्रीय पर्यावरण नीतियां और कानून' WHERE id = 1128;
UPDATE topics SET name_hi = 'संरक्षित क्षेत्र - राष्ट्रीय उद्यान, अभयारण्य, जीवमंडल रिजर्व' WHERE id = 1129;
UPDATE topics SET name_hi = 'सतत विकास लक्ष्य (SDGs)' WHERE id = 1130;
UPDATE topics SET name_hi = 'प्राचीन काल (वैदिक काल से गुप्त काल तक का क्षेत्र)' WHERE id = 1131;
UPDATE topics SET name_hi = 'प्रमुख राजवंश - राजर्षितुल्य कुल, नल, शरभपुरीय, पांडुवंशी, सोमवंशी' WHERE id = 1132;
UPDATE topics SET name_hi = 'कल्चुरी राजवंश और प्रशासन (रतनपुर और रायपुर शाखाएं)' WHERE id = 1133;
UPDATE topics SET name_hi = 'छत्तीसगढ़ में मराठा शासन' WHERE id = 1134;
UPDATE topics SET name_hi = 'ब्रिटिश संरक्षण काल' WHERE id = 1135;
UPDATE topics SET name_hi = 'छत्तीसगढ़ की पूर्व रियासतें और जमींदारियां' WHERE id = 1136;
UPDATE topics SET name_hi = 'सामंती प्रशासन व्यवस्था' WHERE id = 1137;
UPDATE topics SET name_hi = 'छत्तीसगढ़ में 1857 का विद्रोह (नारायण सिंह आदि)' WHERE id = 1138;
UPDATE topics SET name_hi = 'स्थानीय स्वतंत्रता सेनानी और आंदोलन' WHERE id = 1139;
UPDATE topics SET name_hi = 'पृथक राज्य के रूप में छत्तीसगढ़ का गठन (2000) - पृष्ठभूमि' WHERE id = 1140;
UPDATE topics SET name_hi = 'स्थिति, विस्तार और सीमा' WHERE id = 1141;
UPDATE topics SET name_hi = 'भूवैज्ञानिक संरचना और भौतिक विभाजन' WHERE id = 1142;
UPDATE topics SET name_hi = 'अपवाह तंत्र (महानदी, शिवनाथ, इंद्रावती बेसिन)' WHERE id = 1143;
UPDATE topics SET name_hi = 'जलवायु और वर्षा का प्रतिरूप' WHERE id = 1144;
UPDATE topics SET name_hi = 'मिट्टियों के प्रकार' WHERE id = 1145;
UPDATE topics SET name_hi = 'जनसंख्या वृद्धि, घनत्व, वितरण' WHERE id = 1146;
UPDATE topics SET name_hi = 'जन्म/मृत्यु/शिशु मृत्यु दर' WHERE id = 1147;
UPDATE topics SET name_hi = 'लिंगानुपात और आयु वर्ग' WHERE id = 1148;
UPDATE topics SET name_hi = 'प्रवास' WHERE id = 1149;
UPDATE topics SET name_hi = 'अनुसूचित जनजाति जनसंख्या आंकड़े' WHERE id = 1150;
UPDATE topics SET name_hi = 'साक्षरता और व्यावसायिक संरचना' WHERE id = 1151;
UPDATE topics SET name_hi = 'शहरीकरण' WHERE id = 1152;
UPDATE topics SET name_hi = 'परिवार कल्याण कार्यक्रम' WHERE id = 1153;
UPDATE topics SET name_hi = 'पुरातात्विक स्थल और उत्खनन स्थल (सिरपुर, मल्हार आदि)' WHERE id = 1154;
UPDATE topics SET name_hi = 'संरक्षित स्मारक' WHERE id = 1155;
UPDATE topics SET name_hi = 'पर्यटन स्थल (छत्तीसगढ़ सरकार द्वारा अधिसूचित)' WHERE id = 1156;
UPDATE topics SET name_hi = 'जलप्रपात और गुफाएं (विशेषकर बस्तर क्षेत्र)' WHERE id = 1157;
UPDATE topics SET name_hi = 'राष्ट्रीय उद्यान और वन्यजीव अभयारण्य' WHERE id = 1158;
UPDATE topics SET name_hi = 'छत्तीसगढ़ी साहित्य का इतिहास और विकास' WHERE id = 1159;
UPDATE topics SET name_hi = 'प्रमुख साहित्यकार और उनकी रचनाएं' WHERE id = 1160;
UPDATE topics SET name_hi = 'राज्य की साहित्यिक संस्थाएं' WHERE id = 1161;
UPDATE topics SET name_hi = 'छत्तीसगढ़ का लोक संगीत' WHERE id = 1162;
UPDATE topics SET name_hi = 'लोक नृत्य शैलियां' WHERE id = 1163;
UPDATE topics SET name_hi = 'लोक नाट्य' WHERE id = 1164;
UPDATE topics SET name_hi = 'लोक कला परंपराएं' WHERE id = 1165;
UPDATE topics SET name_hi = 'राज्य द्वारा स्थापित सांस्कृतिक संस्थाएं' WHERE id = 1166;
UPDATE topics SET name_hi = 'साहित्य, संगीत, ललित कला में राज्य के पुरस्कार/सम्मान' WHERE id = 1167;
UPDATE topics SET name_hi = 'जनउला (पहेलियां)' WHERE id = 1168;
UPDATE topics SET name_hi = 'मुहावरे' WHERE id = 1169;
UPDATE topics SET name_hi = 'हाना (लोकोक्तियाँ)' WHERE id = 1170;
UPDATE topics SET name_hi = 'लोकोक्तियां' WHERE id = 1171;
UPDATE topics SET name_hi = 'शब्दावली और व्याकरण के मूल तत्व (शब्द रचना, उपसर्ग/प्रत्यय)' WHERE id = 1172;
UPDATE topics SET name_hi = 'विशेष पिछड़ी/विशेष रूप से कमजोर जनजातीय समूह (PVTGs)' WHERE id = 1173;
UPDATE topics SET name_hi = 'प्रमुख और गौण जनजातियां' WHERE id = 1174;
UPDATE topics SET name_hi = 'जनजातीय सामाजिक संगठन (विवाह, परिवार, गोत्र, युवा गृह/घोटुल)' WHERE id = 1175;
UPDATE topics SET name_hi = 'जनजातियों के आभूषण और पारंपरिक परिधान' WHERE id = 1176;
UPDATE topics SET name_hi = 'जनजातीय विकास का इतिहास, कार्यक्रम और संवैधानिक प्रावधान' WHERE id = 1177;
UPDATE topics SET name_hi = 'जनजातीय समस्याएं - अलगाव, प्रवास, परसंस्कृतिग्रहण' WHERE id = 1178;
UPDATE topics SET name_hi = 'छत्तीसगढ़ की अनुसूचित जातियां और अन्य पिछड़ा वर्ग' WHERE id = 1179;
UPDATE topics SET name_hi = 'छत्तीसगढ़ के प्रमुख मेले' WHERE id = 1180;
UPDATE topics SET name_hi = 'धार्मिक और मौसमी त्योहार' WHERE id = 1181;
UPDATE topics SET name_hi = 'जनजातीय त्योहार और अनुष्ठान' WHERE id = 1182;
UPDATE topics SET name_hi = 'छत्तीसगढ़ के प्रमुख संत (गुरु घासीदास आदि)' WHERE id = 1183;
UPDATE topics SET name_hi = 'राज्य की आय और आर्थिक संकेतक' WHERE id = 1184;
UPDATE topics SET name_hi = 'SC/ST/OBC/अल्पसंख्यकों का सामाजिक-आर्थिक पिछड़ापन' WHERE id = 1185;
UPDATE topics SET name_hi = 'रोजगार और आय वितरण की प्रवृत्तियां' WHERE id = 1186;
UPDATE topics SET name_hi = 'महिलाओं का सामाजिक-राजनीतिक-आर्थिक सशक्तिकरण' WHERE id = 1187;
UPDATE topics SET name_hi = 'बाल श्रम की समस्याएं' WHERE id = 1188;
UPDATE topics SET name_hi = 'ग्रामीण विकास कार्यक्रम' WHERE id = 1189;
UPDATE topics SET name_hi = 'राज्य वित्त - बजट, कर संरचना, केंद्रीय कर हिस्सा' WHERE id = 1190;
UPDATE topics SET name_hi = 'सार्वजनिक ऋण संरचना' WHERE id = 1191;
UPDATE topics SET name_hi = 'ग्रामीण साख - संस्थागत/गैर-संस्थागत स्रोत' WHERE id = 1192;
UPDATE topics SET name_hi = 'सहकारी क्षेत्र - संरचना और विकास' WHERE id = 1193;
UPDATE topics SET name_hi = 'प्रमुख फसलें (खाद्यान्न, दलहन, तिलहन)' WHERE id = 1194;
UPDATE topics SET name_hi = 'फसलों का उत्पादन और वितरण' WHERE id = 1195;
UPDATE topics SET name_hi = 'छत्तीसगढ़ में सिंचाई परियोजनाएं' WHERE id = 1196;
UPDATE topics SET name_hi = 'कृषि की समस्याएं और किसानों के लिए राज्य की योजनाएं' WHERE id = 1197;
UPDATE topics SET name_hi = 'वन आवरण और वनों के प्रकार' WHERE id = 1198;
UPDATE topics SET name_hi = 'वन नीति और संरक्षण' WHERE id = 1199;
