UPDATE subjects SET name_hi = 'भारत का इतिहास एवं भारतीय राष्ट्रीय आंदोलन' WHERE id = 1;
UPDATE subjects SET name_hi = 'भारतीय अर्थव्यवस्था' WHERE id = 7;
UPDATE subjects SET name_hi = 'सामान्य विज्ञान' WHERE id = 8;
UPDATE subjects SET name_hi = 'प्रौद्योगिकी' WHERE id = 9;
UPDATE subjects SET name_hi = 'भारतीय दर्शन' WHERE id = 10;
UPDATE subjects SET name_hi = 'भारत की कला, साहित्य एवं संस्कृति' WHERE id = 11;
UPDATE subjects SET name_hi = 'समसामयिकी (राष्ट्रीय/अंतर्राष्ट्रीय)' WHERE id = 12;
UPDATE subjects SET name_hi = 'खेल-कूद' WHERE id = 13;
UPDATE subjects SET name_hi = 'पर्यावरण' WHERE id = 14;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ का भूगोल' WHERE id = 17;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ की जनगणना एवं जनसांख्यिकी' WHERE id = 18;
UPDATE subjects SET name_hi = 'पुरातात्विक एवं पर्यटन केंद्र' WHERE id = 19;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ का साहित्य' WHERE id = 20;
UPDATE subjects SET name_hi = 'संगीत, नृत्य, कला एवं संस्कृति' WHERE id = 21;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ी मुहावरे, हाना एवं लोकोक्तियां' WHERE id = 22;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ की जनजातियां' WHERE id = 23;
UPDATE subjects SET name_hi = 'विशेष परंपराएं, तीज एवं त्यौहार' WHERE id = 24;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ की अर्थव्यवस्था' WHERE id = 25;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ के वन एवं कृषि' WHERE id = 26;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ का प्रशासनिक ढांचा' WHERE id = 27;
UPDATE subjects SET name_hi = 'स्थानीय शासन एवं पंचायती राज' WHERE id = 28;
UPDATE subjects SET name_hi = 'उद्योग, ऊर्जा, जल एवं खनिज संसाधन' WHERE id = 29;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ की समसामयिकी' WHERE id = 30;
UPDATE subjects SET name_hi = 'पारस्परिक एवं संचार कौशल' WHERE id = 31;
UPDATE subjects SET name_hi = 'तार्किक क्षमता' WHERE id = 32;
UPDATE subjects SET name_hi = 'विश्लेषणात्मक क्षमता' WHERE id = 33;
UPDATE subjects SET name_hi = 'निर्णय निर्माण एवं समस्या समाधान' WHERE id = 34;
UPDATE subjects SET name_hi = 'सामान्य मानसिक योग्यता' WHERE id = 35;
UPDATE subjects SET name_hi = 'मूल संख्यात्मकता (कक्षा 10वीं स्तर)' WHERE id = 36;
UPDATE subjects SET name_hi = 'आंकड़ों की व्याख्या' WHERE id = 37;
UPDATE subjects SET name_hi = 'हिंदी भाषा ज्ञान (कक्षा 10वीं स्तर)' WHERE id = 38;
UPDATE subjects SET name_hi = 'छत्तीसगढ़ी भाषा ज्ञान' WHERE id = 39;
