-- Update topics name_hi Part 2

UPDATE topics SET name_hi = 'वन्यजीव प्रबंधन (राष्ट्रीय उद्यान और अभयारण्य)' WHERE id = 1200;
UPDATE topics SET name_hi = 'राज्य कार्यपालिका, विधायिका, न्यायपालिका' WHERE id = 1201;
UPDATE topics SET name_hi = 'जिला प्रशासन व्यवस्था' WHERE id = 1202;
UPDATE topics SET name_hi = 'राजस्व प्रशासन' WHERE id = 1203;
UPDATE topics SET name_hi = 'छत्तीसगढ़ में पंचायती राज संस्थाएं' WHERE id = 1204;
UPDATE topics SET name_hi = 'शहरी स्थानीय निकाय (नगर निगम संरचना)' WHERE id = 1205;
UPDATE topics SET name_hi = 'राज्य के संदर्भ में 73वां/74वां संशोधन' WHERE id = 1206;
UPDATE topics SET name_hi = 'खनिज संसाधन - प्रकार, भंडार, उत्पादन, वितरण' WHERE id = 1207;
UPDATE topics SET name_hi = 'ऊर्जा संसाधन (कोयला, तापीय ऊर्जा, गैर-पारंपरिक स्रोत)' WHERE id = 1208;
UPDATE topics SET name_hi = 'औद्योगिक विकास और संरचना (बड़े, मध्यम, लघु उद्योग)' WHERE id = 1209;
UPDATE topics SET name_hi = 'कृषि, वन और खनिज आधारित उद्योग' WHERE id = 1210;
UPDATE topics SET name_hi = 'छत्तीसगढ़ में परिवहन के साधन' WHERE id = 1211;
UPDATE topics SET name_hi = 'हालिया राज्य सरकार की योजनाएं और नीतियां' WHERE id = 1212;
UPDATE topics SET name_hi = 'हालिया नियुक्तियां और पुरस्कार (राज्य स्तर)' WHERE id = 1213;
UPDATE topics SET name_hi = 'राज्य सरकार की पहल (पिछले 1 वर्ष की)' WHERE id = 1214;
UPDATE topics SET name_hi = 'हालिया बुनियादी ढांचा/विकास परियोजनाएं' WHERE id = 1215;
UPDATE topics SET name_hi = 'बोधगम्यता आधारित तर्क (Comprehension-based reasoning)' WHERE id = 1216;
UPDATE topics SET name_hi = 'प्रभावी संचार की अवधारणाएं' WHERE id = 1217;
UPDATE topics SET name_hi = 'समरूपता / समानता आधारित प्रश्न (Analogy)' WHERE id = 1218;
UPDATE topics SET name_hi = 'विषम छांटना (शब्द/संख्या)' WHERE id = 1219;
UPDATE topics SET name_hi = 'विषम शब्द युग्म' WHERE id = 1220;
UPDATE topics SET name_hi = 'कोडिंग-डिकोडिंग' WHERE id = 1221;
UPDATE topics SET name_hi = 'रक्त संबंध (Blood Relations)' WHERE id = 1222;
UPDATE topics SET name_hi = 'वर्णमाला परीक्षण (Alphabet Test)' WHERE id = 1223;
UPDATE topics SET name_hi = 'श्रृंखला पूर्ण करना (संख्या/आकृति/अक्षर)' WHERE id = 1224;
UPDATE topics SET name_hi = 'कथन और कारण' WHERE id = 1225;
UPDATE topics SET name_hi = 'स्थिति प्रतिक्रिया परीक्षण (Situation Reaction Test)' WHERE id = 1226;
UPDATE topics SET name_hi = 'लुप्त संख्या/शब्द प्रविष्टि' WHERE id = 1227;
UPDATE topics SET name_hi = 'शब्दों का तार्किक विश्लेषण' WHERE id = 1228;
UPDATE topics SET name_hi = 'आंकड़े पर्याप्तता (Data sufficiency)' WHERE id = 1229;
UPDATE topics SET name_hi = 'पैटर्न पहचान (Pattern recognition)' WHERE id = 1230;
UPDATE topics SET name_hi = 'स्थिति आधारित निर्णय परिदृश्य (Case-based decisions)' WHERE id = 1231;
UPDATE topics SET name_hi = 'समस्या समाधान तकनीक (Problem-solving techniques)' WHERE id = 1232;
UPDATE topics SET name_hi = 'पहेलियां (Puzzles)' WHERE id = 1233;
UPDATE topics SET name_hi = 'दृश्य/आकृति तर्क (Visual reasoning)' WHERE id = 1234;
UPDATE topics SET name_hi = 'संख्या प्रणाली और मूल अंकगणितीय संचालन' WHERE id = 1235;
UPDATE topics SET name_hi = 'अनुपात और समानुपात' WHERE id = 1236;
UPDATE topics SET name_hi = 'प्रतिशत, लाभ और हानि' WHERE id = 1237;
UPDATE topics SET name_hi = 'साधारण और चक्रवृद्धि ब्याज' WHERE id = 1238;
UPDATE topics SET name_hi = 'समय, गति और दूरी (नाव और धारा सहित)' WHERE id = 1239;
UPDATE topics SET name_hi = 'औसत' WHERE id = 1240;
UPDATE topics SET name_hi = 'लघुत्तम समापवर्त्य (LCM) और महत्तम समापवर्तक (HCF), गुणनखंड' WHERE id = 1241;
UPDATE topics SET name_hi = 'वैदिक गणित तकनीकें (वर्ग, घन, मूल)' WHERE id = 1242;
UPDATE topics SET name_hi = 'बैंकिंग गणना (बचत, सावधि जमा, आवर्ती जमा ब्याज)' WHERE id = 1243;
UPDATE topics SET name_hi = 'आयकर गणना के मूल तत्व' WHERE id = 1244;
UPDATE topics SET name_hi = 'भारतीय गणितज्ञ (आर्यभट्ट, ब्रह्मगुप्त, भास्कराचार्य, रामानुजन)' WHERE id = 1245;
UPDATE topics SET name_hi = 'चार्ट और ग्राफ' WHERE id = 1246;
UPDATE topics SET name_hi = 'सारणियां (Tables)' WHERE id = 1247;
UPDATE topics SET name_hi = 'आंकड़े पर्याप्तता (Data Sufficiency)' WHERE id = 1248;
UPDATE topics SET name_hi = 'सांख्यिकीय माप (माध्य, माध्यिका, बहुलक)' WHERE id = 1249;
UPDATE topics SET name_hi = 'प्रायिकता (मूल प्रमेय)' WHERE id = 1250;
UPDATE topics SET name_hi = 'व्याकरण के मूल तत्व (Grammar basics)' WHERE id = 1251;
UPDATE topics SET name_hi = 'बोध (Comprehension)' WHERE id = 1252;
UPDATE topics SET name_hi = 'मूल शब्दावली और बोध (Basic vocabulary & comprehension)' WHERE id = 1253;
UPDATE topics SET name_hi = 'सामान्य उपयोग (Common usage)' WHERE id = 1254;
